### PR TITLE
Swaroop: Initial Commit for Homework2

### PR DESCRIPTION
**Pull request by akhileshamara**

### CODE REVIEW

**Comment by swarooprm** [comment]
@kuntalkumarpal, wondering if you can review this PR?

**Comment by kuntalkumarpal** [comment]
Task 009 and 010 seem exactly same one is yes/no ans and another is 1/0 ans. @swarooprm do you consider them as different task

**Comment by kuntalkumarpal** [comment]
task 011. The explanation does not match the description of the task. It is mentioned to keep named entities preserved but the negative explanations says about uppercases, brackets missing, positive explanations do not mention anything about named entities.

**Comment by akhileshamara** [comment]
@kuntalkumarpal @swarooprm 
Task 009 and 010 are created after Swaroop clarifies one of them is **answer generation type classification** and the other is answer generation for a **prompt** type classification.
task 011,012,013 are general transaction tasks. I updated the task definition accordingly. 

Please let me know any further changes are required

**Comment by swarooprm** [comment]
Make sure the prompt varies: the problem right now is prompt is constant.
What I was saying is have a prompt that says "does this contain harmful content?"
and then another which says "are the content non-harmful" or something like that?

@kuntalkumarpal, these 2 might not be completely unique, but should be ok for this PR as he has 5 tasks (1 more than the min. threshold of 4 tasks).
@kuntalkumarpal  Please check and let me know if you are happy with the PR or have any feedback?

**Comment by kuntalkumarpal** [comment]
@swarooprm Looks good

**Comment by swarooprm** [comment]
Thanks! 
@akhileshamara once you do the above 2 fixes as I suggested above, your HW2 will be complete.

**Comment by akhileshamara** [comment]
@swarooprm I have updated the prompts. Also, the datasets are balanced. Thank you

**Comment by swarooprm** [comment]
Your HW2 is complete now.

Would you like to submit the same tasks to our big project repo https://github.com/allenai/natural-instructions-expansion/pulls? You just need to fork that repo, rename tasks starting from the latest number in the repo and create PR there. This way, you can be part of our research on "learning from instructions instead of learning from examples (conventional machine learning)". This is purely optional and your HW2 grade does not depend on this @akhileshamara

**Comment by swarooprm** [comment]
@akhileshamara  Just a reminder that, if you plan to submit these tasks to the main Github repo and join our research project, Monday (27th Sept) is the deadline. Again, this is optional and independent of your HW2 grade.

**Pull request closed without merging**
