### PR TITLE
Swaroop: Tasks 297-304: News_Commentary and DataCommon_FactCheck datasets

### PR DESCRIPTION
**Pull request by vagishagupta**

### CODE REVIEW

**Comment by vagishagupta** [comment]
Hello @swarooprm,

Please review my PR. My build was failing due to presence of redundant input data in the dataset which is now fixed.

**Comment by swarooprm** [comment]
@jayavardhan3112, wondering if you can help review this PR?

**Comment by jayavardhan3112** [comment]
Thanks for the update!
Some generic changes to be addressed, These are the following things that needs your attention

- Edit your readme, elaborate your Summary in a little bit more detail. It would be better if you make readme a little bit more informative by providing more context.
- Change `Translation` -> `Language Translation` in the Readme file, and the respective files and also mention the type of `Classification` if available.
- Please all the research paper link and the dataset link In the source of all the instructions.
- The instances in the language translation tasks were not rendered properly, because most of the languages other than english are showing garbage values, may be because of the encoding issue. 
-- Refer to this [Saving utf-8 texts with json.dumps as UTF8, not as \u escape sequence](https://stackoverflow.com/questions/18337407/saving-utf-8-texts-with-json-dumps-as-utf8-not-as-u-escape-sequence)

**Comment by swarooprm** [comment]
@vagishagupta: Can you address reviewer comments so that I can evaluate your HW?

**Comment by vagishagupta** [comment]
@swarooprm Sure, I will make the changes.

- Can you please help me with all details I should add in the Readme.
- I will update the 'Translations' to 'Language Translation'.
- The dataset link is already there in the Source, I will add the research paper link
- I presumed that the languages had to dumped in json so they should be encoded. Should I decode all the sentences in the instances as given in the link provided above?

**Comment by jayavardhan3112** [comment]
> * I presumed that the languages had to dumped in json so they should be encoded. Should I decode all the sentences in the instances as given in the link provided above?

Yes, you should decode all the sentences, because they aren't readable, since they are in the format (utf-8). You need to change them to their corresponding language.

**Comment by swarooprm** [comment]
Your tasks look good. Some final comments and your HW2 will be complete as soon as you do this.
Write definition as if you are instructing someone. Here's an example, make sure to change other definition similarly.
- "In this task, we have news commentary as given input statement that needs to be classified into the language that the sentence is written in"--->"In this task, we have news commentary given as input statement. Classify the input into the language in which it is written in"
- fix the utf8 encoding issue as Jay suggested so that instances are readable.
- make sure classes are balanced in classification tasks.
- fix typo and grammatical mistakes.

**Comment by vagishagupta** [comment]
Hello @swarooprm 
I have made the changes as suggested by you and @jayavardhan3112. Please review and let me know if any other updates are required.

**Comment by swarooprm** [comment]
@jayavardhan3112, check if you are happy or have any other feedback?

**Comment by jayavardhan3112** [comment]
> @jayavardhan3112, check if you are happy or have any other feedback?

Looks good to me, we can move forward with the merge.

**Comment by swarooprm** [comment]
Your HW2 is complete now.

Would you like to submit the same tasks to our big project repo https://github.com/allenai/natural-instructions-expansion/pulls? You just need to fork that repo, rename tasks starting from the latest number in the repo and create PR there. This way, you can be part of our research on "learning from instructions instead of learning from examples (conventional machine learning)". This is purely optional and your HW2 grade does not depend on this @jayavardhan3112

**Comment by swarooprm** [comment]
@vagishagupta  Just a reminder that, if you plan to submit these tasks to the main Github repo and join our research project, Monday (27th Sept) is the deadline. Again, this is optional and independent of your HW2 grade.

**Pull request closed without merging**
