### PR TITLE
Complete Tasks 201-204: SBIC and ConLLPP

### PR DESCRIPTION
**Pull request by arlenfan**

### CODE REVIEW

**Comment by swarooprm** [comment]
@Mihir3009, wondering if you can help reviewing this task?

**Comment by Mihir3009** [comment]
1. Add a Link for the dataset, it will look like this:
       "Source": [
        "SBIC (Link - [add dataset link])"
    ]

Task 201:

1. Let's make the definition more comprehensive. Change definition to this - "In this task, you are given a text from a post. Your task is to classify a given post into two categories: 1) yes if the given post is intentionally offensive, 2) no, otherwise. Also, generate label 'no' if offensive statements that appear to be unintentional, or non-offensive statements that are underhandedly offensive." (This is what you mean. Right?)
2. Please make sure that your dataset is balanced meaning you have the almost same number of yes and no examples.

Task 202:

1.  Let's make the definition more comprehensive. Change definition to this - "In this task, you are given a text from a post. Your task is to classify a given post into two categories: 1) yes if the given post is sexually offensive, 2) no, otherwise. Emphasis on sexually offensive or any lewd reference. Generate label 'no' for offensive posts that do not reference sexually explicit content."
2. Please make sure that your dataset is balanced meaning you have the almost same number of yes and no examples.

Task 203:

1.  Let's make the definition more comprehensive. Change definition to this - "In this task, you are given a text from a post. Your task is to classify a given post into two categories: 1) yes if the given post is potentially offensive to anyone (i.e., a subset of people, any particular person, etc.), 2) no, otherwise. Note that potentially offensive posts can contain sexual, racial, religious biased or offensive language."
2. Please make sure that your dataset is balanced meaning you have the almost same number of yes and no examples.

Task 204:

1. Let's make the definition more comprehensive. Change definition to this - "In this task, you are given a text from a post. Your task is to find all of the proper nouns and label them. The labels are <B-PER>, <I-PER> for persons; <B-ORG>, <I-ORG> for organizations; <B-LOC>, <I-LOC> for locations; and <B-MISC>, <I-MISC> for other nouns. The capital 'B' denotes the first word of a proper noun phrase. The capital 'I' denotes all following words of the same noun phrase. If a word is not a part of a proper noun phrase, do not label it."
2. Write down the examples in positive examples and explain there how they should be labeled rather than in the definition.

Please review these comments.

**Comment by arlenfan** [comment]
All your comments have been addressed.

**Comment by Mihir3009** [comment]
https://github.com/arlenfan/CSE576HW/blob/dce3fecebdc0e88d512304baab160f5a428f4d8b/tasks/task204_conllpp_ner.json#L11 

In this definition, please add tags, I think they were removed from the definition. Just check. It's not showing in JSON definition.

**Comment by arlenfan** [comment]
@Mihir3009 The tags have been added back in.

**Comment by Mihir3009** [comment]
Looks good to me!

**Comment by swarooprm** [comment]
Your HW2 is complete.

Would you like to submit the same tasks to our big project repo https://github.com/allenai/natural-instructions-expansion/pulls? You just need to fork that repo, rename tasks starting from the latest number in the repo (which at this point is 591) and create PR there. This way, you can be part of our research on "learning from instructions instead of learning from examples (conventional machine learning)". This is purely optional and your HW2 grade does not depend on this @arlenfan ?

**Pull request closed without merging**
