### PR TITLE
Task 168-Task 188 Variants Phase 1

### PR DESCRIPTION
**Pull request by PhaniRohithaKaza**

### CODE REVIEW

**Comment by Ravsehajsinghpuri** [comment]
@PhaniRohithaKaza Can you resolve the conflicts?

**Comment by PhaniRohithaKaza** [comment]
@Ravsehajsinghpuri Hi, I tried with the original files pushing too for the tasks 171-175, it's still showing the same error as attached below. I think my files are correct, but I don't know why it's not accepting as said it's not even passing the original files too. @swarooprm could you please help me with this.
image

**Comment by Ravsehajsinghpuri** [comment]
@PhaniRohithaKaza from what I can see, there is some issue regarding json encoding, maybe when writing to json, use a suitable, stable library which takes care of formatting it correctly. @swarooprm can you guide on this piece why is it failing?

**Comment by PhaniRohithaKaza** [comment]
@Ravsehajsinghpuri yes, but it's showing the same error even for the original task files. Because of that I'm not sure.

**Comment by PhaniRohithaKaza** [comment]
@swarooprm I have replaced the test_all.py and pushed the code. Now, I'm getting the README.md conflict, could you please help me to resolve this.

**Comment by Ravsehajsinghpuri** [comment]
@PhaniRohithaKaza Will take care of that. few more modifications - 1) Can you add the original tasks in this PR with their original names. 2) Can you rename the task variants as taskxxx.1_yyyy, taskxxx.2_yyyy, taskxxx.3_yyyy and so on. For e.g. task547.1_spl_translation_entk_en.json, task547.2_spl_translation_entk_en.json, task547.3_spl_translation_entk_en.json and so on. Do this for all the tasks in this PR

**Comment by PhaniRohithaKaza** [comment]
@Ravsehajsinghpuri I have made the above mentioned changes and pushed the code. Please let me know if there are any additional changes needed to be made. Thanks in advance :)

**Comment by Ravsehajsinghpuri** [comment]
@PhaniRohithaKaza there are conflicts which I cannot solve, pls do a git pull and then commit, in order to make it consistent with the updated 'main'

**Comment by Ravsehajsinghpuri** [comment]
> @PhaniRohithaKaza there are conflicts which I cannot solve, pls do a git pull and then commit, in order to make it consistent with the updated 'main'

friendly reminder on this - pls try to complete it at the earliest if not by Friday

**Comment by PhaniRohithaKaza** [comment]
@Ravsehajsinghpuri I'm still trying to resolve it. Definitely I will try to push the code by end of today. Thank you.

**Comment by Ravsehajsinghpuri** [comment]
> @Ravsehajsinghpuri I'm still trying to resolve it. Definitely I will try to push the code by end of today. Thank you.

sounds good, thanks!

**Comment by PhaniRohithaKaza** [comment]
- I added `encoding='utf-8-sig'` in the test_all.py file while opening the file name (since most of my tasks are not in english) I used utf-8 encoding to encode the files. 
- Also, I tried using allenai `test_all.py` as suggested by @swarooprm  but since the home directory has unnecessary files, like pdf and json it's throwing an Assertion error.

**Comment by Ravsehajsinghpuri** [comment]
@swarooprm Can you please review this PR?

**Comment by PhaniRohithaKaza** [comment]
@Ravsehajsinghpuri Is it possible for you to remove the files shown in the below image? Please let me know.
nlpgit

**Comment by swarooprm** [comment]
I think @PhaniRohithaKaza' s additon to utf-8 encoding to test_all.py is reasonable. I don't think we have a better workaround here. @yeganehkordi is an expert in this matter, do you have any solution to fix this without editing the test file  @yeganehkordi?

**Comment by Ravsehajsinghpuri** [comment]
> @Ravsehajsinghpuri Is it possible for you to remove the files shown in the below image? Please let me know.
> nlpgit

why do you want to delete these files?

**Comment by PhaniRohithaKaza** [comment]
> > @Ravsehajsinghpuri Is it possible for you to remove the files shown in the below image? Please let me know.
> > nlpgit
> 
> why do you want to delete these files?

I'm getting Assertion error when I'm trying to Git push after making the Git pull.

**Comment by yeganehkordi** [comment]
> I think @PhaniRohithaKaza' s additon to utf-8 encoding to test_all.py is reasonable. I don't think we have a better workaround here. @yeganehkordi is an expert in this matter, do you have any solution to fix this without editing the test file @yeganehkordi?

@PhaniRohithaKaza, I guess you can solve the error by dumping the decoded data into the JSON files. Try this script:
`data = codecs.decode(text, 'utf-8-sig')`
`with open('filename.json', 'w') as f:`
    `json.dump(data, f)`

**Comment by Ravsehajsinghpuri** [comment]
@yeganehkordi Thanks a lot for the guidance, @PhaniRohithaKaza Can you try this out and fix this by today?

**Comment by PhaniRohithaKaza** [comment]
@Ravsehajsinghpuri yes, definitely I will submit by end of today. Thanks @yeganehkordi i will try that.

**Comment by PhaniRohithaKaza** [comment]
@swarooprm @yeganehkordi @Ravsehajsinghpuri I tried the code you suggested. But still it's not working. I'm attaching the screenshot of the error below.
againerror

**Comment by swarooprm** [comment]
@yeganehkordi, any suggestion?

**Comment by yeganehkordi** [comment]
I'll check the files to see if there is another solution.

**Comment by PhaniRohithaKaza** [comment]
@yeganehkordi Thank You. And the problem is only with the tasks from 171-175 translation tasks.

**Comment by Ravsehajsinghpuri** [comment]
@PhaniRohithaKaza Do you need to commit anything to this PR or should I go ahead and merge it to main? Have you added all the task which were assigned to you along with their variants?

**Comment by PhaniRohithaKaza** [comment]
> @PhaniRohithaKaza Do you need to commit anything to this PR or should I go ahead and merge it to main? Have you added all the task which were assigned to you along with their variants?

@Ravsehajsinghpuri I have added all the required files.

**Pull request merged**
