### PR TITLE
Complete: Maitreya: Task 1113-1117: SciTail and Cnn-Dailymail Dataset

### PR DESCRIPTION
**Pull request by nbhimte**

### CODE REVIEW

**Review by Maitreyapatel — CHANGES_REQUESTED** [review]
1. No need to remove anything from the readme.
2. Keep the task files count from 113-117 (i.e., in 3 digits).
3. Task115 is a classification task. So, replace Entailment with Classification in readme.
4. You do not have to delete task1001 and task1002 files.
5. Task113:
a. Keep the definition natural. Change to “In this task, we ask you to create a question based on a given scientific fact” to “Given scientific fact as input, generate the question from this fact such that it can be answered from the input." 
6. Task114:
a. Again keep in mind that your definitions should be clear and specific. Just mention that there are news articles instead of saying they are from CNN and Dailymail. And explain the summarization task. Like, How long do you need? Is it just one sentence? What are the things a summary/highlight should have? Something on this line.
7. Task115:
a. Please explain clearly what the classes are for your task and how to classify them. For example, explain what entailment is.
Task category should be Classification.
b. Positive examples contain only “entails” class. And Negative examples contain “neutral” classes. But you need to give both class examples in these sections. In a can of negative examples, you need to show what is wrong classification and explain why and what is the correct answer. 
c. Please be sure that your grammar is correct in all the task files (i.e., in definition and explanations).
8. Task116: 
a. The task is Answer Generation but your definition says a completely different thing. Please write the proper definition. 
9. Task117:
a. In this definition, you are asking to generate sentences. But what is this sentence ? Is it random ? Is it based on Question-Answer ? 

You mainly need to work on your definitions. Before submitting, take others' opinions. Ask your friend or roommate to read them and check whether they can understand or not.

**Review by Maitreyapatel — COMMENTED** [review]
Few more minor suggestions to improve these tasks:
1. Task115: What is the data distribution? (i.e., how many examples are there for each class? Are they balance?) If it's not balanced then make them balanced.
2. Task116: You need to further explain the task in definition. You have to generate the answer but what kind of answer? Is it open ended or Does the answer belong to the input text ? 
3. Task117: Same as task116 don't just write that generate the sentence based on QA. But clearly mention few things like answer should be in the generated sentence if that's the requirement, if not mention that answer can be open-ended so, generate the sentence such that answer does not belong. 

There should not be any assumptions in the definition. Please updated the task files from above mentioned minor changes. And we will accept your homework.

**Comment by swarooprm** [comment]
@Maitreyapatel, check and let me know if you are happy or have any other feedback?

**Comment by swarooprm** [comment]
Your HW2 is complete now.

Would you like to submit the same tasks to our big project repo https://github.com/allenai/natural-instructions-expansion/pulls? You just need to fork that repo, rename tasks starting from the latest number in the repo and create PR there. This way, you can be part of our research on "learning from instructions instead of learning from examples (conventional machine learning)". This is purely optional and your HW2 grade does not depend on this @nbhimte

**Comment by swarooprm** [comment]
@nbhimte, Just a reminder that, if you plan to submit these tasks to the main Github repo and join our research project, Monday (27th Sept) is the deadline. Again, this is optional and independent of your HW2 grade.

**Pull request closed without merging**
