### PR TITLE
Complete: Tasks 649-652: Quail, Rotten Tomatoes and Go Emotions Dataset

### PR DESCRIPTION
**Pull request by saianirud**

### CODE REVIEW

**Comment by swarooprm** [comment]
@Mihir3009, wondering if you can help reviewing this task?

**Comment by Mihir3009** [comment]
1. In the “Source”, please add dataset name also. See below, you will get the idea: “Source”: [
	“Dataset Name (Link - [give link] )”
]

Task 649:

1. In the definition, there are spelling mistakes, please change to this: -- In this task, you are given a passage and your task is to generate a question from the information in the passage such that it can be inferred directly from the passage.
2. What do you mean by "Directly inferred from the passage"? Please explain that part in the definition clearly.
3. In the positive examples, there are many things that you can infer from the passage, but why this specific information, Please write a more clear explanation for the examples.
    For example: In the first input passage, there can be a possible question that "Which is a favourite proverb for the author?", but why specific question generated is important. Explain that in the definition.

Task 650:

1. Let's make the definition more comprehensive, change it to this: "In this task, you are given a context passage and a question. Your task is to generate the right answer to the given question based on a given context passage."

Task 651:

1. Let's make the definition more comprehensive, change it to this: "In this task, you are given a review of the movie. Your task is to classify given movie review into two categories: 1) positive, and 2) negative based on its content."
2. Please change 1 to positive and 0 to negative in examples and instances.

Task 652:

1. Let's make the definition more comprehensive, change it to this: "In this task, you are given a sentence. Your job is to classify a given sentence into one of the five different emotions: 1) anger, 2) confusion, 3) joy, 4) sadness and 5) neutral."
2. Please change numbers into the emotion names in all examples and instances.

Please address all comments.

**Comment by saianirud** [comment]
@Mihir3009 I made the changes you requested. Let me know if it needs more corrections.

**Comment by Mihir3009** [comment]
Just quick two questions:

1. In task 649, in the definition, you wrote that "generate a question for the character", something like that, but there are questions based on "What" where answers are not related to character. Can you please update the definition more clearly?
2. Please write down here the number of samples for each class in Task 651 and 652.

**Comment by saianirud** [comment]
@Mihir3009 I made the changes for task 649.
For Task 651 - No of instances are 1) positive - 250     2) negative - 250
For Task 652 - No of instances are 1) anger - 100     2) confusion - 100     3) joy - 100     4) sadness - 100     5) neutral - 100

Let me know if there any further changes.

**Comment by Mihir3009** [comment]
Looks good to me.

**Comment by saianirud** [comment]
@swarooprm I think the PR has been reviewed. Let me know if anything extra needs to be done.

**Comment by swarooprm** [comment]
Your HW2 is complete now.

Would you like to submit the same tasks to our big project repo https://github.com/allenai/natural-instructions-expansion/pulls? You just need to fork that repo, rename tasks starting from the latest number in the repo (which at this point is 522) and create PR there. This way, you can be part of our research on "learning from instructions instead of learning from examples (conventional machine learning)". This is purely optional and your HW2 grade does not depend on this @saianirud

**Comment by swarooprm** [comment]
@saianirud  Just a reminder that, if you plan to submit these tasks to the main Github repo and join our research project, Monday (27th Sept) is the deadline. Again, this is optional and independent of your HW2 grade.

**Pull request closed without merging**
