### PR TITLE
Complete: Task 433-436: MSR dataset, Amazon review Dataset

### PR DESCRIPTION
**Pull request by vinayak15**
Name - Vinayak Kothari (vkothar3@asu.edu)  ASU ID - 1219114741

### CODE REVIEW

**Comment by vinayak15** [comment]
@swarooprm Can you please let me know changes that need be made

**Comment by swarooprm** [comment]
1. Task433: Definition is grammatically incorrect "In this task you a text and write a compression for this text.", think how will you explain this task to your friend, that should be your definition. Current definition needs major modification. Category: "Text Compression"
2. Task434: Same problem in definition as above. Also, in this task you need to define what are the various possible domains, you should have a list of domains in the definition, and then ask model to choose one of the domains. Category: 'Answer Generation
3. Task435: 2nd example in positive example needs to be changed, I did not like the output there. Category: "Answer Generation". Category: "Summarization"
4. Task 436: Grammatical incorrect definition "In this task you will be given a review body give rating for this product.". Instead of asking a model to predict a rating from 0-5, I would say make it a binary classfication problem by converting samples with lower than 2.5 to be bad rating and higher than 2.5 to good rating. This would make the task more reasonable. Make sure to specify it in the defintion.
Let me know once you are done and I can review again @vinayak15

**Comment by vinayak15** [comment]
@swarooprm  I have made changes to file, can you please check again and let me know.

**Comment by swarooprm** [comment]
@vinayak15, there are still grammatical errors
e.g. task433: "In this task you a will be given a text and you have to write compressed version of given text."-->"In this task you will be given a text and you have to write compressed version of the given text."
Make sure to check grammar both manually and by using grammarly and then I will review these tasks again.

**Comment by vinayak15** [comment]
@swarooprm  I changed the grammar, can you please check now.

**Review by swarooprm — COMMENTED** [review]
task 433 and 435 look good.

task 434 a human can't answer. It's indeed difficult to identify source from text. Seems random to me.
task436 contains annotation errors, e.g. the following is incorrect.
            "input": "My Grand girl is having issues downloading games and programs. The process will get to the end and then it stops. These are normal games, they are not very high tech. I am very disappointed with this tablet since we were very careful in our research.",
            "output": [
                "Positivie Review"
Either modify these tasks so they are more reliable or add new tasks to compensate for these 2 tasks.

**Comment by vinayak15** [comment]
@swarooprm I have changed for task 436, for task 434 I asked question to check whether input statement has any grammatical error and does it make meaningful sentences and to be divided in bad and good statement

**Review by swarooprm — COMMENTED** [review]
Great. Your HW2 is complete.

Would you like to submit the same tasks to our big project repo https://github.com/allenai/natural-instructions-expansion/pulls? You just need to fork that repo, rename tasks starting from the latest number in the repo (which at this point is 591) and create PR there. This way, you can be part of our research on "learning from instructions instead of learning from examples (conventional machine learning)". This is purely optional and your HW2 grade does not depend on this @vinayak15 ?

**Comment by swarooprm** [comment]
@vinayak15  Just a reminder that, if you plan to submit these tasks to the main Github repo and join our research project, Monday (27th Sept) is the deadline. Again, this is optional and independent of your HW2 grade.

**Pull request closed without merging**
