### PR TITLE
Task 212-234 Phase 1

### PR DESCRIPTION
**Pull request by vijaykumawat256**

### CODE REVIEW

**Comment by Ravsehajsinghpuri** [comment]
@vijaykumawat256 1) Can you add the original tasks in this PR. 2) Can you rename the task variants as taskxxx.1_yyyy, taskxxx.2_yyyy, taskxxx.3_yyyy and so on. For e.g. task547.1_spl_translation_entk_en.json, task547.2_spl_translation_entk_en.json, task547.3_spl_translation_entk_en.json and so on. Do this for all the tasks in this PR
3) Can you pls resolve the conflict as well

**Comment by vijaykumawat256** [comment]
@Ravsehajsinghpuri  I have made changes as per the requirement. Please check and let me know if there is any issue.

**Comment by Ravsehajsinghpuri** [comment]
@vijaykumawat256 QQ - are these task variants different than the ones pushed in phase 2? If yes, can you rename the tasks in this PR as phase 2 tasks have been merged so there will be a conflict.

**Comment by vijaykumawat256** [comment]
Yes, these are different. But what is format for renaming ? Can I use 'Task123.a, Task123.b  at the place of Task123.1 Task123.2?

**Comment by vijaykumawat256** [comment]
> @Ravsehajsinghpuri   Yes, these are different. But what is format for renaming ? Can I use 'Task123.a, Task123.b at the place of Task123.1 Task123.2?

**Comment by Ravsehajsinghpuri** [comment]
> @Ravsehajsinghpuri Yes, these are different. But what is format for renaming ? Can I use 'Task123.a, Task123.b at the place of Task123.1 Task123.2?

No, use the same convention. If the last variant task was named task123.6, then rename the task in this PR as task123.7 and so on. Start from where the previous variant for the respective task ended

**Comment by vijaykumawat256** [comment]
@Ravsehajsinghpuri  I have made changes. Please check now.

**Comment by Ravsehajsinghpuri** [comment]
> @Ravsehajsinghpuri I have made changes. Please check now.

perfect, thanks! LGTM

**Pull request merged**
