### PR TITLE
Savan: Task 561 - 564: Wiki auto and winograd dataset

### PR DESCRIPTION
**Pull request by khushal1996**

### CODE REVIEW

**Comment by swarooprm** [comment]
@SavanDoshi, Wondering if you can help review these tasks?

**Comment by SavanDoshi** [comment]
**readme.md** : should be in the format of  Name | Summary | Category.
you need to update the readme according to it. ex: `task562_pronoun_finder` | find the pronoun in the sentence | Pronoun Finder 

- Check grammar for definitions and explanations for every task.
- There are many asci characters in the file. Use this command to generate json "json.dumps(your_json_string, indent=4, ensure_ascii=False))"
- in the explanations whenever you are referring to a particular word from the input sentence. put that word in the quote. ex:  in the first negative example "There is no his in the sentence" -> "There is no \"his\" in the sentence".
- change the explanations according to the above method.

**task561:**  
- Category should be "Summarization"  instead of "Title Generation". 
- Try to write definition clearly. ex: instead of using the word "passage" use "sentence" as there are no passage examples.

**task562:**
- Category should be "Answer Generation".
- write a clear and proper definition as if you are explaining to another person.

**task563:**
- Category should be "Answer Generation".
- explain the definition clearly like, what is quote in the sentence.

**task564:**
- Category should be "Answer Generation".

**Comment by khushal1996** [comment]
So do I create another pull request ? @SavanDoshi

**Comment by SavanDoshi** [comment]
> So do I create another pull request ? @SavanDoshi

No, update the files in this PR.

**Comment by khushal1996** [comment]
ohkay.. I will do that today.

**Comment by swarooprm** [comment]
@SavanDoshi, check and let me know if you are happy with the changes or have any other feedback?

**Comment by SavanDoshi** [comment]
@swarooprm looks good to me.

**Comment by swarooprm** [comment]
Your HW2 is complete now.

Would you like to submit the same tasks to our big project repo https://github.com/allenai/natural-instructions-expansion/pulls? You just need to fork that repo, rename tasks starting from the latest number in the repo and create PR there. This way, you can be part of our research on "learning from instructions instead of learning from examples (conventional machine learning)". This is purely optional and your HW2 grade does not depend on this @khushal1996

**Comment by khushal1996** [comment]
Hi @swarooprm Yeah sure. I have submitted the tasks to the repo you mentioned.

**Pull request closed without merging**
