### PR TITLE
Complete: Instruction Tasks 41-48 (PAWS-X and PEC)

### PR DESCRIPTION
**Pull request by jwande18**
I have created a total of 50 new instruction tasks that were generated from two datasets:

- [PAWS-X](https://huggingface.co/datasets/paws-x)
- [PEC](https://huggingface.co/datasets/pec)

Within the set of instruction tasks, they are organized into three unique tasks (41, 42, and 43) as well as variations of said tasks that include differing languages from the seven total supported languages.

If a fourth unique instruction is required per the homework requirements, please let me know.

### CODE REVIEW

**Comment by jwande18** [comment]
@swarooprm I have updated my instruction task with the following changes:

- For translation tasks, the fields `Input_language` and `Output_language` has been added
- For classification tasks, the definition is more explicit on the two types of classifications
- For all tasks, the explanations have been modified to use more natural language

Please let me know if this looks good. Thank you!

**Review by swarooprm — COMMENTED** [review]
Looks good. Your HW2 is complete now.

Since you have shown interest to be a co-author in our future paper, please submit the
same tasks to our big project repo https://github.com/allenai/natural-instructions-expansion/pulls? You just need to fork that repo, rename tasks starting from the latest number in the repo (which at this point is 591) and create PR there. This way, you can be part of our research on "learning from instructions instead of learning from examples (conventional machine learning)". This is optional and your HW2 grade does not depend on this @jwande18

**Comment by jwande18** [comment]
Perfect. Thank you!

I will be making the formal submission to the repository today. I see the deadline has been extended to October 15th, so that is good news! :tada:

**Comment by swarooprm** [comment]
@jwande18  Just wanted to update that, if you plan to submit these tasks to the main Github repo and join our research project, Monday (27th Sept) is the internal deadline. It should not take more than a couple of minutes to submit.

**Pull request closed without merging**
