### PR TITLE
Mihir: Tasks 97-101: OpenBookQA and CLUE datasets

### PR DESCRIPTION
**Pull request by ebell495**

### CODE REVIEW

**Comment by swarooprm** [comment]
@Mihir3009, wondering if you can review these?

**Comment by Mihir3009** [comment]
1. Update Readme summary like this:

Task 97: Given a fact, generate a question that can be answered using given the fact
Task 98: Given a fact and question, generate an answer to the question
Task 99: Given a fact and question, generate three incorrect answers to the question
Task 100: Given a question and answer, generate a fact statement
Task 101: Given a Chinese passage, generate a question based on the passage

Task 98:

1. Change definition like this:

`In this task, you are given a fact statement and question based on the fact. Your task is to generate the correct answer for the question. The answer needs to be generated using a context fact statement.`

Task 99:

Why three incorrect answers? Why not one at a time?

Task 100:

1. Change category to "Sentence Generation" (change file name accordingly)
2. Let's change the definition like this:

`In this task, you are given a question and a corresponding answer. Your task is to generate a fact statement that is useful in answering the given question.`

3. Add explanation in positive examples

Task 101:

1. While saving JSON file use this, this will save Chinese text:
`json.dumps(your_json_string, indent=4, ensure_ascii=False)`

2. Add language indicator to the schema:

"Input_language": language of the input/instructions
"Output_language": language of the responses/output
"instruction_language": ["en"]

We can specify these languages via their [two-digit ISO 639-1 code](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes).

3. Change definition:

`Given a passage in simplified Chinese, generate a reading comprehension question. The question should be unambiguous and the answer to this question should be in the passage.`

**Comment by swarooprm** [comment]
@ebell495, can you address reviewer comments so that I can grade your HW?

**Comment by ebell495** [comment]
I've pushed my changes to address their comments.

**Comment by Mihir3009** [comment]
@swarooprm I am happy with this PR. Looks good to me.

**Comment by swarooprm** [comment]
Your HW2 is complete now.

Would you like to submit the same tasks to our big project repo https://github.com/allenai/natural-instructions-expansion/pulls? You just need to fork that repo, rename tasks starting from the latest number in the repo and create PR there. This way, you can be part of our research on "learning from instructions instead of learning from examples (conventional machine learning)". This is purely optional and your HW2 grade does not depend on this @ebell495

**Comment by swarooprm** [comment]
@ebell495, Just a reminder that, if you plan to submit these tasks to the main Github repo and join our research project, Monday (27th Sept) is the deadline. Again, this is optional and independent of your HW2 grade.

**Pull request closed without merging**
