### PR TITLE
Task 144-166: Dataset 3, Phase 1

### PR DESCRIPTION
**Pull request by RushangKaria**
Variants are suffixed with "_v*" and each variant only changes the definition from the original (the original file is not included).

For the assigned 22 tasks, total variants created are 75 with (51/24) being (auto/manually) generated with at least 3 variants per task.
Automatic generation was using https://quillbot.com/.

### CODE REVIEW

**Comment by Ravsehajsinghpuri** [comment]
@RushangKaria 1) Can you add the original tasks in this PR. 2) Can you rename the task variants as taskxxx.1_yyyy, taskxxx.2_yyyy, taskxxx.3_yyyy and so on. (For e.g. task547.1_spl_translation_entk_en.json, task547.2_spl_translation_entk_en.json, task547.3_spl_translation_entk_en.json and so on). Do this for all the tasks in this PR 3) Can you resolve the conflicts

**Comment by RushangKaria** [comment]
@Ravsehajsinghpuri will do! thanks!

is there any deadline to this?

**Comment by Ravsehajsinghpuri** [comment]
> @Ravsehajsinghpuri will do! thanks!
> 
> is there any deadline to this?

Try to complete by Friday

**Comment by RushangKaria** [comment]
@Ravsehajsinghpuri done!

**Comment by Ravsehajsinghpuri** [comment]
@RushangKaria Can you resolve the conflicts?

**Comment by RushangKaria** [comment]
@Ravsehajsinghpuri  you can delete this PR. My phase2 is a superset of this PR (all changes in this PR already got merged in the PR for phase 2).

thanks!

**Pull request closed without merging**
