### PR TITLE
Shailaja: Tasks 257-260 craigslist_bargains, qed 

### PR DESCRIPTION
**Pull request by ritvik7**

### CODE REVIEW

**Comment by swarooprm** [comment]
@shailaja183, wondering if you can help review this PR?

**Comment by shailaja183** [comment]
for all tasks:
merge dataset and website into a single source -- "https://huggingface.co/datasets/craigslist_bargains Craigslist Bargains"

257:
- in beginning of the definition, specify that input will be a text passage and output is one of the labels "accepted"/"rejected", then provide more details about when to choose a particular label
- Select [accepted]/[rejected] if --> output "accepted"/"rejected" if 

258:
- clearly specify in the definition that output should be "a name of the category" (and not the numbering of the category) and there should be exactly one category for a given input

257/258:
- order of "inputs" and "outputs" are reversed in instances. It does not causes issues but you may fix it anyway.

259: 
- category of the task would be "text span selection" 
@swarooprm, please confirm
- add more description about how the answer should look like
does the phrases need to be continuous, does the phrases need to be minimal, how to answer if multiple phrases from different sentences have to be combined or any other things one should keep in mind while answering.
ex. in what scenario generate answers like [ "`` just now '' or `` now itself '' ( ab meaning now )" ] 
see example at https://github.com/allenai/natural-instructions-expansion/blob/master/tasks/task075_squad1.1_answer_generation.json
- Also I do not understand following, 
@swarooprm please share your thoughts 
in examples, when you say "Leo Varadkar , TD" that means both tokens must be used in the answer
whereas when you say ["Leo Varadkar , TD"] in instances, that means either of them are acceptable answers
(if both "Leo Varadkar" , "TD" are necessary for answer, simply concatenate before putting them into output of an instance like [ "Leo Varadkar , TD" ]
- In the instances, passages are missing in inputs

260:
- specify in the definition how long the title is supposed to be (typically x-y words)

**Comment by swarooprm** [comment]
> for all tasks:
> merge dataset and website into a single source -- "https://huggingface.co/datasets/craigslist_bargains Craigslist Bargains"
> 
> 257:
> 
> * in beginning of the definition, specify that input will be a text passage and output is one of the labels "accepted"/"rejected", then provide more details about when to choose a particular label
> * Select [accepted]/[rejected] if --> output "accepted"/"rejected" if
> 
> 258:
> 
> * clearly specify in the definition that output should be "a name of the category" (and not the numbering of the category) and there should be exactly one category for a given input
> 
> 257/258:
> 
> * order of "inputs" and "outputs" are reversed in instances. It does not causes issues but you may fix it anyway.
> 
> 259:
> 
> * category of the task would be "text span selection"
>   @swarooprm, please confirm
> * add more description about how the answer should look like
>   does the phrases need to be continuous, does the phrases need to be minimal, how to answer if multiple phrases from different sentences have to be combined or any other things one should keep in mind while answering.
>   ex. in what scenario generate answers like [ "`just now '' or` now itself '' ( ab meaning now )" ]
>   see example at https://github.com/allenai/natural-instructions-expansion/blob/master/tasks/task075_squad1.1_answer_generation.json
> * Also I do not understand following,
>   @swarooprm please share your thoughts
>   in examples, when you say "Leo Varadkar , TD" that means both tokens must be used in the answer
>   whereas when you say ["Leo Varadkar , TD"] in instances, that means either of them are acceptable answers
>   (if both "Leo Varadkar" , "TD" are necessary for answer, simply concatenate before putting them into output of an instance like [ "Leo Varadkar , TD" ]
> * In the instances, passages are missing in inputs
> 
> 260:
> 
> * specify in the definition how long the title is supposed to be (typically x-y words)
> 
> @ritvik, please address these comments and update the PR

@ritvik7, can you address reviewer comments so that I can evaluate your HW?

**Comment by ritvik7** [comment]
@swarooprm @shailaja183 I am making changes to my tasks to address the points you raised. I will update the PR today.

**Comment by ritvik7** [comment]
Apart from the ordering of input and output I have addressed all the points. For task 259 all the instances are such that the answer lies in only a single sentence, and that is mentioned in the description. I have now only chosen instances with one word answers and mentioned the same in the description. Please let me know if any further issues.

**Comment by shailaja183** [comment]
Final check- looks good to me!

**Comment by swarooprm** [comment]
Your HW2 is complete now.

Would you like to submit the same tasks to our big project repo https://github.com/allenai/natural-instructions-expansion/pulls? You just need to fork that repo, rename tasks starting from the latest number in the repo and create PR there. This way, you can be part of our research on "learning from instructions instead of learning from examples (conventional machine learning)". This is purely optional and your HW2 grade does not depend on this @ritvik7

**Comment by ritvik7** [comment]
I have created a PR to the allenai repo as well.

**Comment by ritvik7** [comment]
@swarooprm

**Comment by swarooprm** [comment]
Thanks!

**Pull request closed without merging**
