### PR TITLE
Dataset 3 phase 2 Task 75- 92

### PR DESCRIPTION
**Pull request by AnshitaSinghBais**

### CODE REVIEW

**Comment by Ravsehajsinghpuri** [comment]
@AnshitaSinghBais 1) Can you resolve the conflicts? 2) Can you add the original tasks in this PR. 3) Can you rename the task variants as taskxxx.1_yyyy, taskxxx.2_yyyy, taskxxx.3_yyyy and so on. For e.g. task547.1_spl_translation_entk_en.json, task547.2_spl_translation_entk_en.json, task547.3_spl_translation_entk_en.json and so on. Do this for all the tasks in this PR

**Comment by AnshitaSinghBais** [comment]
> @AnshitaSinghBais 1) Can you resolve the conflicts? 2) Can you add the original tasks in this PR. 3) Can you rename the task variants as taskxxx.1_yyyy, taskxxx.2_yyyy, taskxxx.3_yyyy and so on. For e.g. task547.1_spl_translation_entk_en.json, task547.2_spl_translation_entk_en.json, task547.3_spl_translation_entk_en.json and so on. Do this for all the tasks in this PR

Hi, I have made the asked changes except the 1st one. Could you please help me with the conflicts. I am unable to resolve them.
Thank you

**Comment by Ravsehajsinghpuri** [comment]
> > @AnshitaSinghBais 1) Can you resolve the conflicts? 2) Can you add the original tasks in this PR. 3) Can you rename the task variants as taskxxx.1_yyyy, taskxxx.2_yyyy, taskxxx.3_yyyy and so on. For e.g. task547.1_spl_translation_entk_en.json, task547.2_spl_translation_entk_en.json, task547.3_spl_translation_entk_en.json and so on. Do this for all the tasks in this PR
> 
> Hi, I have made the asked changes except the 1st one. Could you please help me with the conflicts. I am unable to resolve them. Thank you

Can you add the original tasks to the same folder as the variant tasks? All at one place

**Comment by Ravsehajsinghpuri** [comment]
@AnshitaSinghBais Can you check why the checks are failing and resolve it?

**Comment by Ravsehajsinghpuri** [comment]
@AnshitaSinghBais Can you raise this PR again? There were issues when I merged. So I have reverted the merge. Can you raise the PR for phase 2 again?

**Comment by AnshitaSinghBais** [comment]
Hello,
My checks are failing because of the original task 74. It is being
downloaded in the rtf format and saving it in the json format is changing
all its formatting which is causing the checks to fail. Should I remove the
original task 74 ?

**Comment by AnshitaSinghBais** [comment]
Hello,

I tried to create a new PR, but it says that there are no changes to
compare.
[image: image.png]

**Pull request merged**
