### PR TITLE
Anjana: Task 81-85: Clickbait_news_bg and TriviaQA datsets

### PR DESCRIPTION
**Pull request by amulyaarunb**

### CODE REVIEW

**Comment by swarooprm** [comment]
@aarunku5, wondering if you can help review this PR?

**Comment by aarunku5** [comment]
Make sure you update the readme file according to the comments given where necessary.
For augmenting the definitions for tasks 81-83, since it's a different language put it through translate in order to get the relevant details.
Also run the definition and explanations through Grammarly before resubmitting.

**81**
In the definition, modify to "In this task you are given a passage as the input content in the ___ language. You are expected to generate a suitable title for the passage." 

You also need to write another sentence about any constraints in the output. Like what constitutes the title? Is it words from the story or a generic title? How many words max? Check the sample tasks provided to you from squad. Modify your defnition to be specific about the details of input and output generated. Also make sure you write in complete sentences, with proper punctuation.

The same goes for your explanations- they need to be complete sentences, with proper grammar and punctuation. You also need to be able to say why they are correct/incorrect. Is the title not relevant? Does it contain no words from the passage? Those kinds of things.

**82**

Refer to comments on **81**'s definition. Define what a fake news score is, and how it is computed. Also the task category  is answer generation if you are calculating it and not selecting from provided options. Change that, change the task name, and update the readme file as well.  

If there is a method of picking particular words or sentences for the fake news score, you need to include that as part of the explanation to justify why the score is correct/incorrect.

**83**

Same comments about definition and explanation as 82. The category is again answer generation here.

**84**

Minor grammatical errors in definition. Also split the first sentence into two, it's not clear at first glance.
Put a comma between the question text's end and search result label for all examples and instances to make it more readable.

**85**

Make the category classification. Specify in the defn that they can choose a or b as the answer, and modify output to be a or b. 
Put a comma between question, options, search result in the input.

**Comment by swarooprm** [comment]
@amulyaarunb, can you address reviewer comments so that I can evaluate your HW?

**Comment by amulyaarunb** [comment]
@swarooprm, Can I get some time to address the comments by the reviewer? There are a lot of points mentioned, and it is taking a lot of time to address everything.

**Comment by amulyaarunb** [comment]
@aarunku5 I have made all the changes you have asked me to do, with respect to the review.

However, with respect to how the fake_news_score and click_bait_score are calculated, there is no information provided. I have read through the entire research paper associated with the article but they have not provided any details on how these values are calculated. In the paper, they used neural networks and different architectures to generate the scores for an unseen passage, based on a huge dataset of passages and corresponding scores.

All other changes have been made as per the comments provided

**Comment by aarunku5** [comment]
@swarooprm can you check tasks 82, 83? The rest look good.

**Comment by swarooprm** [comment]
Your HW2 is complete now.

Would you like to submit the same tasks to our big project repo https://github.com/allenai/natural-instructions-expansion/pulls? You just need to fork that repo, rename tasks starting from the latest number in the repo and create PR there. This way, you can be part of our research on "learning from instructions instead of learning from examples (conventional machine learning)". This is purely optional and your HW2 grade does not depend on this @amulyaarunb

**Comment by swarooprm** [comment]
@amulyaarunb Just a reminder that, if you plan to submit these tasks to the main Github repo and join our research project, Monday (27th Sept) is the deadline. Again, this is optional and independent of your HW2 grade.

**Pull request closed without merging**
