### PR TITLE
Swaroop: Tasks 161-168: ShreLIic, pib, Pracchathai67k

### PR DESCRIPTION
**Pull request by CodeHime**

### CODE REVIEW

**Comment by swarooprm** [comment]
@SavanDoshi, wondering if you can help review this PR?

**Comment by swarooprm** [comment]
@kuntalkumarpal, wondering if you can help review this PR?

**Comment by swarooprm** [comment]
Some general comments:

**Comment by CodeHime** [comment]
Got it. There was some typo in the code for the Definition, which I will update  the files for. The second point is also noted. For the third point, I am pretty sure I balanced all the classes for classification tasks. Could you point me to the file you are referring to?

**Comment by swarooprm** [comment]
> Got it. There was some typo in the code for the Definition, which I will update the files for. The second point is also noted. For the third point, I am pretty sure I balanced all the classes for classification tasks. Could you point me to the file you are referring to?

Please ignore the third point, if labels are already balanced.
Let me know once you do the two changes so that I can review again @CodeHime

**Comment by swarooprm** [comment]
> > Got it. There was some typo in the code for the Definition, which I will update the files for. The second point is also noted. For the third point, I am pretty sure I balanced all the classes for classification tasks. Could you point me to the file you are referring to?
> 
> Please ignore the third point, if labels are already balanced.
> Let me know once you do the two changes so that I can review again @CodeHime

Wondering if you addressed the comments and should I review them again? @CodeHime

**Comment by swarooprm** [comment]
@CodeHime, you have done an exceptional job. Your HW is complete now.
I strongly suggest you to submit the same tasks to our big project repo https://github.com/allenai/natural-instructions-expansion/pulls? You just need to fork that repo, rename tasks starting from the latest number in the repo and create PR there. This way, you can be part of our research on "learning from instructions instead of learning from examples (conventional machine learning)". Once your tasks get accepted in that repo, you will become a co-author in our future paper.

This is purely optional and your HW2 grade does not depend on this.

**Comment by swarooprm** [comment]
> > @CodeHime, you have done an exceptional job. Your HW is complete now. I strongly suggest you to submit the same tasks to our big project repo https://github.com/allenai/natural-instructions-expansion/pulls. You just need to fork that repo, rename tasks starting from the latest number in the repo and create PR there. This way, you can be part of our research on "learning from instructions instead of learning from examples (conventional machine learning)". Once your tasks get accepted in that repo, you will become a co-author in our future paper. If you decide to submit, please do it soon since the internal deadline to submit to that repo is already passed.
> > This is purely optional and your HW2 grade does not depend on this.
> 
> Thank you!
> 
> Sounds interesting, I will surely create a PR asap! Thank you for the suggestion!

Great! Looking forward.

**Comment by swarooprm** [comment]
> > > @CodeHime, you have done an exceptional job. Your HW is complete now. I strongly suggest you to submit the same tasks to our big project repo https://github.com/allenai/natural-instructions-expansion/pulls. You just need to fork that repo, rename tasks starting from the latest number in the repo and create PR there. This way, you can be part of our research on "learning from instructions instead of learning from examples (conventional machine learning)". Once your tasks get accepted in that repo, you will become a co-author in our future paper. If you decide to submit, please do it soon since the internal deadline to submit to that repo is already passed.
> > > This is purely optional and your HW2 grade does not depend on this.
> > 
> > 
> > Thank you!
> > Sounds interesting, I will surely create a PR asap! Thank you for the suggestion!
> 
> Great! Looking forward.

A Gentle Reminder @CodeHime !

**Pull request closed without merging**
