### PR TITLE
Shailaja: Task 33-37: CFD MCD1, MS MARCO datasets 

### PR DESCRIPTION
**Pull request by ujjwalaananth**
Tasks created for:
CFQ MCD1 (SQL queries and natural language description)
MS MARCO (QnA dataset)

### CODE REVIEW

**Comment by swarooprm** [comment]
@shailaja183, can you review this task?
We have some SQL related tasks e.g., make sure that definition etc. are not a copy from the existing tasks. We want diversity in language.

**Comment by shailaja183** [comment]
Make sure that your json is human readable (use proper indentation, e.g., in Python: json.dumps(<>,indent=4)).
Will review after the fix.

**Comment by ujjwalaananth** [comment]
Have indented. Kindly review and let me know if I should make any changes.

**Comment by ujjwalaananth** [comment]
Have indented. Kindly review and let me know if I should make any changes. @shailaja183

**Comment by shailaja183** [comment]
General comments for all tasks:
1. Put your tasks.json inside tasks/. You also need to define your tasks into Readme file inside tasks/.
2. "Positive Examples" and "Negative Examples" are empty in tasks 33, 34
3. delete repeated copies of tasks (there are two files for task 35, 36, 37)
4. Do not write generic explanations: "This answer is correct according to data from the passage" or "This answer is incorrect.". Explain in detail why an answer is correct or incorrect. 

Task 35:
1. all inputs are not formated correctly/have missing escape characters
2. Make definition more comprehensive. This statement is not clear "Answers may not be an exact statement from the passage" -- Rather, explain how should an answer look like? (a word, a phrase, a sentence?). There are many answer generation examples at https://github.com/allenai/natural-instructions-expansion/blob/master/tasks/. See them carefully and update your task definition accordingly.

Task 36:
1. In definition you have mentioned "Given a fact" -- make it "Given a passage". Also refer other reading comprehension tasks at https://github.com/allenai/natural-instructions-expansion/blob/master/tasks/ and improve definition. 

Task 37/38:
@swarooprm please review, I am not sure if these should be considered as tasks.
@ujjwalaananth From MS MARCO's website https://microsoft.github.io/msmarco/ -- The first dataset was a question answering dataset featuring 100,000 real Bing questions and a human generated answer. Since then we released a 1,000,000 question dataset, a natural langauge generation dataset, a passage ranking dataset, keyphrase extraction dataset, crawling dataset, and a conversational search. 
You can create many more interesting tasks using any of the datasets.

**Comment by ujjwalaananth** [comment]
4 tasks completed. Details in tasks/README.md

**Comment by swarooprm** [comment]
@shailaja183 , are you happy with the changes or have any other feedback?

**Comment by swarooprm** [comment]
I don't see tasks 37,38 to review.
@shailaja183, check if you are happy?

**Comment by swarooprm** [comment]
Your HW2 is complete now.

Would you like to submit the same tasks to our big project repo https://github.com/allenai/natural-instructions-expansion/pulls? You just need to fork that repo, rename tasks starting from the latest number in the repo and create PR there. This way, you can be part of our research on "learning from instructions instead of learning from examples (conventional machine learning)". This is purely optional and your HW2 grade does not depend on this @ujjwalaananth

**Comment by ujjwalaananth** [comment]
> Your HW2 is complete now.
> 
> Would you like to submit the same tasks to our big project repo https://github.com/allenai/natural-instructions-expansion/pulls? You just need to fork that repo, rename tasks starting from the latest number in the repo and create PR there. This way, you can be part of our research on "learning from instructions instead of learning from examples (conventional machine learning)". This is purely optional and your HW2 grade does not depend on this @ujjwalaananth

Sure, I'll do that. Thanks!

**Comment by swarooprm** [comment]
@ujjwalaananth  Just a reminder that, if you plan to submit these tasks to the main Github repo and join our research project, Monday (27th Sept) is the deadline. Again, this is optional and independent of your HW2 grade.

**Pull request closed without merging**
