### PR TITLE
Swaroop: Tasks313-316 DialogRE

### PR DESCRIPTION
**Pull request by matthew-huff**

### CODE REVIEW

**Comment by swarooprm** [comment]
@eshaanpathak, wondering if you can help review these tasks?

**Comment by eshaanpathak** [comment]
@swarooprm Yeah, I can review this. I'm guessing you made this research project an assignment for a class you're TAing for haha? Can you also update the `src/test_all.py` with the latest version that we have in the AI2 repo? Can you also enable it so it runs these checks in this repo too?

@matthew-huff Hey Matthew. Thanks for the submission!
1. In `tasks/README.md`, switch out the apostrophe (' character) with the grave accent (` character that is usually the same key as the ~ character on your keyboard). This way it will highlight and look nice in the markdown file in `tasks/README.md`.
2. In `tasks/README.md`, make sure all characters in the filename are lowercased and that the `.json` file extension ending is not present.
3. Instead of two spaces, you should have one space followed by a newline character before each speaker in the dialog. For example, "Speaker 1: Hello! \nSpeaker 2: Hi! \nSpeaker 1:". This will make each speaker be on a new line.
4. You should add a third positive example to your tasks.

Please let me know when you have made these changes and if you have any questions!

**Comment by matthew-huff** [comment]
@eshaanpathak Hi Eshaan, thanks for the pointers.  Hopefully these files are all fixed now!

**Comment by eshaanpathak** [comment]
1. Make sure to stay consistent throughout the examples on adding the space and new line characters. Some only have a new line or just a space still. 
2. Make sure there also new lines throughout the instances as well and not just in the examples.
3. I think the last task should be categorized as "Answer Generation".

**Comment by swarooprm** [comment]
@matthew-huff, can you address reviewer comments so that I can evaluate your HW?

**Comment by matthew-huff** [comment]
> @matthew-huff, can you address reviewer comments so that I can evaluate your HW?

Hi @swarooprm , I must've missed the additional notes from Eshaan. I'll fix those up and tag you in a comment here once I'm finished, thanks for the heads up!

**Comment by matthew-huff** [comment]
Hi @swarooprm , I fixed those newline errors and committed.  Thanks again.

**Comment by eshaanpathak** [comment]
For tasks 313 and 316, can you actually save the JSON file with an `indent=4` so it's easy to read? Like how you did for tasks 314 and 315.

Some more advice:

1. You don't need to add newline characters before the very first speaker in the dialog.
2. And make sure you add newline characters to your positive and negative examples too.

**Comment by eshaanpathak** [comment]
1. I think you may have missed adding newline characters to some of the speakers in the examples.
2. You also don't need to add two spaces before the newline character, just one space is fine.

**Comment by eshaanpathak** [comment]
One last thing: can you save your JSON files in utf-8 encoding? There are some examples and instances that have unicode encodings such as "\u2019" when they should be apostrophes, quotations, etc.

**Comment by swarooprm** [comment]
Your HW2 is complete (assuming that you fix the utf-8 encoding issue)

Would you like to submit the same tasks to our big project repo https://github.com/allenai/natural-instructions-expansion/pulls? You just need to fork that repo, rename tasks starting from the latest number in the repo and create PR there. This way, you can be part of our research on "learning from instructions instead of learning from examples (conventional machine learning)". This is purely optional and your HW2 grade does not depend on this @matthew-huff

**Comment by matthew-huff** [comment]
@swarooprm I just fixed that UTF-8 issue. Sure, I'll fork that repo and add the tasks there.

**Comment by swarooprm** [comment]
@matthew-huff, Just a reminder that, if you plan to submit these tasks to the main Github repo and join our research project, Monday (27th Sept) is the deadline. Again, this is optional and independent of your HW2 grade.

**Pull request closed without merging**
