### PR TITLE
Mirali: Tasks 417-424

### PR DESCRIPTION
**Pull request by krishna-8**

### CODE REVIEW

**Comment by swarooprm** [comment]
@Mirzyaaliii, wondering if you can help review these tasks?

**Comment by Mirzyaaliii** [comment]
- General Comments -
1. Include dataset link and paper (if there is any) in the source field, for reference check tasks 166 and 313 [here](https://github.com/allenai/natural-instructions-expansion/tree/master/tasks).
2. Correct grammar and typos in the definition and explanation from all the tasks (few suggestions are provided below also.).
3. Inside the file write the category which you wrote in the README for all the tasks.

- Task 417-419
1. Why there are special characters in place of the Yoruba language in the whole file? Files are not properly saved.
Write this while saving your JSON
`json.dumps(your_dict, ensure_ascii=False, indent=4)`
2. Check this link, and write 2 letter short-form of the language which is included in your tasks in the file name. For example,
`task417_menyo20k-mt_en_yo_translation`
where _en_yo_ indicates English to Yoruba.
3. Check tasks 312-315 [here](https://github.com/allenai/natural-instructions-expansion/tree/master/tasks) and change all things (filename, definition, summary in the README and add Input_language, Output_language, Instruction_language).

- Task - 421 & 422
1. Elaborate the definition.
2. Provide few examples that are fine but explain how that specific example is correct or incorrect in the positive and negative examples, respectively.

- Task - 423 & 424
1. Elaborate the definition.
2. Remove **\\"** from and include a separator between different elements of the input.
For example,
`original question: Who presented the mac to the Scottish Parliament when it was initially opened?, \n disfluent question: Who presented the mac is displayed in I mean to the Scottish Parliament when it was initially opened?, \n context: In front ....`
3. In the definition, explain why original and disfluent both questions are required.

**Comment by Mirzyaaliii** [comment]
- Task 417-419

1. In the definition, do following changes (For Task 517 & 418)

**i)** Mention input language in the definition, for example
`The input contains texts obtained from ... professional translators, and we ask you to translate those to the Yoruba language.`
change to
`The input contains texts obtained from ... professional translators in the English. Your task is to translate the given English sentence into the Yoruba language.`

**ii)** Instead of writing _we are_ in the definition write something like this
`We are looking for the most naturally written ...`
change to
`Generated output should be natural language and ...`
Apply this change in the whole definition

**iii)** In point (6), it is mentioned that 6) _Note the input is all lowercased except for special placeholders._ However, input is in the sentence case. (Correct it)

2. For Task 417, 418 and 419 
You can provide only 3 examples (or a few examples) in the positive and negative, but explain why it is correct (in positive) or why it is incorrect (in negative). For your reference, check tasks 424 and 425 [here](https://github.com/Mirzyaaliii/natural-instructions-expansion/tree/HindiEnglish_Corpora/tasks) and 2nd point [here](https://github.com/allenai/natural-instructions-expansion/pull/231#issuecomment-917717522).

- Also, do all other changes in the other tasks and once done drop a comment here.

**Comment by krishna-8** [comment]
Hi, I have made the changes according to the feedback please recheck and let me know. Thanks

**Comment by Mirzyaaliii** [comment]
- Complete each sentence by **.** in the explanation and definition. (Check this in all tasks)

- Change the name of these files
task421_disfl_qa_convert_disfluent_to_proper_question **->** task421_disfl_qa_text_modication
task422_disfl_qa_disfluent_question_prediction **->** task422_disfl_qa_disfluent_question_classification
task423_disfl_qa_answerable_quesion_prediction **->** task423_disfl_qa_question_yesno_classification
task424_disfl_qa_find_answer_to_question **->** task525_disfl_qa_asnwer_generation

- Change summary in the README
1. Task - 421: Given a disfluent question, convert it to a proper question.
2. Task - 422: Given a question, predict whether it is disfluent or not.
3. Task - 423: Given a context and a question, predict if a question is answerable or not based on the context.
4. Task - 424: Given a context and a question, return an answer to the question based on context.

- In the definition of Task 417 & 418
1. Include one more point that Numbers should not be converted in translation.
2. Instead of writing _we are_ in the definition write something like this
`We are looking for the most naturally written ...`
change to
`Generated output should be in natural language and ...`
Apply this change in the whole definition.

 - Task - 418
 1. From the explanation of the first negative example, 
 `"explanation": "The above sentence is not correctly translated from Yoruba to English as the word kọkàndínlógún is translated to the number 19 in English`
2. remove words of the Yoruba language and explain it using English only (as the instruction language is English only.)

- Task - 419
1. In the source field, do not write 2 elements
```
"Source": [
    "menyo20k-mt",
    "https://huggingface.co/datasets/menyo20k_mt"
  ],
```
write the dataset link in the bracket like this
"Source": [
    "menyo20k-mt (Dataset - https://huggingface.co/datasets/menyo20k_mt)"
  ],
2. You can provide only 3 examples (or a few examples) in the positive and negative, but explain why it is correct (in positive) or why it is incorrect (in negative). For your reference, check tasks 424 and 425 [here](https://github.com/Mirzyaaliii/natural-instructions-expansion/tree/HindiEnglish_Corpora/tasks) and 2nd point [here](https://github.com/allenai/natural-instructions-expansion/pull/231#issuecomment-917717522).

Task - 423
1. Remove curly brace inside the input
`
      "input": "{'original question': 'In what year did the U of C become one of 7 founding members of the Association of Chicago Universities?',\n'disfluent question': 'In what year did Robert Harper or did the U of C become one of 7 founding members of the Association of Chicago Universities?', \n 'context': 'Founded by the American Baptist Education Society with a donation from oil magnate and wealthiest man in history John D. Rockefeller, the University of Chicago was incorporated in 1890; William Rainey Harper became the university's first president in 1891, and the first classes were held in 1892. Both Harper and future president Robert Maynard Hutchins advocated for Chicago's curriculum to be based upon theoretical and perennial issues rather than on applied sciences and commercial utility. With Harper's vision in mind, the University of Chicago also became one of the 14 founding members of the Association of American Universities, an international organization of leading research universities, in 1900.\"}",
`
It should be just string. (Also, apply this to Task-424.)
2. Remove extra **\\** and **\***. (Also, apply this to Task-424.)

- Task - 424
1. Return output as **None**, if there is no answer. That makes more sense, compared to an empty string.
2. Remove special characters (i.e., \u2013, \u00f, etc.) from examples and instances.
3. From the instances, keep only 1 output where it is the same. For example
```
"output": [
        "May",
        "May",
        "May"
      ]
```

**Comment by krishna-8** [comment]
@Mirzyaaliii I tried removing the encodings in file 423 and 424 but couldn't do it. Could you please help me with these?

**Comment by Mirzyaaliii** [comment]
> @Mirzyaaliii I tried removing the encodings in file 423 and 424 but couldn't do it. Could you please help me with these?

Try to do as much as possible.

**Comment by swarooprm** [comment]
> @Mirzyaaliii I tried removing the encodings in file 423 and 424 but couldn't do it. Could you please help me with these?

Can you let me know what issue you are facing so that I can try to help?
Let @Mirzyaaliii know once you address all other comments so that she can check your files again and I can grade.

**Comment by krishna-8** [comment]
@swarooprm The files in task423 and 424 have some encodings and I am not able to change them, I tried various types of saving methods using encoding="utf-8","latin-1" but it is resulting in errors. There are about 3000 instances with such encodings and I am not able to manually remove each of them. Can you let me know how to proceed? I have done all the other changes suggested by @Mirzyaaliii please check.

**Comment by Mirzyaaliii** [comment]
Some changes are not done (which are addressed above), again pointing out below:

- There are few grammatical errors in the explanations. So, please once pass this on the Grammarly (or a similar tool). Hence, there will be no grammatical, punctuation, spacing, etc errors. (In all the tasks.)

- Why were tasks 421 and 422 removed?

- In the definition of Task 417 & 418
1. Include one more point that Numbers should not be converted in translation.
2. Instead of writing _we are_ in the definition write something like this
`We are looking for the most naturally written ...`
change to
`Generated output should be in natural language and ...`
Apply this change in the whole definition.
3. Also, the 5th point is missing or either there is a mistake in numbering.

- Task - 419
1. You can provide only 3 examples (or a few examples) in the positive and negative, but explain why it is correct (in positive) or why it is incorrect (in negative). For your reference, check tasks 424 and 425 [here](https://github.com/Mirzyaaliii/natural-instructions-expansion/tree/HindiEnglish_Corpora/tasks) and 2nd point [here](https://github.com/allenai/natural-instructions-expansion/pull/231#issuecomment-917717522).

- Task - 424
1. From the instances, keep only 1 output where it is the same. For example
```
"output": [
        "\"Southwest Fresno\"",
        "Southwest Fresno"
      ]
```
2. Return output as **None**, if there is no answer. That makes more sense, compared to an empty string.
3. Remove special characters (i.e., \u2013, \u00f, etc.) from examples and instances. (Apply this change to Task-423 also.)
4. It would be great if you can apply change as below:
`"input": "'original question': 'What act convened the old parliament of Scotland?',\n'disfluent question': 'What act convened the old government actually no parliament of Scotland?', \n 'context': 'Following a referendum in 1997, in which the Scottish electorate voted for devolution, the current Parliament was convened by the Scotland Act 1998, which sets out its powers as a devolved legislature. The Act delineates the legislative competence of the Parliament \\u2013 the areas in which it can make laws \\u2013 by explicitly specifying powers that are \\\"reserved\\\" to the Parliament of the United Kingdom. The Scottish Parliament has the power to legislate in all areas that are not explicitly reserved to Westminster. The British Parliament retains the ability to amend the terms of reference of the Scottish Parliament, and can extend or reduce the areas in which it can make laws. The first meeting of the new Parliament took place on 12 May 1999.\""`
As you can see there are extra **''** after and before the original question, disfluent question and context. remove it. Also, there are extra \\\\\\ and some special characters, remove it. (You can remove \\\\\\ just by using replace the function of the string.)
and change it to like this
`"input": "Original Question: What act convened the old parliament of Scotland? \n Disfluent Question: What act convened the old government actually no parliament of Scotland? \n Context: Following a referendum in 1997, in which the Scottish electorate voted for devolution, the current Parliament was convened by the Scotland Act 1998, which sets out its powers as a devolved legislature. The Act delineates the legislative competence of the Parliament the areas in which it can make laws by explicitly specifying powers that are "reserved" to the Parliament of the United Kingdom. The Scottish Parliament has the power to legislate in all areas that are not explicitly reserved to Westminster. The British Parliament retains the ability to amend the terms of reference of the Scottish Parliament, and can extend or reduce the areas in which it can make laws. The first meeting of the new Parliament took place on 12 May 1999."`

**Comment by Mirzyaaliii** [comment]
You did not apply many changes which I gave you almost 2-3 times. I am again pointing it below:

- There are few grammatical errors in the explanations. So, please once pass this on the Grammarly (or a similar tool). Hence, there will be no grammatical, punctuation, spacing, etc errors. (In all the tasks.)
For example, in the explanation of Task - 424
instead of this
```
The answer to the above question is not found from the context hence it is not answerable and the output is empty string
```
it should be like this
```
The answer to the above question is not found from the context hence it is not answerable and the output is an empty string.
```
Also, there are many mistakes in other tasks also, please check once (definition and explanation).

- In the definition of Task 417 & 418
1. Include one more point that Numbers should not be converted in translation. (If you did not mention it for purpose, point it out here in comment or if already added that in the definition, point out that also.)
2. Instead of writing _we are_ in the definition write something like this
`We are looking for the most naturally written ...`
change to
`Generated output should be in natural language and ...`
Apply this change in the whole definition.

- Task - 419
Shuffle the instances, hence all the English and Yoruba instances are not in sequence.

- Task - 421
1. Change the category inside the file.
2. In the explanation, explain why the input question is disfluent and output is the proper question.

- Task - 422
1.  In the instances, why there are all the examples of difluent only?
2. What is your task exactly,
classify the input into disfluent or not difluent
or
classify the input into disfluent or proper
Whatever task is from the above, add other positive examples which are not disfluent.

- Task - 424
1. Still, there are extra **'** in some inputs.
`"input": "original question: When did Augustus find Rome?',\ndisfluent question: When did Augustus find the upper Danube, no when did he find Rome?', \n context: From the death of Augustus in AD 14 until after AD 70, Rome accepted as her Germanic frontier the water-boundary of the Rhine and upper Danube. Beyond these rivers she held only the fertile plain of Frankfurt, opposite the Roman border fortress of Moguntiacum (Mainz), the southernmost slopes of the Black Forest and a few scattered bridge-heads. The northern section of this frontier, where the Rhine is deep and broad, remained the Roman boundary until the empire fell. The southern part was different. The upper Rhine and upper Danube are easily crossed. The frontier which they form is inconveniently long, enclosing an acute-angled wedge of foreign territory between the modern Baden and Württemberg. The Germanic populations of these lands seem in Roman times to have been scanty, and Roman subjects from the modern Alsace-Lorraine had drifted across the river eastwards."`
From the above example,
-> Remove **'** after Rome? in the original question, disfluent question.
-> Remove **,** after Original Question and Disfluent Question end. 
-> Keep space before **\n**, you kept it somewhere and somewhere not. (Apply this change to Task-423 also.)
Make the whole input like below:
`"input": "Original Question: When did Augustus find Rome? \n Disfluent Question: When did Augustus find the upper Danube, no when did he find Rome? \n Context: From the death of Augustus in AD 14 until after AD 70, Rome accepted as her Germanic frontier the water-boundary of the Rhine and upper Danube. Beyond these rivers she held only the fertile plain of Frankfurt, opposite the Roman border fortress of Moguntiacum (Mainz), the southernmost slopes of the Black Forest and a few scattered bridge-heads. The northern section of this frontier, where the Rhine is deep and broad, remained the Roman boundary until the empire fell. The southern part was different. The upper Rhine and upper Danube are easily crossed. The frontier which they form is inconveniently long, enclosing an acute-angled wedge of foreign territory between the modern Baden and Württemberg. The Germanic populations of these lands seem in Roman times to have been scanty, and Roman subjects from the modern Alsace-Lorraine had drifted across the river eastwards."`
2. Change the definition, according to the task, you need to change the below line:
'''
return an empty tuple if an answer can't be found
'''
3. Also, mention why disfluent and original questions are needed or I think only original question is fine.

- **Once you are done applying all the changes, drop a comment here and if you have any suggestions or doubts on any comment mention here.**

**Comment by krishna-8** [comment]
@Mirzyaaliii I am still working on the changes. I am pushing them one by one I will make a comment once I am done.

**Comment by swarooprm** [comment]
> @Mirzyaaliii I am still working on the changes. I am pushing them one by one I will make a comment once I am done.

@krishna-8,  Can you address the reviewer comments soon so that I can evaluate your HW?

**Comment by krishna-8** [comment]
Sorry I was caught up with other deadlines. I will complete and recheck every task and let you know by EOD tomorrow.

**Comment by krishna-8** [comment]
@Mirzyaaliii Sorry for the trouble. I have made changes based on above feedback. Please review it. For task 423 - 424, I agree that only the one of the questions is enough to find the output. I have changed the definition to "use a disfluent question or a proper question to find the output" If you think it is better to remove one of these from input let me know and I will make the changes.

**Comment by swarooprm** [comment]
> @Mirzyaaliii Sorry for the trouble. I have made changes based on above feedback. Please review it. For task 423 - 424, I agree that only the one of the questions is enough to find the output. I have changed the definition to "use a disfluent question or a proper question to find the output" If you think it is better to remove one of these from input let me know and I will make the changes.

@Mirzyaaliii, check if you are happy or have any other feedback?

**Comment by Mirzyaaliii** [comment]
Just a few minor changes -
- In Task - 417, change the definition as below:
```
In this task, you are given a sentence in the English language from the various articles. Your task is to translate the given English sentence into the Yoruba language. Please bear in mind the following guidelines while doing the translation: 1) Generated output should have natural language and formal form. The output sentence should not be a colloquial form of the input sentence. The generated output should be in natural language which is how you would type your queries in a text-based virtual assistant. 2) The words between quotation marks *SHOULD NOT* be translated. The output should keep those values intact and include the quotation marks around them as well. 3) Numbers and fully capitalized words like SEPTEMBER, or 10 HOURS *SHOULD NOT* be translated. Keep them as they are in the translations. 4) Do not localize measurement units like miles to kilometers during your translation. 5) Note the input is in sentence case except for special placeholders. Do the same in your translations.
```
Apply this change to Task - 418 accordingly.
- In Task - 424, remove **'** after every difluent question. For example, there is **'** after rather in the below instance. 
```
... disfluent question: When did the name black death officially take root in Scandinavia no sorry England rather' \n context: ...
```

Apart from this, all things look good to me.

**Comment by swarooprm** [comment]
> Just a few minor changes -
> 
> * In Task - 417, change the definition as below:
> 
> ```
> In this task, you are given a sentence in the English language from the various articles. Your task is to translate the given English sentence into the Yoruba language. Please bear in mind the following guidelines while doing the translation: 1) Generated output should have natural language and formal form. The output sentence should not be a colloquial form of the input sentence. The generated output should be in natural language which is how you would type your queries in a text-based virtual assistant. 2) The words between quotation marks *SHOULD NOT* be translated. The output should keep those values intact and include the quotation marks around them as well. 3) Numbers and fully capitalized words like SEPTEMBER, or 10 HOURS *SHOULD NOT* be translated. Keep them as they are in the translations. 4) Do not localize measurement units like miles to kilometers during your translation. 5) Note the input is in sentence case except for special placeholders. Do the same in your translations.
> ```
> 
> Apply this change to Task - 418 accordingly.
> 
> * In Task - 424, remove **'** after every difluent question. For example, there is **'** after rather in the below instance.
> 
> ```
> ... disfluent question: When did the name black death officially take root in Scandinavia no sorry England rather' \n context: ...
> ```
> 
> Apart from this, all things look good to me.

Let me know once you do these changes so that I can evaluate your HW?

**Comment by krishna-8** [comment]
@swarooprm The changes are done.

**Comment by swarooprm** [comment]
@krishna-8, looks good, one issue:
Instead of saying "This task is...", directly instruct by saying "Answer"/ "Generate" etc.... Imagine how you will you instruct your friend to do this task, that will be your definition.
Finally, check grammatical errors and typos in definitions via Grammarly.
Your HW will be complete as soon as you do these changes.

**Comment by swarooprm** [comment]
Your HW2 is complete now.

Would you like to submit the same tasks to our big project repo https://github.com/allenai/natural-instructions-expansion/pulls? You just need to fork that repo, rename tasks starting from the latest number in the repo and create PR there. This way, you can be part of our research on "learning from instructions instead of learning from examples (conventional machine learning)". This is purely optional and your HW2 grade does not depend on this @krishna-8

**Comment by swarooprm** [comment]
@krishna-8, Just a reminder that, if you plan to submit these tasks to the main Github repo and join our research project, Monday (27th Sept) is the deadline. Again, this is optional and independent of your HW2 grade.

**Pull request closed without merging**
