### PR TITLE
Mirali: Task265-269-SMCalFlow-WebQuestion

### PR DESCRIPTION
**Pull request by parilghori**

### CODE REVIEW

**Comment by swarooprm** [comment]
@Mirzyaaliii, wondering if you can help review this PR?

**Comment by Mirzyaaliii** [comment]
- General comments -
1. Make all filenames in lowercase
2. Correct the README file, copy from master and then modify according to your tasks
3. In the source field, instead of dataset line write dataset link or only dataset. For example, check Task-300 [here](https://github.com/allenai/natural-instructions-expansion/tree/master/tasks).
4. In the category, write only _Classification_ instead of _Utterance Classification_ or _Agent Utterance Classification_. Change it in the README and inside the JSON file.
5. Elaborate the definition. Read few definitions from [here](https://github.com/allenai/natural-instructions-expansion/tree/master/tasks).
For example, in Task-265, you can provide criteria based on which utterance will be classified into Agent or User.
6. Correct grammar and typos from the definition and explanations.
7. Task-267 is not clear. Is this open-domain question-answering? or answer is available in the input URL?

**Comment by swarooprm** [comment]
@parilghori, can you address reviewer comments so that I can evaluate your HW?

**Comment by parilghori** [comment]
> @parilghori, can you address reviewer comments so that I can evaluate your HW?

@swarooprm Sorry for the delay, I will do it in 30 minutes.

**Comment by Mirzyaaliii** [comment]
Some of the above changes are not done, pointing out again below:

- **Correct the README file**, copy from master and then modify according to your tasks.
- In the category, write only _Classification_ instead of _Utterance Classification_ or _Agent Utterance Classification_. Change it in the README and inside the JSON file.
- In the README, elaborate the summary. For your reference, read a few summaries from [here](https://github.com/allenai/natural-instructions-expansion/tree/master/tasks).
- There are few grammatical errors in the explanations and definition. So, please once pass this on the Grammarly (or a similar tool). Hence, there will be no typos, grammatical, punctuation, spacing, etc errors.
- Write a source like this
```
"Source": [
    "SMCalFlow (Dataset - https://www.mitpressjournals.org/doi/pdf/10.1162/tacl_a_00333)"
  ]
```
- @swarooprm Can you please look at Tasks **267** & **268** and confirm whether this kind of task is valid or not?

**Comment by swarooprm** [comment]
> Some of the above changes are not done, pointing out again below:
> 
> * **Correct the README file**, copy from master and then modify according to your tasks.
> * In the category, write only _Classification_ instead of _Utterance Classification_ or _Agent Utterance Classification_. Change it in the README and inside the JSON file.
> * In the README, elaborate the summary. For your reference, read a few summaries from [here](https://github.com/allenai/natural-instructions-expansion/tree/master/tasks).
> * There are few grammatical errors in the explanations and definition. So, please once pass this on the Grammarly (or a similar tool). Hence, there will be no typos, grammatical, punctuation, spacing, etc errors.
> * Write a source like this
> 
> ```
> "Source": [
>     "SMCalFlow (Dataset - https://www.mitpressjournals.org/doi/pdf/10.1162/tacl_a_00333)"
>   ]
> ```
> 
> * In Task - 265, remove 1) and 2), it is not needed.
> * @swarooprm Can you please look at Tasks **267** & **268** and confirm whether this kind of task is valid or not?

@parilghori , can you address reviewer comments so that I can evaluate your HW?

**Comment by parilghori** [comment]
> > Some of the above changes are not done, pointing out again below:
> > 
> > * **Correct the README file**, copy from master and then modify according to your tasks.
> > * In the category, write only _Classification_ instead of _Utterance Classification_ or _Agent Utterance Classification_. Change it in the README and inside the JSON file.
> > * In the README, elaborate the summary. For your reference, read a few summaries from [here](https://github.com/allenai/natural-instructions-expansion/tree/master/tasks).
> > * There are few grammatical errors in the explanations and definition. So, please once pass this on the Grammarly (or a similar tool). Hence, there will be no typos, grammatical, punctuation, spacing, etc errors.
> > * Write a source like this
> > 
> > ```
> > "Source": [
> >     "SMCalFlow (Dataset - https://www.mitpressjournals.org/doi/pdf/10.1162/tacl_a_00333)"
> >   ]
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * In Task - 265, remove 1) and 2), it is not needed.
> > * @swarooprm Can you please look at Tasks **267** & **268** and confirm whether this kind of task is valid or not?
> 
> @parilghori , can you address reviewer comments so that I can evaluate your HW?

@swarooprm I have done the changes as per the comments. c

**Comment by Mirzyaaliii** [comment]
- In Task 266 and 269, change the category from _Utterance Generation_ to _Sentence Generation_.
- For each task write the category inside the JSON file, whatever is there in the README.
- In the definition of Task - 269,
change this

> ... question, based on that you have to **identify** what will be Agent's **utterance** ...

to

> ... question, based on that you have to **return** what will be Agent's **response/reply** ...

@parilghori Once you complete all the changes, drop a comment here and if you have any suggestions or doubts on any comment mention here.

**Comment by parilghori** [comment]
> * In Task 266 and 269, change the category from _Utterance Generation_ to _Sentence Generation_.
> * For each task write the category inside the JSON file, whatever is there in the README.
> * In the definition of Task - 269,
>   change this
> 
> > ... question, based on that you have to **identify** what will be Agent's **utterance** ...
> 
> to
> 
> > ... question, based on that you have to **return** what will be Agent's **response/reply** ...
> 
> @parilghori Once you complete all the changes, drop a comment here and if you have any suggestions or doubts on any comment mention here.

@swarooprm @Mirzyaaliii Thank you for your review. I have done the changes as per instructions.

**Comment by swarooprm** [comment]
Your HW2 is complete now.

Would you like to submit the same tasks to our big project repo https://github.com/allenai/natural-instructions-expansion/pulls? You just need to fork that repo, rename tasks starting from the latest number in the repo and create PR there. This way, you can be part of our research on "learning from instructions instead of learning from examples (conventional machine learning)". This is purely optional and your HW2 grade does not depend on this @parilghori

**Comment by swarooprm** [comment]
@parilghori, Just a reminder that, if you plan to submit these tasks to the main Github repo and join our research project, Monday (27th Sept) is the deadline. Again, this is optional and independent of your HW2 grade.

**Comment by parilghori** [comment]
> @parilghori, Just a reminder that, if you plan to submit these tasks to the main Github repo and join our research project, Monday (27th Sept) is the deadline. Again, this is optional and independent of your HW2 grade.

@swarooprm I will do it by today.

**Pull request closed without merging**
