### PR TITLE
Neeraj: Task 233-238: SCDE, opus_montenegrinsubs, cornell_movie_dialog

### PR DESCRIPTION
**Pull request by harshilgandhi3199**

### CODE REVIEW

**Comment by swarooprm** [comment]
@shailaja183, wondering if you can help review this PR?

**Comment by swarooprm** [comment]
@nrjvarshney, wondering if you can help review this PR since Shailaja already is handling a lot of PRs?

**Comment by nrjvarshney** [comment]
Task 233-236: 
* I like the task
* You can give the index for the candidates also. Start index from 1 instead of 0.
* Also, try to make the definition a bit concise. 


Task 237;
* In the examples, illustrate this "The fully capitalized words like DATE and TIME should not be translated. Please keep them as they appear in the input sentence."

Task 238 
* This is not a good task.
* This expects knowledge of the movie.

**Comment by harshilgandhi3199** [comment]
@swarooprm @nrjvarshney 

For tasks 233-236:
- I have changed the definition such that it is more concise now.
- For the suggestion "you can give the index for the candidates also. Start index from 1 instead of 0." do you mean that I should create a new task?

For task 237:
- I have changed the definition slightly and included a negative example for the same.

For task 238:
- Is there something I can do here so that task can be made better?

Please let me know about these things. I will make a new commit with all the changes.

**Comment by nrjvarshney** [comment]
237 -
* Include a positive example also

233- 236
* No, not a new task but make changes in the existing tasks. 
* In the output you have "[1, 0, 3, 2, 5]" how would someone what does 1 stand for.

You can drop 238

**Comment by harshilgandhi3199** [comment]
If you will see, I have mentioned in the definition how to interpret the results. 

For example, in task 233
Definition: "The sequence of numbers in output indicates the sequence of the items in the \"candidates\" list that will be the answer for the blanks in order of the blank number. For example, the output [2, 3] means that candidate item at the position 2 will be the answer for the blank 1 and candidate item at the position 3 will be the answer for the blank 2"

**Comment by swarooprm** [comment]
Your HW2 is complete now.

Would you like to submit the same tasks to our big project repo https://github.com/allenai/natural-instructions-expansion/pulls? You just need to fork that repo, rename tasks starting from the latest number in the repo and create PR there. This way, you can be part of our research on "learning from instructions instead of learning from examples (conventional machine learning)". This is purely optional and your HW2 grade does not depend on this @harshilgandhi3199

**Comment by swarooprm** [comment]
@harshilgandhi3199  Just a reminder that, if you plan to submit these tasks to the main Github repo and join our research project, Monday (27th Sept) is the deadline. Again, this is optional and independent of your HW2 grade.

**Pull request closed without merging**
