### PR TITLE
Swaroop: Task 905-910: SQAC, peixian/equity_evaluation_corpus

### PR DESCRIPTION
**Pull request by sraakesh95github**
Created one of the tasks for the dataset 1 correspnoding to the SPAC spanish corpus. The task is a answer generation task

### CODE REVIEW

**Review by swarooprm — COMMENTED** [review]
@sraakesh95github, as mentioned during the call today,
1. Simplify definitions, write more detailed explanations, rename PR and create all tasks in a single PR.

Let me know once you are done and I will then review it.

**Comment by sraakesh95github** [comment]
> 
> 
> @sraakesh95github, as mentioned during the call today,
> 
>     1. Simplify definitions, write more detailed explanations, rename PR and create all tasks in a single PR.
> 
> 
> Let me know once you are done and I will then review it.

Hi Swaroop, please find the modified tasks (2 each) for the datasets provided. Thanks

**Comment by swarooprm** [comment]
1. Task905: Some typos and grammatical errors. "Input is CONTENT and a QUESTION in SPANISH language. The goal is to generate answers that are atleast THREE (3) words long.\nThings to note: A) The asnwers NEED TO BE context specific and cannot be general knowledge or a random guess \n Caution: A) Do not accept context shorter than 3 words"-->"Input is a CONTEXT and a QUESTION in SPANISH language. You need to generate an answer which is at least THREE (3) words long.\nThings to note: A) Your answer has to be from the given context. \n Caution: A) Make sure that your answer has more than 3 words."
2. Task906: "Based on a given content in SPANISH and an answer phrase in SPANISH, generate questions that point to the answer.\n Suggestion: The question may involve starting question words like WHERE, WHEN, HOW, WHAT (in Spanish).\nThings to note: A) The questions NEED to comply with the context specified in the input B) The questions NEED to be paraphrased from the context specified \n Caution: A) The question can be 7 to 30 words."-->"Based on the given context, generate a question which can be answered by the given answer. Generate a question that has more than 7 words. You can paraphrase the given context while forming the question." Also, verfiy if at least 7 words are present in all question.
3. Task907: You can improve definition based on my suggestion in above tasks, but I don't understand how can gender be determined based on a sentence. We know many names are used in both genders. Same in task 908: Identifying race from the sentence etc. is not very reliable. You can submit these tasks after minor modification in defintion, but I am not sure whether they will be accepted in your HW.  To be on the safer side, I suggest to create a 5th task, where given a sentence as input, model need to detect emotion as output. Also, think of creating a 6th task based on the information available to you in either of the datasets.

Also, add dataset url along with its name in the source field.
You should be able to fix my suggestions quickly. let me know once you are done @sraakesh95github

**Comment by sraakesh95github** [comment]
> 
> 
>     1. Task905: Some typos and grammatical errors. "Input is CONTENT and a QUESTION in SPANISH language. The goal is to generate answers that are atleast THREE (3) words long.\nThings to note: A) The asnwers NEED TO BE context specific and cannot be general knowledge or a random guess \n Caution: A) Do not accept context shorter than 3 words"-->"Input is a CONTEXT and a QUESTION in SPANISH language. You need to generate an answer which is at least THREE (3) words long.\nThings to note: A) Your answer has to be from the given context. \n Caution: A) Make sure that your answer has more than 3 words."
> 
>     2. Task906: "Based on a given content in SPANISH and an answer phrase in SPANISH, generate questions that point to the answer.\n Suggestion: The question may involve starting question words like WHERE, WHEN, HOW, WHAT (in Spanish).\nThings to note: A) The questions NEED to comply with the context specified in the input B) The questions NEED to be paraphrased from the context specified \n Caution: A) The question can be 7 to 30 words."-->"Based on the given context, generate a question which can be answered by the given answer. Generate a question that has more than 7 words. You can paraphrase the given context while forming the question." Also, verfiy if at least 7 words are present in all question.
> 
>     3. Task907: You can improve definition based on my suggestion in above tasks, but I don't understand how can gender be determined based on a sentence. We know many names are used in both genders. Same in task 908: Identifying race from the sentence etc. is not very reliable. You can submit these two tasks (907 and 908) after minor modification in defintion, but I am not sure whether they will be accepted in your HW.  To be on the safer side, I suggest to create a 5th task, where given a sentence as input, model need to generate emotion as output. Also, think of creating a 6th task based on the information available to you in either of the datasets.
> 
> 
> Also, add dataset url along with its name in the source field.
> You should be able to fix my suggestions quickly. let me know once you are done @sraakesh95github



> 
> 
>     1. Task905: Some typos and grammatical errors. "Input is CONTENT and a QUESTION in SPANISH language. The goal is to generate answers that are atleast THREE (3) words long.\nThings to note: A) The asnwers NEED TO BE context specific and cannot be general knowledge or a random guess \n Caution: A) Do not accept context shorter than 3 words"-->"Input is a CONTEXT and a QUESTION in SPANISH language. You need to generate an answer which is at least THREE (3) words long.\nThings to note: A) Your answer has to be from the given context. \n Caution: A) Make sure that your answer has more than 3 words."
> 
>     2. Task906: "Based on a given content in SPANISH and an answer phrase in SPANISH, generate questions that point to the answer.\n Suggestion: The question may involve starting question words like WHERE, WHEN, HOW, WHAT (in Spanish).\nThings to note: A) The questions NEED to comply with the context specified in the input B) The questions NEED to be paraphrased from the context specified \n Caution: A) The question can be 7 to 30 words."-->"Based on the given context, generate a question which can be answered by the given answer. Generate a question that has more than 7 words. You can paraphrase the given context while forming the question." Also, verfiy if at least 7 words are present in all question.
> 
>     3. Task907: You can improve definition based on my suggestion in above tasks, but I don't understand how can gender be determined based on a sentence. We know many names are used in both genders. Same in task 908: Identifying race from the sentence etc. is not very reliable. You can submit these two tasks (907 and 908) after minor modification in defintion, but I am not sure whether they will be accepted in your HW.  To be on the safer side, I suggest to create a 5th task, where given a sentence as input, model need to generate emotion as output. Also, think of creating a 6th task based on the information available to you in either of the datasets.
> 
> 
> Also, add dataset url along with its name in the source field.
> You should be able to fix my suggestions quickly. let me know once you are done @sraakesh95github

1. Changed description for task 905 accordingly without grammatical errors or typos
2. Verified that atleast 6 words are present in the questions and stated in the description
3. Created 2 tasks from the "peixian_equity_evaluation" datasets to compensate, in case task 907 and task 908 doesn't work out.
4. Added URLs in the Source field of the JSON

**Review by swarooprm — COMMENTED** [review]
1. Task906- Have a look at my earlier comment, definition needs to be changed.
2. Task 909- Make sure that there is a space after ending of a sentence (e.g. there is no space before the 2nd sentence starts). Also, only the first letter needs to be capitalized. "The emotion mainly depends on the ADVERB within the sentence like Anxious which falls under Fear."-->"The emotion mainly depends on the ADVERB within the sentence like 'anxious' which falls under 'fear'."
3. Task 910-Instances are incorrect. There is \<blank\> in output & both the input and output are same.

**Comment by swarooprm** [comment]
@sraakesh95github, can you address my comments so that I can evaluate your HW?

**Comment by sraakesh95github** [comment]
Please find the updated JSON files

**Comment by swarooprm** [comment]
My task 910 comments are yet to be addressed. 

> Task 910-Instances are incorrect. There is \<blank\> in output & both the input and output are same.

Outputs should not contain \<blank\> in the instances.

**Comment by sraakesh95github** [comment]
I have updated now. Apologize for the inconvenience.

**Comment by swarooprm** [comment]
Your HW2 is complete now.

Would you like to submit the same tasks to our big project repo https://github.com/allenai/natural-instructions-expansion/pulls? You just need to fork that repo, rename tasks starting from the latest number in the repo and create PR there. This way, you can be part of our research on "learning from instructions instead of learning from examples (conventional machine learning)". This is purely optional and your HW2 grade does not depend on this @sraakesh95github

**Comment by swarooprm** [comment]
@sraakesh95github Just a reminder that, if you plan to submit these tasks to the main Github repo and join our research project, Monday (27th Sept) is the deadline. Again, this is optional and independent of your HW2 grade.

**Comment by sraakesh95github** [comment]
> 
> 
> @sraakesh95github Just a reminder that, if you plan to submit these tasks to the main Github repo and join our research project, Monday (27th Sept) is the deadline. Again, this is optional and independent of your HW2 grade.

Thank you for providing information regarding the opportunity. I may not be interested in joining the research project at the moment.

**Pull request closed without merging**
