### PR TITLE
Task 625-629: giga_fren, poem_sentiment and poleval2019_mt datasets

### PR DESCRIPTION
**Pull request by abhinawale12**

### CODE REVIEW

**Comment by swarooprm** [comment]
@nrjvarshney, wondering if you can review these tasks?

**Comment by nrjvarshney** [comment]
Task 625 and 626-
* You can simplify the definition: "In this task, you need to translate the given English sentence to the French language".
* Try to elaborate on the explanations. I understand that input-output is evident here but see if you can elaborate.

Task 627 and 628 -
* The examples do not follow the task definition.
* Will review it after you update the examples.
* Keep the label text consistent. You have used "no" and "No" both. 
* Need to improve the explanation - "Polish sentence is properly converted to English sentence but the output is no. The ouput should be yes." --> "Polish sentence is properly converted to English sentence. So, the output should have been 'yes' instead of 'no'."

Task 629 - 
* Can simplify the definition: "In this task, you need to identify the sentiment of the given sentence as one of 'positive' or 'negative'". Add details if need be.

**Comment by abhinawale12** [comment]
@nrjvarshney I have made changes as you requested. But I don't know how to elaborate on positive example explanation in the Translation task.

**Comment by nrjvarshney** [comment]
Task 625 and 626 - 
* Change the explanation of negative : "The conversion.... difference" to "The correct translation of the input to French is .... However, the given output misses ...."
* In the explanations, write the expected output also. Just saying that the output is wrong is not enough.

Task 627 and 628-
* Simplify the task definition - "In this task, you...." to "In this task, you are given a sentence in English language and its corresponding French translation. Here, your job is to output \"yes\" if the translation is correct, otherwise output \"no\"."
* Same comment about explanation

**Comment by abhinawale12** [comment]
@nrjvarshney, I have made the changes. Please have a look at it. Thank you.

**Comment by swarooprm** [comment]
@nrjvarshney, are you happy with the PR or have any other feedback?

**Comment by nrjvarshney** [comment]
@swarooprm , All my comments have been addressed.

**Comment by swarooprm** [comment]
Great, your HW2 is complete now.
Would you like to submit the same tasks to our big project repo https://github.com/allenai/natural-instructions-expansion/pulls? You just need to fork that repo, rename tasks starting from the latest number in the repo (which at this point is 517) and create PR there. This way, you can be part of our research on "learning from instructions instead of learning from examples (conventional machine learning)". This is purely optional and your HW2 grade does not depend on this @abhinawale12

**Comment by swarooprm** [comment]
@abhinawale12  Just a reminder that, if you plan to submit these tasks to the main Github repo and join our research project, Monday (27th Sept) is the deadline. Again, this is optional and independent of your HW2 grade.

**Pull request closed without merging**
