### PR TITLE
Shailaja: Task 529-532: meta_woz, europa_ecdc_tm dataset

### PR DESCRIPTION
**Pull request by RexMao**

### CODE REVIEW

**Comment by swarooprm** [comment]
@shailaja183, wondering if you can help review these tasks?

**Comment by shailaja183** [comment]
task529:
language fixes - "we can know" -> "we know", "the answer gives us" -> "answer/output is", "so this is a wrong example" -> "incorrect", "the answer should be wrong." -> "the answer is wrong/incorrect.", "so this is a negative example" -> "so the answer xyz is incorrect"

task530/531/532
1. Please make Definition a bit more detailed on what aspects of translation should be taken care of (upper/lowercase, numbers, proper nouns, punctuations etc.). See https://github.com/allenai/natural-instructions-expansion/blob/master/tasks/  tasks 250-253 for example.
2. For Positive/Negative Examples, write detailed justification about what aspect of translation is correct/incorrect.  See https://github.com/allenai/natural-instructions-expansion/blob/master/tasks/  tasks 250-253 for example.
3. language fixes in definition - "given sentences" -> "a given sentence"

You already have translation tasks from language x -> y; If you can just swap inputs and outputs, and do minor changes in definition to create tasks for y -> x translation, we would appreciate it :-) 
However, this is optional and does not affect your grades for this assignment. You can add these tasks even after the assignment deadline. If you create 25 tasks in total, you can be a co-author in Swaroop's upcoming paper.

**Comment by RexMao** [comment]
Hi @shailaja183, I have addressed all the comments. Please let me know if you have any other issues.

**Comment by shailaja183** [comment]
529 - good to go

530-532:
Seems like you have entirely copy pasted task description from the reference translation task I suggested. Try to write in your own words.

Remove descriptions that are not related to your dataset "We are looking for formal form which is how you would type your queries in a text-based virtual assistant.". and "Please do not localize measurement units like miles to kilometers during your translation. miles should be translated to its equivalent in your language". 

https://huggingface.co/datasets/europa_ecdc_tm says that your dataset "contains text about health-related topics" so add constraints that are relevant to the domain of your dataset.

**Comment by swarooprm** [comment]
@RexMao, can you address reviewer comments so that I can grade your HW?

**Comment by RexMao** [comment]
@swarooprm @shailaja183 I have addressed the comments.

**Comment by shailaja183** [comment]
530-532: description could be more detailed @swarooprm have a look once.
In negative examples explanation, specify why the translation is incorrect and hence a bad bad sample

Looks good otherwise.

**Comment by swarooprm** [comment]
Your HW2 is complete now.

Would you like to submit the same tasks to our big project repo https://github.com/allenai/natural-instructions-expansion/pulls? You just need to fork that repo, rename tasks starting from the latest number in the repo and create PR there. This way, you can be part of our research on "learning from instructions instead of learning from examples (conventional machine learning)". This is purely optional and your HW2 grade does not depend on this @RexMao

**Comment by swarooprm** [comment]
@RexMao, Just a reminder that, if you plan to submit these tasks to the main Github repo and join our research project, Monday (27th Sept) is the deadline. Again, this is optional and independent of your HW2 grade.

**Pull request closed without merging**
