### PR TITLE
Amir: Task 882,885,887,888:  lhoestq Dataset

### PR DESCRIPTION
**Pull request by hanut1909**

### CODE REVIEW

**Comment by swarooprm** [comment]
@amirrezamirzaei, wondering if you can help review this PR?

**Comment by amirrezamirzaei** [comment]
Hi @hanut1909 , some minor comments
- why have you removed tasks 1001-1002?
- please fix the numbering of the tasks. you have uploaded four tasks but the pr name is `881-888`.
- don't use `Emphasis & Caution` and `Things to avoid` format in the task definitions. express the contents of these two-part naturally.
- capitalize the explanations in the examples.
- please provide a link to the paper or dataset in the source field (e.g `lhoestq (link)`)
- for consistency reasons with our other task please dont use the dataset name in the definition of the readMe file. also its better if the tone of the definition is imperative for examples see [here](https://github.com/allenai/natural-instructions-expansion/tree/master/tasks).
- task 882: `DO NOT` should be `do not`.
- task 885 : change the category to `Answer Generation`.remove `This is the correct answer` and `This is not the correct answer` from the examples. please use the same format for the task definition (`In this task your Given, ....`
- task 887 : change the category to `Answer Generation`. same comment as before about the definition format
- task 888: same comment about the definition. also please fix the source and contributor field here.
- also please use `json.dumps(your_json_string, indent=4, ensure_ascii=False)` to make your file and dont edit the file yourself.

**Comment by hanut1909** [comment]
okk...will do it asap. sorry for the delay.

**Comment by hanut1909** [comment]
[image: Screen Shot 2021-09-22 at 5.57.21 PM.png]
Hi Swaroop, I don't know why I am getting this error for the question
generation task.
Why is a key required even for the question generation task?
I had submitted the tasks before without any errors but now I keep on
getting these errors.
Please look into it and let me know how to correct it.

Thank you.

**Comment by swarooprm** [comment]
Make the key "Explanation"-->"explanation". This should resolve the issue.

**Comment by hanut1909** [comment]
Done. Thanks for the clarification.

**Comment by swarooprm** [comment]
Your HW2 is complete now.

Would you like to submit the same tasks to our big project repo https://github.com/allenai/natural-instructions-expansion/pulls? You just need to fork that repo, rename tasks starting from the latest number in the repo and create PR there. This way, you can be part of our research on "learning from instructions instead of learning from examples (conventional machine learning)". This is purely optional and your HW2 grade does not depend on this @hanut1909

**Comment by hanut1909** [comment]
Hi Swaroop,
Yes, I would like to submit the tasks created to the project repository.
I will do the necessary steps by today.
If anything else is needed, please let me know.

**Pull request closed without merging**
