### PR TITLE
Complete: task 553-556 Wiqa dataset

### PR DESCRIPTION
**Pull request by hmazboud**
Hadi Mazboudi, CSE576, 1214483530

### CODE REVIEW

**Comment by swarooprm** [comment]
@Maitreyapatel, wondering if you can help review this PR?

**Comment by swarooprm** [comment]
Your HW2 is complete.

Would you like to submit the same tasks to our big project repo https://github.com/allenai/natural-instructions-expansion/pulls? You just need to fork that repo, rename tasks starting from the latest number in the repo and create PR there. This way, you can be part of our research on "learning from instructions instead of learning from examples (conventional machine learning)". This is purely optional and your HW2 grade does not depend on this @hmazboud ?

**Comment by hmazboud** [comment]
Yes!! I would like to submit it. Also to get a coauthor credit, what is the deadline?

**Comment by swarooprm** [comment]
Great. All tasks have to be accepted by Oct 15 to get coauthor credit.

**Comment by swarooprm** [comment]
@hmazboud, Just a reminder that, if you plan to submit these tasks to the main Github repo and join our research project, Monday (27th Sept) is the deadline. Again, this is optional and independent of your HW2 grade.

**Pull request closed without merging**
