### PR TITLE
Swaroop: Task 889-896: BSC-TeMU/ancora-ca-ner, librispeech_asr

### PR DESCRIPTION
**Pull request by ssingulu**

### CODE REVIEW

**Comment by swarooprm** [comment]
@Palipoor, wondering if you can help review these tasks?

**Comment by ssingulu** [comment]
Hi, If possible, please change the definition of task889_ancora-ca-ner_named_entity_recognition.json to this: 'This task is about doing Named Entity Recognition(NER) for every token in a sentence. The first step is to construct a Catalan sentence. Then split the sentence into single words or punctuation symbols. For each word, you need to assign an IOB tag. IOB tag consists of two parts separated by ‘-’ or a single part depending on whether the word belongs to a chunk or not. If the word doesn’t belong to any chunk, you will assign an ‘O’ tag to that particular word. But if it belongs to a chunk, you will assign a two-part tag like this: The I- prefix before a tag indicates that the tag is inside a chunk. The B- prefix before a tag indicates that the tag is the beginning of a chunk that immediately follows another chunk without O tags between them. It is used only in that case: when a chunk comes after an O tag, the first token of the chunk takes the I- prefix. So, if a token does belong to a chunk, you need to asign 'LOC' or 'ORG' or 'PER' tag as the second-part of the tag where 'LOC' indicates the token belongs to a location chunk, 'ORG' indicates the token belongs to a organization name chunk, 'PER' indicates the token belongs to a person name chunk, and 'MISC' indicates the token belongs to chunk which is not a person, location or an organization. Avoid using words from other languages.'


Previously, I forgot to eplain the second-part of the tag.

**Comment by Palipoor** [comment]
Hi, 
In file ` task889_ancora-ca-ner_named_entity_recognition.json` : 
1. what do you mean by this sentence in the definition? `The first step is to construct a Catalan sentence`
2. Can you provide a definition of "chunk" in the description? 
In file `task1001_squad1.1_question_generation.json`:
1. Please change `reading the given passage and construct a question` to `reading the given passage and constructing a question`. Also please change `(ii) uses same words` to `(ii) use the same words`. 
2. In negative examples please change ` its answer is not a shortest continuous text span from the paragraph` to `it can not be answered with a short continuous text span from the paragraph`.
There're some similar typos (with extra -s at the end of plural verbs, etc. in other files, please re-read all the definitions and explanations! thanks.
Also, please change the "Contributors" field to be a list in all files.
In file `task890_ancora-ca-ner_text_auto_completion.json`
1. I think by this sentence ` we need to come up with a Catalan sentence with more than two words. Then we will split the sentence somewhere in the middle, making sure that the left and right parts have at least one word. So, here given the left part, we need to predict the right part of the sentence.` you mean: `you are given an unfinished Catalan sentence and you need to predict the rest of it.` Creating the original sentence and splitting it in half is not part of the task.  
2. The first negative example doesn't really make sense, as the input is never English, and the task doer is not responsible for the inputs!
3. Please merge the outputs of instances into one string, inside a list, instead of separate tokens. 

Are the tasks 891 and 892 even valid? @swarooprm  Can you check these two?

In file `task893_librispeech_asr_next_word_prediction.json`:
1. Please remove `Make sure the input and output are not empty, and both should be in capital letters.`. The task doesn't include giving the input, only generating the output. Also please remove negative examples that are about the input being invalid.
2. Is it necessary for the data to be all capital?

**Comment by ssingulu** [comment]
Hi,
In file task889_ancora-ca-ner_named_entity_recognition.json :

what do you mean by this sentence in the definition? The first step is to construct a Catalan sentence - I assumed that the user needs to come up with a sentence. I'll modify this.
Can you provide a definition of "chunk" in the description? - Yes.

In file task1001_squad1.1_question_generation.json: - Sorry, this is not my dataset. Tasks for Squad1.1 dataset are already present in the repo when I forked them.
Please change reading the given passage and construct a question to reading the given passage and constructing a question. Also please change (ii) uses same words to (ii) use the same words.
In negative examples please change its answer is not a shortest continuous text span from the paragraph to it can not be answered with a short continuous text span from the paragraph.
There're some similar typos (with extra -s at the end of plural verbs, etc. in other files, please re-read all the definitions and explanations! thanks.
Also, please change the "Contributors" field to be a list in all files. - Ok

In file task890_ancora-ca-ner_text_auto_completion.json
I think by this sentence we need to come up with a Catalan sentence with more than two words. Then we will split the sentence somewhere in the middle, making sure that the left and right parts have at least one word. So, here given the left part, we need to predict the right part of the sentence. you mean: you are given an unfinished Catalan sentence and you need to predict the rest of it. Creating the original sentence and splitting it in half is not part of the task. - Yes, I'll modify this.
The first negative example doesn't really make sense, as the input is never English, and the task doer is not responsible for the inputs! - Ok, I'll edit this.
Please merge the outputs of instances into one string, inside a list, instead of separate tokens. - Ok

Are the tasks 891 and 892 even valid? @swarooprm Can you check these two? - Please, @swarooprm let me know.

In file task893_librispeech_asr_next_word_prediction.json:

Please remove Make sure the input and output are not empty, and both should be in capital letters.. The task doesn't include giving the input, only generating the output.  - Given a partial English sentence, task doer needs to predict the next word. This is my task.
Also please remove negative examples that are about the input being invalid. - Yes
Is it necessary for the data to be all capital?- No, I'll remove it.

**Comment by ssingulu** [comment]
@Palipoor, I had addressed all the above comments in my recent commit.
I had also added one new task for BSC-TeMU/ancora-ca-ner dataset. I have also added two new tasks for the librispeech_asr dataset since I don't know whether tasks 891 and 892 are valid or not. 
Thanks for the clear and precise comments and the guidance.

**Comment by Palipoor** [comment]
Thanks!

**Comment by Palipoor** [comment]
Please make all input and outputs normally cased. 
I am still in doubt about the tasks containing voice files.

**Comment by ssingulu** [comment]
@Palipoor,
I had made the suggested changes in the most recent commit could you please check.
Yes, I also have the same doubt, @swarooprm please advise.
 Thank you in advance.

**Comment by Palipoor** [comment]
Thanks!

**Comment by swarooprm** [comment]
@ssingulu, tasks containing audio files are not allowed, since we only accept text input and text output. So, remove the 2 tasks that contain audio files.
Identifying missing words, text autocompletion, next word prediction are not unique tasks because they can be applied to any task.
Task 889: In instances field, output should be ["o-o-b..] and not the way it is right now ["o","o"...]
Please fix task889, remove tasks with audio file and create 1-2 new tasks since you don't have a lot of new tasks.
Let me know once you are done so that I can evaluate your HW.

**Comment by ssingulu** [comment]
Hi @swarooprm,
As you had suggested I had updated task 889, deleted tasks that relied on audio files and created 2 new tasks using the new Rulemaker dataset. Please evaluate them.
Thanks for your patience and guidance.

**Comment by swarooprm** [comment]
looks good, some comments:
-Given a text paragraph and a fact, you need to mark it as True or False based on the given Paragraph. If the Fact can't be marked True or False from the given paragraph, mark it as False. Please don't use general knowledge or knowledge which can be inferred outside of given paragraph to check the fact",--->'Given a text paragraph and a fact, generate 'True' if the fact can be inferred from the paragraph, otherwise generate 'False'. If the Fact can't be marked True or False from the given paragraph, mark it as False. Don't use knowledge outside the given paragraph to check the fact.
-Given a text paragraph and a question, you need to generate an incorrect fact from the given paragraph. Please don't use general knowledge or knowledge which can be inferred outside of given paragraph to generate the incorrect fact"--->Given a text paragraph and a fact, generate an incorrect fact based on the given paragraph. Don't use knowledge outside the given paragraph to generate the incorrect fact.

In classification tasks, ensure that labels of all classes are balanced in your instances.

Once you do the above changes, your HW will be complete.

**Comment by ssingulu** [comment]
Hi @swarooprm ,
As suggested I had updated descriptions for tasks 895 and 896. I also made sure that the labels are balanced for classifications tasks. Please evaluate them.

**Comment by swarooprm** [comment]
Your HW2 is complete now.

Would you like to submit the same tasks to our big project repo https://github.com/allenai/natural-instructions-expansion/pulls? You just need to fork that repo, rename tasks starting from the latest number in the repo and create PR there. This way, you can be part of our research on "learning from instructions instead of learning from examples (conventional machine learning)". This is purely optional and your HW2 grade does not depend on this @ssingulu

**Comment by ssingulu** [comment]
@swarooprm Absolutely, I would submit my tasks to the AllenAI repo.

**Pull request closed without merging**
