### PR TITLE
Tasks 465:469: Translation, Primary Subject Recognition, Classification, Emotive Sequence Detection

### PR DESCRIPTION
**Pull request by aklagoo**

### CODE REVIEW

**Comment by swarooprm** [comment]
@amirrezamirzaei, wondering if you can help review these tasks?

**Comment by aklagoo** [comment]
@swarooprm Could you tell me if I need to make a new pull request for new tasks 468-469 or if this is fine?

**Comment by amirrezamirzaei** [comment]
please change the pr name to task 465:469

**Comment by amirrezamirzaei** [comment]
task 467 is not human readable please use `json.dumps(your_json_string, indent=4, ensure_ascii=False))` to make the file

**Comment by aklagoo** [comment]
Please let me know if this is fine

**Comment by amirrezamirzaei** [comment]
thanks for the changes. the tasks look good to me just a few minor comments
1 - can you change the tone of the definition in the readMe file to be imperative for example `Translating sentences in English to Xhosa` could be `Translate a sentence in English to Xhosa`.
2- in tasks 465-466 the definition could be something like `In this task, you are given a sentence or phrase in (Language). you must translate them to (Language) in a way…`
3-task 467 looks good but the definition could be better something like
`in this task, you are given a sentence or sub-sentence. you must find the primary subject ....`
4-in task 468 please make sure the classification labels are balanced. also the definition could be something like `In this task, you are given a sentence containing a particular emotion. You must classify the emotion into one of the following classes (1) joy ….`
5- in task 469 it's better if the input arent JSON encoded. you can express the inputs like this `sentence\nlabel` . also the outputs for this task don't need to be lists.

**Comment by aklagoo** [comment]
I have made the changes. Please let me know if that works

**Comment by amirrezamirzaei** [comment]
thanks for the changes. a few minor comments

- please add these field (Input_language" , "Output_language", "instruction_language") to the translation tasks. see this [task](https://raw.githubusercontent.com/allenai/natural-instructions-expansion/master/tasks/task272_europarl_translation.json) as an example. also please put an `.` at the end of your sentence in explanation of the examples.
- please provide a link to the paper or dataset in the source field.(e.g `dataset name ("link to paper")`
- task 465: change `khosa` to `Xhosa` in the second positive example.
- task 466: change `khosa` to `Xhosa` in the file name and readMe file.
- task 467: in the definition `The input is a sentence or a sub-sentence` isn't really needed because you specify the input in `in this task your given ...`. also in the second positive example please change `Howver ` to `However`.
- task 468: please remove the long space in the second negative example. also in the first positive example please change ``the word 'nostalgic' could either indicate 'love' or 'sadness'`` to `the word \"nostalgic\" could either indicate love or sadness`
- task 469: please fix the problem I pointed out in the previous comment. also the definition contains some grammatical errors.

**Comment by aklagoo** [comment]
I made all the changes. As for task 469, the output needs to be a list since there are multiple phrases for some sentences that can contribute to the sentence together.

**Comment by amirrezamirzaei** [comment]
yes I understand but the output tag is a list itself so you don't need to make your list into a string and then save it. please look at this [task](https://raw.githubusercontent.com/allenai/natural-instructions-expansion/master/tasks/task001_quoref_question_generation.json) as an example.

**Comment by aklagoo** [comment]
I understand that example, but the task here is a little different in my opinion.
In Question Generation, for a passage P, you need to generate one out of several valid questions, resulting in **multiple pairs** such as P-Q1, P-Q2, P-Q3, ...
In this task however, for every sentence P, you must generate multiple subsequences Q1, Q2, Q3, .... This results in **a single pair** P-[Q1, Q2, Q3, ...].

**Comment by amirrezamirzaei** [comment]
yes your right but still let's not use the list as string format. Why don't we just separate the outputs with a comma. please also specify the output format in the definition.

**Comment by amirrezamirzaei** [comment]
- task 465-466 looks good
- task 467:
1.  please change the definition in the ReadMe file from ` Recognize primary subjects in sentences` to ` Recognize the primary subject in a sentence`.
2. in the second positive example change `However, the since all others` to `However, since all others`.
3. explicitly say what the primary subject is in the negative example explanation.
- task 468:
1. please change `The input sentence is a string while the output sentence is a string representing a single emotion from sadness, joy, love, anger, fear, and surprise.` into something like `the output should be a string representing a single emotion from sadness, joy, love, anger, fear, and surprise.`
2. in the second positive example change `\"nostalgic\" could either mean` to `\"nostalgic\" could either indicate`.
3. remove `due the reason behind finding meaning` from the second negative example explanation. it makes the sentence grammatically incorrect.
- task 469:
1. please refer to the comment before this.

also please provide a link to the paper or dataset in the source field.(e.g dataset name ("link to paper")

**Comment by aklagoo** [comment]
Please let me know if this is correct

**Comment by amirrezamirzaei** [comment]
thank you, one final comment about task 468:
1. you have misspelled `senntence ` in the definition.
2. change `\"nostalgic\" could indicate either ` to `\"nostalgic\" could either indicate `

**Comment by aklagoo** [comment]
Done 👍

**Comment by amirrezamirzaei** [comment]
@swarooprm looks good to me.

**Comment by swarooprm** [comment]
Your HW2 is complete and you did a great job!
Would you like to submit the same tasks to our big project repo https://github.com/allenai/natural-instructions-expansion/pulls? You just need to fork that repo, rename tasks starting from the latest number in the repo (which at this point is 442) and create PR there. This way, you can be part of our research on "learning from instructions instead of learning from examples (conventional machine learning)". This is purely optional and your HW2 grade does not depend on this @aklagoo ?

**Comment by aklagoo** [comment]
Sure! I'll go ahead and do that tomorrow!

**Comment by swarooprm** [comment]
@aklagoo Just a reminder that, if you plan to submit these tasks to the main Github repo and join our research project, Monday (27th Sept) is the deadline. Again, this is optional and independent of your HW2 grade.

**Comment by aklagoo** [comment]
Hi! I'm sorry about the delay. Could you tell me which task numbers are available? @swarooprm

**Comment by swarooprm** [comment]
The latest task number in the PR is 867, so you can start from 868 (this might change when you submit, make sure to get the latest task numbers from the latest PR in the Allen AI Repo)

**Pull request closed without merging**
