### PR TITLE
Phase2 387 to 427

### PR DESCRIPTION
**Pull request by ZoroKiran**
Please check 4 tasks from 873 to 876.

### CODE REVIEW

**Comment by swarooprm** [comment]
@Palipoor, wondering if you can help review this PR?

**Comment by Palipoor** [comment]
Hi, sorry I had a busy weekend and couldn't respond sooner. 

1. Please update the readme file with task names and change the files' names(they can't be all the same). Also, all your tasks should be in the `tasks/ `directory.
2. For task 873, please provide a minimum length for summary (as in one of the negative examples you're stating that it's too short)
3. You don't need to bring the whole example output in the explanation. It suffices to just explain why the output is correct/incorrect.
4. For contributors and categories, please use a list (like "Contributors" : ["Your name"])
6. The description of task 875 contains some grammatical issues, please re-read it.
7. In task 875, please change the category to "Classification"
8. Task 876 has an extra { before positive examples. 
9. This sentence in task description (876) doesn't make sense" ` The input is a not a question statement`. Also, I think the description is not enough. Please write it again and try to make it easily understandable.

**Comment by ZoroKiran** [comment]
> Hi, sorry I had a busy weekend and couldn't respond sooner.
> 
> 1. Please update the readme file with task names and change the files' names(they can't be all the same). Also, all your tasks should be in the `tasks/ `directory.
> 2. For task 873, please provide a minimum length for summary (as in one of the negative examples you're stating that it's too short)
> 3. You don't need to bring the whole example output in the explanation. It suffices to just explain why the output is correct/incorrect.
> 4. For contributors and categories, please use a list (like "Contributors" : ["Your name"])
> 5. The description of task 875 contains some grammatical issues, please re-read it.
> 6. In task 875, please change the category to "Classification"
> 7. Task 876 has an extra { before positive examples.
> 8. This sentence in task description (876) doesn't make sense" ` The input is a not a question statement`. Also, I think the description is not enough. Please write it again and try to make it easily understandable.

Hi, I'll try to update by 22 Sept, 11:50pm. Thanks for the review.

**Comment by swarooprm** [comment]
@ZoroKiran, can you fix test failures?

**Comment by ZoroKiran** [comment]
> @ZoroKiran, can you fix test failures?

I have updated the readme.md file for the test failure. Can you please check again.

**Comment by ZoroKiran** [comment]
> @ZoroKiran, can you fix test failures?

json.decoder.JSONDecodeError: Expecting ',' delimiter: line 1648 column 4 (char 941431)

I have fixed the following dataset error. Please run test again.

**Comment by ZoroKiran** [comment]
> @ZoroKiran, can you fix test failures?

I have applied the dataset error fixes. Can you review again.

Capture

**Comment by swarooprm** [comment]
@Palipoor, check if you are happy or have any other feedback?

**Comment by Palipoor** [comment]
Hi again, Can you please rename the tasks? For example: `task874_newsroom_title_generation` , `task875_newsroom_classification` ..
Also, please re-word the definition for task 875.
I feel like in task 876 there's no need to have "Did" in all of the inputs.

**Comment by ZoroKiran** [comment]
> Hi again, Can you please rename the tasks? For example: `task874_newsroom_title_generation` , `task875_newsroom_classification` ..
> Also, please re-word the definition for task 875.
> I feel like in task 876 there's no need to have "Did" in all of the inputs.
1. Updated the file name as per the example given.
2. Definition of task875 changed. I have taken words from the research paper. The summaries are generated based on various nn models for each category of the summary. Hence if I have to add any model detail, it would make the definition more technical than a definition. Please advise if I need to change anything further.
3. Removed the "Did" from all the inputs.

**Comment by swarooprm** [comment]
Looks good to me.

One last change- Instead of saying "the task is to", say "you need to" (Think how you will instruct your friend to do this task).

Once you do this change, your HW will be complete. @ZoroKiran

**Comment by ZoroKiran** [comment]
> Looks good to me.
> 
> One last change- Instead of saying "the task is to", say "you need to" (Think how you will instruct your friend to do this task).
> 
> Once you do this change, your HW will be complete. @ZoroKiran

I have updated as per the recommendation in the task definition of all 4 files.

**Comment by swarooprm** [comment]
Looks good. Just that there are some grammatical mistakes you would like to fix. Just pass it over Grammerly for your defintion.
You need to writing--> You need to write.

This should complete your HW.

**Pull request merged**
