### PR TITLE
Swaroop: Tasks 753-758:  Opus100, HindEnCorp and Sent_Comp

### PR DESCRIPTION
**Pull request by arpit3956**
Adding 4 translation tasks. I had 2 dataset and both contained translation tasks on 1 sentence. I have created 4 tasks Hindi-English, English-Hindi, Gujarati-English, English-Gujarati.

Student ID: 1219477402
Name: Arpit Prajapati

### CODE REVIEW

**Comment by swarooprm** [comment]
Note that, just creating translations tasks won't be enough, as discussed in office hour. Make sure to create some other tasks along with the tasks you have already created.

**Comment by swarooprm** [comment]
@shailaja183, Wondering if you can review this?

**Comment by arpit3956** [comment]
@swarooprm 
1. I can make task like if the statement is question or not.
Please suggest some more tasks as my dataset only has pair of sentences with one sentence in English and other in some language. Or add more dataset having more than pair of sentenses.

**Comment by swarooprm** [comment]
@arpit3956 , I understand your concern. I have added one more dataset. Hope it helps.

**Comment by shailaja183** [comment]
General comments for Definition:
1. "The provided file includes english sentences" -- change to "You are given a sentence in English Language ..."
2. Keep the definition formal, do not use "Please bear in mind .." etc. Just say "Make sure .."/"Consider following guidelines"
3. Do not simply copy paste instructions from the crowd-sourcing template. 
ex. "We are looking for the most naturally written and formal form of each sentence in your language.", similarly no need of adding things like "text-based virtual assistant"
4. Simplify them and write in minimalistic language. 
ex. "Note the input can be lowercased or upercased. Please do the same in your translations." 
More importantly, Instructions related to Case-sensitivity does not make sense as Gujarati/Hindi does not have it.
5. Avoid repeated instructions 
ex. "formal form" is mentioned more than once 
 
General comments for Examples:
1. highlight important words in explanation with ' ' (ex. missing 'package', 'tranditional', 'remote machines' etc.)

task753:
definition - typo "english", "guidlines", "upercased"
positive example 5 explanation- typo "formal and accuracy"
negative example 2 explanation- typo "transaltion", "tranditional"
negative example 3 explanation- typo "ommited"
negative example 5 output missing some escape character
negative example 4 explanation- typo "fro" 
negative example 5 explanation- typo "statment"
simplify negative example 5 explanation - "Last statment is not part of the input. The output is incorrect for input as it contains extra sentence."

FIX ALL THE TYPOS, GRAMMATICAL ERROS, PUNCTUATIONS AND ARTICLES. 
I have only reviewed task 753 for now. I will review remaining tasks after you commit again with all fixes mentioned above.

**Comment by arpit3956** [comment]
Hi @shailaja183,
I have followed all of the instructions you have given in the comment above. Please review this whenever possible and suggest the changes if required.

**Comment by swarooprm** [comment]
@shailaja183, let me know if you are happy or have any other feedback?

**Comment by swarooprm** [comment]
task 757, maker sure labels are balanced in classification task

Leaving for @shailaja183 to have a look and let me know if she is happy or have any other feedback

**Comment by arpit3956** [comment]
@swarooprm  Thank you very much for pointing out class imbalance. I have updated the files.

@shailaja183 Please take a look at the tasks whenever possible.

**Comment by swarooprm** [comment]
Looks good to me.
Just shuffle the instances (now first half has label 'matched' and second half has label 'no') and your HW2 will be complete.

**Comment by arpit3956** [comment]
@swarooprm  I have shuffled the instances. Please check whenever you can.

I hope this is last change.

**Comment by swarooprm** [comment]
Great! Your HW2 is complete now.

Would you like to submit the same tasks to our big project repo https://github.com/allenai/natural-instructions-expansion/pulls? You just need to fork that repo, rename tasks starting from the latest number in the repo and create PR there. This way, you can be part of our research on "learning from instructions instead of learning from examples (conventional machine learning)". This is purely optional and your HW2 grade does not depend on this @arpit3956

**Comment by swarooprm** [comment]
@arpit3956  Just a reminder that, if you plan to submit these tasks to the main Github repo and join our research project, Monday (27th Sept) is the deadline. Again, this is optional and independent of your HW2 grade.

**Pull request closed without merging**
