### PR TITLE
Mehrad: Task 537-540: NYC, event2Mind

### PR DESCRIPTION
**Pull request by abmasud1214**

### CODE REVIEW

**Comment by swarooprm** [comment]
@Mehrad0711, wondering if you can help review this PR?

**Comment by Mehrad0711** [comment]
1. In "tasks/README.md" I suggest updating the definitions to be something like: `Creating text (emotional state) based on event2Mind event prompts` and `Creating text (intent) based on event2Mind event prompts` for generation tasks 1 and 2.
2. I suggest using `Slot Filling` as task category for "tasks/task539_NYC_answer_generation.json"
3. I noticed some non-readable characters in examples. For example: `rating[average], price[less than \u00c2\u00a320], cuisine[Japanese]` in "task539_NYC_answer_generation.json". You may be able to fix them.

Looks good to me otherwise.

**Comment by swarooprm** [comment]
@abmasud1214, can you address reviewer comments so that I can evaluate?

**Comment by abmasud1214** [comment]
Made all of the changes according to the comments.

**Comment by swarooprm** [comment]
@Mehrad0711, check and let me know if you are happy with the tasks?

**Comment by Mehrad0711** [comment]
Yeah, thanks for the fixes. LGTM.

**Comment by swarooprm** [comment]
Your HW2 is complete now.

Would you like to submit the same tasks to our big project repo https://github.com/allenai/natural-instructions-expansion/pulls? You just need to fork that repo, rename tasks starting from the latest number in the repo and create PR there. This way, you can be part of our research on "learning from instructions instead of learning from examples (conventional machine learning)". This is purely optional and your HW2 grade does not depend on this @abmasud1214

**Comment by swarooprm** [comment]
@abmasud1214 Just a reminder that, if you plan to submit these tasks to the main Github repo and join our research project, Monday (27th Sept) is the deadline. Again, this is optional and independent of your HW2 grade.

**Pull request closed without merging**
