### PR TITLE
Pegah: Task 593- 600: miam, freebase_qa

### PR DESCRIPTION
**Pull request by karthikmuru**

### CODE REVIEW

**Comment by swarooprm** [comment]
@Palipoor, wondering if you can help review this PR?

**Comment by Palipoor** [comment]
Hi!
1. In tasks 593 and 594, you've provided "Dialogue id"s. I don't think that's ok. You should include the whole dialogue in the inputs for it to be answerable. 
2. In task 595 please change "Given a sentence, generate the language to which the sentence belongs." to "Given a sentence, decide the language of that sentence". After that, "languages" -> "language"
3. In task 595 you have some characters like "d\u00edas". Please fix this with using "ensure_ascii = False" in JSON dumps.
4. In task 596 : "a open-ended" -> "an open-ended"
5. It seems to me that tasks 596 and 597 (and maybe 600) need outside information(like Wikipedia or a knowledge base) to be answered. I am not sure whether this kind of task is accepted. (@swarooprm )
6. In task 598 you have repeated outputs for some instances. Merge them into one.
7. In task 599, are the categories pre-defined? If so, please list them in the definition. Also, I don't think "Question Generation" is a fitting category for this task.

**Comment by swarooprm** [comment]
@karthikmuru, can you address reviewer comments so that I can evaluate?

**Comment by karthikmuru** [comment]
Hi @Palipoor, Thanks for your review!  I have addressed the comments.
1. Included the whole preceding dialogue sequences to the input for tasks 593 & 594.
2. Fixed the grammatical error. Task 595
3. Fixed the encoding error for task 595
4. Fixed the grammatical error. Task 596
5. The whole freebase_qa dataset is based on open-ended topics from the internet. The content/corpus which is used to derive the output is not present in the original dataset. Have added this to the definition. Need your thoughts on this @swarooprm. (Task 596, 597, 600)
6. Merged repeating outputs for task 598
7. Added the categories list to the definition for task 599. Also changed the task type.

**Comment by swarooprm** [comment]
Task 596,597 and 600 requires external knoweldge- this is fine.

@Palipoor, can you check other things and let us know if you are happy or have any other feedback?

**Comment by Palipoor** [comment]
Looks good to me! two small issues: in task 595, in one example the output is "english" and not "English".
Also in task 596, the first negative example has a typo. If that's part of it being incorrect, mention it in the explanation, otherwise please fix it.
Other than these everything is ok!

**Comment by karthikmuru** [comment]
@Palipoor  Fixed the typo mentioned in the previous comment.

**Comment by swarooprm** [comment]
Your HW2 is complete now.

Would you like to submit the same tasks to our big project repo https://github.com/allenai/natural-instructions-expansion/pulls? You just need to fork that repo, rename tasks starting from the latest number in the repo and create PR there. This way, you can be part of our research on "learning from instructions instead of learning from examples (conventional machine learning)". This is purely optional and your HW2 grade does not depend on this @karthikmuru

**Comment by swarooprm** [comment]
@karthikmuru Just a reminder that, if you plan to submit these tasks to the main Github repo and join our research project, Monday (27th Sept) is the deadline. Again, this is optional and independent of your HW2 grade.

**Comment by karthikmuru** [comment]
@swarooprm Yes, I want to push the changes to the main Repo. Will do this within today. Thanks for the reminder!

**Pull request closed without merging**
