### PR TITLE
Swaroop: Task 185-188: conll2002 dataset 

### PR DESCRIPTION
**Pull request by Mani9333**

### CODE REVIEW

**Comment by swarooprm** [comment]
@Mirzyaaliii, wondering if you can help review these tasks.

**Comment by Mirzyaaliii** [comment]
- General Comments -
1. Include dataset link and paper (if there is any) in the source field, for reference check tasks 166 and 313 [here](https://github.com/allenai/natural-instructions-expansion/tree/master/tasks).
2. In the README, write the tasks in order.
3. Correct grammar and typos in the definition from all the tasks (few suggestions are provided below also.).
4. In the file name, keep all letters small.

- Task - 185
1. Please check Task-345 [here](https://github.com/allenai/natural-instructions-expansion/tree/master/tasks) and change your whole task accordingly.
2. Also, check 312 on the same link and add the following things:
```
  "Input_language": "",
  "Output_language": "",
  "instruction_language": ""
```
Apply this change to all 4 tasks.

- Task - 186
1. In the definition, it is mentioned as _LOC_ and in the example, it is written as _LOCN_; correct it.
2. In the definition, correct this line
`You should respond with the valid NET tags.`

- Task - 187
1. There are some special characters (e.g. _\u00e9_) in some examples and instances, remove that.
Apply this change to 188 as well.
2. Elaborate definition by explaining that how to generate output (write about B and I tag, PER, etc.).
Apply this change to 188 as well.
3. In the 3rd positive example, there is no word **Bode** in the input then how does it come into output. (Correct it or explain it.)
4. Also mention in the definition that there can be instance exist which has 0 Name Entity in the input. (if this is the case,)
Apply this change to 188 as well.

**Comment by Mirzyaaliii** [comment]
- General comments -
1. Source and Category should be list not string (In all the tasks).
2. In the definition and explanation write **.** after each sentence and end (In all the tasks).
3. Delete the old file of Task -185.
4. Mention category at end of the filename (in all the tasks), for example,
`task185_conll2002_pos_tagging_answer_generation`
`task187_conll2002_person_name_extraction_answer_generation`
5. Change category of task 186 to _Answer Generation_.
6. In Task - 186 & 187, the output is in Dutch and English both languages, mention that in _Output_language_ in the list.
7. In Task - 186 & 187, return output as _None_, if there is no name or location entity presents in the input. That makes more sense, compared to an empty string.

**Comment by Mirzyaaliii** [comment]
All things look good to me, can you please just make this one change:
In Task 186-188, separate entity and entity name by **:** as below
`Marktrock: B-MISC, Leuven: B-LOC`

**Comment by Mirzyaaliii** [comment]
- One last change -
Change the definition (for Tasks 186-188)
from
`There can be the instances with no ... name entities.`
to
`There can be instances with no ... name entity then return \*None\*.`

**Comment by Mirzyaaliii** [comment]
@swarooprm All tasks look to me now. Proceed further.

**Comment by swarooprm** [comment]
@Mani9333, please fix the test failures and your HW2 will be complete.

**Comment by swarooprm** [comment]
Your HW2 is complete now.

Would you like to submit the same tasks to our big project repo https://github.com/allenai/natural-instructions-expansion/pulls? You just need to fork that repo, rename tasks starting from the latest number in the repo and create PR there. This way, you can be part of our research on "learning from instructions instead of learning from examples (conventional machine learning)". This is purely optional and your HW2 grade does not depend on this @Mani9333

**Comment by swarooprm** [comment]
@Mani9333, Just a reminder that, if you plan to submit these tasks to the main Github repo and join our research project, Monday (27th Sept) is the deadline. Again, this is optional and independent of your HW2 grade.

**Pull request closed without merging**
