### PR TITLE
Complete: Kirby: task 401-405 : diplomacy_detection, allocine, yahoo_answers_topics

### PR DESCRIPTION
**Pull request by RoseleenKaur**

### CODE REVIEW

**Comment by swarooprm** [comment]
@kurbster, wondering if you can help review these tasks?

**Comment by kurbster** [comment]
I can look at this

**Comment by kurbster** [comment]
For all tasks, make the following fields, _Contributors_ and _Categories_ a list of strings (even if there is only 1 option) and put them at the top of the son. Add the link to your dataset in the _Source_ field.

For task 401, can you make the definition more clear on this part `exchanges between 2 countries player`. What is a countries player? Is countries a game? Like Civ V or Risk? Also, why do all of the positive and negative examples include '\n' after each message but the instances don't. We should remove them from the examples to be consistent. There are some input instances that have no output, remove these examples or provide their output. Also, @swarooprm are emojis ok in the dataset?
For task 402, remove the fields _Input\_language_ and _Output\_language_ from the json file. Change the definition ` in french language` to `in French` or `in the French language`. Also, say `You need to predict its sentiment. Output a 0 for negative ... `. Remove the '\n label' from the end of the second negative example.
For task 404, you need to remove every instance of `<br />` in the dataset. This occurs throughout, a simple search and replace should work. Also, remove the `according to the www.fedex.com ...` from the first negative example and instances along with the `from ask yahoo ...` in the instance on line 62. 
For task 405, this category is question generation not answer generation. You need to add an explanation for the first positive example. Also, make the same removals as task 404.

**Comment by swarooprm** [comment]
@RoseleenKaur, can you address reviewer comments so that I can evaluate?

**Comment by RoseleenKaur** [comment]
Hi swaroop, I am working on it, I will update it by EOD and let you know.

**Comment by RoseleenKaur** [comment]
Hi @swarooprm, I have made the changes mentioned above.

**Comment by swarooprm** [comment]
@kurbster, check and let me know if you are happy with the changes?

**Comment by kurbster** [comment]
For task 401, on line 860 the output is just `I'd`. This example should be removed as it doesn't make any sense(sorry I didn't catch it the first time). 

Everything else looks good, just need to remove that one instance. Great job with the changes!

**Comment by RoseleenKaur** [comment]
Hi @kurbster and @swarooprm,
thanks @kurbster for pointing out all the issues.
I think there should be no more errors. 
@swarooprm please feel free to evaluate now.

**Comment by swarooprm** [comment]
Your HW2 is complete now.

Would you like to submit the same tasks to our big project repo https://github.com/allenai/natural-instructions-expansion/pulls? You just need to fork that repo, rename tasks starting from the latest number in the repo and create PR there. This way, you can be part of our research on "learning from instructions instead of learning from examples (conventional machine learning)". This is purely optional and your HW2 grade does not depend on this @RoseleenKaur

**Comment by swarooprm** [comment]
@RoseleenKaur Just a reminder that, if you plan to submit these tasks to the main Github repo and join our research project, Monday (27th Sept) is the deadline. Again, this is optional and independent of your HW2 grade.

**Pull request closed without merging**
