### PR TITLE
Kirby: Task_(118-121)_BSC-TeMU/tecla_scifact

### PR DESCRIPTION
**Pull request by NakulVaidya**

### CODE REVIEW

**Comment by swarooprm** [comment]
@kurbster, wondering if you can help review these tasks?

**Comment by kurbster** [comment]
I can look at this tonight.

**Comment by kurbster** [comment]
For every task, you should shuffle the Instances so they aren't the same for every task from a dataset. Also, you should have different positive and negative examples. Don't reuse the same inputs for both pos and neg examples.

For task 118, why is the input a string of a list? The input should just be a string.
For task 119, make the _Abstract_ field a string, not a string of a list, same comment as 118. 
For task 120, you should list the 30 different possible. Otherwise, the model will not know what to generate. Especially because you only have 2 positive examples so the model will only know of 2 possible classes. Also, some outputs contain leading and trailing whitespace. Remove any whitespace from the answers. Finally, make sure your classes are balanced. Each class should contain roughly the same number of instances.
For task 121, same comment as task 118. Also, you need to explain what structured means in the definition. You just say if the abstract is structured, but I don't know what that even means. Finally, you need to balance the different classes. _True_ had 937 instances and _False_ had 4063 instances, make sure they are roughly the same number of instances.

**Comment by kurbster** [comment]
You can keep the same positive and negative examples. But every other comment still applies.

**Comment by NakulVaidya** [comment]
Thanks, @kurbster I have updated all the tasks as suggested.

**Comment by kurbster** [comment]
When you changed the list into a string how did you do it? I noticed that the periods are not followed by a space, which could confuse the model into thinking some words are combined. You can use git to check out an old commit then run `' '.join(list)` in python.
Also, task120 is not balanced. Out of 30 classes, only 19 are used. If there is more source data, we may want to create other tasks (which is not part of the assignment so you are good). The breakdown for the tasks was

Parliament: 185
Trade: 232
Business: 121
Politics: 1104
Culture: 70
Education: 356
European Union: 105
Environment: 81
Cinema: 81
Events: 438
Society: 136
Government: 121
Health: 298
Police: 246
Tourism: 260
Economy: 127
Judicial: 87
Parties: 835
Letters: 117

**Comment by swarooprm** [comment]
@NakulVaidya, can you address reviewer comments so that I can evaluate?

**Comment by NakulVaidya** [comment]
@swarooprm I have made all the changes as suggested by @kurbster.

**Comment by kurbster** [comment]
@swarooprm everything looks good. Task 120 will need to be reworked before it goes into the final repo. Currently, it only includes 19 of the 30 possible categories. I can rework this task and submit a PR in the main repo. What would be best?

1. take `6500/30 = 216` examples of each category and only make 1 task.
2. split this task into multiple classification tasks grouped by related topics.
3. split this task into multiple classification tasks grouped by frequency in the original dataset.

**Comment by swarooprm** [comment]
Thanks @kurbster.
@NakulVaidya, you have created 4 tasks. One task (task120) has problem. I don't want to deduct points and would like to give you a chance if you are interested in fixing task120 as @kurbster suggested or create a new task?

**Comment by swarooprm** [comment]
> @swarooprm everything looks good. Task 120 will need to be reworked before it goes into the final repo. Currently, it only includes 19 of the 30 possible categories. I can rework this task and submit a PR in the main repo. What would be best?
> 
> 1. take `6500/30 = 216` examples of each category and only make 1 task.
> 2. split this task into multiple classification tasks grouped by related topics.
> 3. split this task into multiple classification tasks grouped by frequency in the original dataset.

Either of 2 or 3 will work.

**Comment by NakulVaidya** [comment]
@swarooprm I went through the entire BSC-TeMU/tecla dataset but I can only find 19 classes. I have changed the task definition to 19 classes and balanced all of them in the task.

**Comment by swarooprm** [comment]
Your HW2 is complete now.

Would you like to submit the same tasks to our big project repo https://github.com/allenai/natural-instructions-expansion/pulls? You just need to fork that repo, rename tasks starting from the latest number in the repo and create PR there. This way, you can be part of our research on "learning from instructions instead of learning from examples (conventional machine learning)". This is purely optional and your HW2 grade does not depend on this @NakulVaidya

**Comment by swarooprm** [comment]
@NakulVaidya Just a reminder that, if you plan to submit these tasks to the main Github repo and join our research project, Monday (27th Sept) is the deadline. Again, this is optional and independent of your HW2 grade.

**Pull request closed without merging**
