### PR TITLE
Complete: Mihir: Task 105-112: ProPara, cmrc2018, samsum Datasets 

### PR DESCRIPTION
**Pull request by Amrit-Bhaskar-abhask10**
I have uploaded 8 tasks for 3 datasets. Please review.

### CODE REVIEW

**Comment by swarooprm** [comment]
@Mihir3009, wondering if you can help review this PR?

**Comment by Mihir3009** [comment]
Task 105:

Let's make the definition more comprehensive (Change it to this):

`In this task, you are given a paragraph, and your job is to generate comma-separated entities present in the given paragraph. Generate entities from a given passage in such a way that (i) they are present in the paragraph, (ii) they are non-duplicate, (iii) they underwent a state change during the process. Avoid creating entities that (i) aren't present in the process paragraph and (ii) aren't significant. `

Task 106:

Few changes in the definition:

`In this task, you are given a paragraph, and your task is to construct a question from the given passage. Construct question in such a way that (i) it is well explained in the paragraph, (ii) the words may/may not be present in the paragraph, (iii) it should start with what/how/describe. Avoid creating a question that (i) is just relevant to one or two sentences, and (ii) not relevant to passage.`

Task 107:

1. Change the definition:

`In this task, you are given a paragraph, event and an entity. The event is part of the given paragraph and it changes the state of the entity. Your task is to classify the state of the entity into three classes: 1) not exist, 2) unknown location and 3) known location.  [Moreover, explain what each label means here].`

2. Follow the same format of input for 'Positive Examples', 'Negative Examples' and 'Instances'.

Task 108:

1. Change definition like this:

`In this task, you are given a paragraph, and your task is to construct a question from the given passage. Construct a question in such a way that (i) it is unambiguous, (ii) it is answerable from the passage, (iii) its answer is unique, and (iv) the answer is a continuous text span from the paragraph. Avoid creating questions that (i) can be answered correctly without actually understanding the paragraph and (ii) uses the same words or phrases given in the passage.`

2. Please use the language indicators as suggested in [#113](https://github.com/allenai/natural-instructions-expansion/issues/113)

Task 109:

1. Definition:

`In this task, you are given a paragraph and question, and your task is to generate the right answer for the given question from the passage. Construct an answer in such a way that (i) it is unambiguous, (ii) it is answerable from the passage, (iii) it is relevant to the question asked, and (iv) its answer is a continuous text span from the paragraph.`

2. Please use the language indicators as suggested in [#113](https://github.com/allenai/natural-instructions-expansion/issues/113)

Task 110:

1. Change category to "Answer Generation" only
2. Definition:

`In this task, you are given a paragraph and question. The answer to the given question is a span from the given passage. Your task is to generate the starting index of answer span for the given question from the passage. `
3. Please use the language indicators as suggested in [#113](https://github.com/allenai/natural-instructions-expansion/issues/113)
4. In the Instances, your outputs are wrong, check - 

{
            "input": " ... ",
            "output": [
                "dataset[i]['answers']['answer_start'][0]"    **[This should be the number]**
            ]
       },

Task 111:

1. Change category to "Summarization" from "Summarisation"
2. Definition:

`In this task, you are given a conversation, and your task is to generate a summary from the information present in the given conversation. Generate a summary in such a way that the context should be present in the conversation. It should cover the complete context of the conversation.`

3. Remove '\r\' from the input text. Keep them comma-separated

Task 112:

1. Change category to "Classification"
2. Definition:

`In this task, you are given two sentences taken from a conversation, and your job is to classify whether these given sentences are sequential or not. We will mark the given sentence pair as 'True' if it's sequential, otherwise 'False'. The two sentences are spoken by two different people.`

3. Remove '\r\' from input. Keep them comma-separated.

Let's Change Readme also:

Task 105: Generate entities from given text
Task 106: Generate question from the given passage
Task 107: Based on the passage, event, and entity, classify locations
Task 108: Generate question from the given passage
Task 109: Generate the right answer to a given question from the context passage
Task 110: Generate starting index of the answer span to a given question from the context passage
Task 111: Generate a summary of given conversations
Task 112: Classify whether given two dialogue sentences are sequential or not

(Change categories and JSON file names accordingly)

**Comment by swarooprm** [comment]
@Amrit-Bhaskar-abhask10, can you address reviewer comments so that I can evaluate your HW?

**Comment by Amrit-Bhaskar-abhask10** [comment]
@Mihir3009 By adding language indicators in 108, 109, and 110, do you mean, adding as part of the template? like 
input :
input_language :
output :
output_language:

**Comment by Mihir3009** [comment]
@Amrit-Bhaskar-abhask10 No. You don't have to add for all of the input output pairs.
Just before the definition, include three more keys in JSON:

For example, you have Bulgarian for input and English for output and you wrote definition in english then:
{
"Contributors": [],
"Source":[],
"Input_language": ['bg']
"Output_language": ['en']
"instruction_language": ['en']
"Definition":
.
.
.
.
}

**Comment by Amrit-Bhaskar-abhask10** [comment]
@swarooprm @Mihir3009 , Thanks for the review. I have updated the files w.r.t your comments.

**Comment by Mihir3009** [comment]
Don't remove swaroop's .json files and also don't remove that from Readme. Please update it.

**Comment by Amrit-Bhaskar-abhask10** [comment]
@Mihir3009 Added the files and updated the Readme.

**Comment by Mihir3009** [comment]
@swarooprm I am happy with @Amrit-Bhaskar-abhask10's work. I approve of this PR. Looks good to me.

**Comment by swarooprm** [comment]
Your HW2 is complete now.

Would you like to submit the same tasks to our big project repo https://github.com/allenai/natural-instructions-expansion/pulls? You just need to fork that repo, rename tasks starting from the latest number in the repo and create PR there. This way, you can be part of our research on "learning from instructions instead of learning from examples (conventional machine learning)". This is purely optional and your HW2 grade does not depend on this @Amrit-Bhaskar-abhask10

**Comment by swarooprm** [comment]
@Amrit-Bhaskar-abhask10 Just a reminder that, if you plan to submit these tasks to the main Github repo and join our research project, Monday (27th Sept) is the deadline. Again, this is optional and independent of your HW2 grade.

**Pull request closed without merging**
