### PR TITLE
Mirali Task897 - 900: LiMiT, QA-SRL_dataset

### PR DESCRIPTION
**Pull request by ssaivenkat176**
@swarooprm I have created a pull request. Please review the instruction tasks.

### CODE REVIEW

**Comment by ssaivenkat176** [comment]
@swarooprm 
The workflow is not running as it seems to require approval from the maintainer.
Could you please look into this?

**Comment by swarooprm** [comment]
@Mirzyaaliii, wondering if you can help review these tasks?

**Comment by Mirzyaaliii** [comment]
- General Comments -

1. Add contributor name to all the tasks.
2. Include dataset link and paper (if there is any) in the source field, for reference check tasks 166 and 313 [here](https://github.com/allenai/natural-instructions-expansion/tree/master/tasks).
3. Remove extra empty lines after Definition, Positive Examples and Negative Examples.
4. Correct grammar and typos in the definition of all the tasks and remove the repetitive parts. (few suggestions are provided below also.)
5. Elaborate summary for all the tasks in the README, (For reference check summary of few tasks from [here](https://github.com/allenai/natural-instructions-expansion/tree/master/tasks))

- Task-897
1. The provided definition and examples do not match, i.e.,
`"Definition": "In this task you are given a sentence and your task is answer the question with yes or no answers.You should answer the question using the information from the sentence. The answer to the question is yes if there is a physical occurrence of a motion of a physical entity otherwise the answer is no"`
i) you are given a sentence and your task is answer the question with yes or no answers **->** this sounds confusing and there is no connection between sentence and question.
ii) As mentioned in the definition that output should generate the answer to the question, however, there is no question in the input. Either correct the definition or correct the task.

- Task-898
1. In the definition, mention that if there can be an instance when there is 0 physical entity in the motion and if not mention that there is at least 1 entity exists.
2. In the output of instances, instead of separating entities by comma, make every entities element of the list. E.g.,
 ```
"output": [
            "I",
            "she",
            "home"
        ]
```
In the examples, keep it as it is. Just add space between each entity. i.e.,
`"output": "person, fruit, spoon"`

- Task-899
1. Include a separator between different elements of the input.
For example:
`"input": "Sentence: The album is named after the discredited pseudoscience of phrenology , the study of head shapes to determine intelligence and character , which was used to rationalize racism during the 19th century in the United States . \n Verb: named"`
(Apply this to Task-900 also)
2. In the definition, change this
i) In this task you are given a sentence and a verb in the sentence and your task ... **->** In this task, you are given a sentence and a verb from the sentence. Your task ...
ii) and the answers to these questions are phrases in the given sentence **->** and the answers to the generated questions are phrases in the given sentence
iii) (v) the length of the questions must not exceed 7 **->** what does _7_ indicate here?
iv) If _This set of questions must contain the verb and the answers to these questions are phrases in the given sentence._ and _(ii) it is answerable from the sentence,_ are the same thing, then remove either one and make definition concise.
v) Avoid creating questions that (i) can be answered correctly without actually understanding the sentence **->** What does this mean?? clarify.
3. Remove extra empty lines.

**Comment by Mirzyaaliii** [comment]
Looks good to me almost, just a few minor changes

- Task - 897
1. Simplify this statement in the definition (Task - 897)
`... The sentence belongs to the 'yes' category if there is a physical occurrence of a motion of a physical entity ...`
2. There are some yes and no capital and some small. Write all like this **Yes** and **No**.
3. In the explanation of the examples, you mentioned present tense and all, if this is the case write in the definition that when some physical entity in the motion should provide answer Yes and when No.

- Task - 898
1. Combine this line
`The sentence will contain at least one entity. The sentence might contain more than one entity taking part in various physical motions.`
something like this
`The input sentence can have more than one entity and also there is at least one entity that takes part in physical motion.`

- Task - 899
1. In the definition
`This set of questions must contain the verb and the answers to the generated questions are phrases in the given sentence. The answer to these questions is associated with a specific semantic role.`
change this like to something like this
`The generated questions must contain the verb and the answers to these questions are phrases in the input sentence. The answer to the questions is associated with a specific semantic role.`

- Task - 900
1. Keep space after every sentence. For example, in the definition
`... ed using the sentence.Your task is to answer the ...`
Keep space between 2 sentences. Check in the explanation also.

**Comment by ssaivenkat176** [comment]
In the explanation of the examples, you mentioned present tense and all, if this is the case write in the definition that when some physical entity in the motion should provide answer Yes and when No.

Could you explain this?Did not get this point

**Comment by Mirzyaaliii** [comment]
> In the explanation of the examples, you mentioned present tense and all, if this is the case write in the definition that when some physical entity in the motion should provide answer Yes and when No.
> 
> Could you explain this?Did not get this point

In the 2nd and 3rd positive examples, you mentioned that motion exists in the input but it is not currently happening. Also, in the 4th example, you wrote that the input sentence is in the present tense and it has motion.
So. define these criteria in the definition that when the output is Yes and when No in terms of _when motion is happening_.

**Comment by swarooprm** [comment]
@ssaivenkat176, can you address reviewer comments so that I can evaluate your HW?

**Comment by ssaivenkat176** [comment]
@swarooprm 
Could you please approve the workflow?
@Mirzyaaliii 
I have addressed your comments. Please look into it.

**Comment by swarooprm** [comment]
@Mirzyaaliii, check and let me know if you are happy or have any other feedback?

**Comment by Mirzyaaliii** [comment]
All tasks look good to me. Just a few minor comments -

- Contributor and Category should be list not string.
- There are few grammatical errors in the explanations. So, please once pass this on the Grammarly (or a similar tool). Hence, there will be no grammatical, punctuation, spacing, etc errors.

**Comment by ssaivenkat176** [comment]
@Mirzyaaliii addressed comments.
@swarooprm please approve the workflow.

**Comment by Mirzyaaliii** [comment]
@swarooprm All tasks look good to me. Proceed further.

**Comment by swarooprm** [comment]
Your HW2 is complete now.

Would you like to submit the same tasks to our big project repo https://github.com/allenai/natural-instructions-expansion/pulls? You just need to fork that repo, rename tasks starting from the latest number in the repo and create PR there. This way, you can be part of our research on "learning from instructions instead of learning from examples (conventional machine learning)". This is purely optional and your HW2 grade does not depend on this @ssaivenkat176

**Comment by swarooprm** [comment]
@ssaivenkat176 Just a reminder that, if you plan to submit these tasks to the main Github repo and join our research project, Monday (27th Sept) is the deadline. Again, this is optional and independent of your HW2 grade.

**Pull request closed without merging**
