### PR TITLE
Swaroop Task 273-277: xlsum and numer_sense datsets

### PR DESCRIPTION
**Pull request by krishnasree11**

### CODE REVIEW

**Comment by nrjvarshney** [comment]
Task 273, 274, 275 - 
* You can shorten the task definition something like "In this task, you need to generate an appropriate title for the given text. The title must be short and include the main topic of the text." Add/edit if I missed any instruction.
* Improve the explanation, specify why the output is correct/incorrect.
* The inputs are very long. This would limit the number of instances that can be used for evaluation (token limit). is that a concern @swarooprm  or we can ignore this?

Task 276 and 277 - 
* Make it a multiple-choice QA task and specify that in the task definition
* Include the redundant phrase "Choose the right answer from options given" in the definition itself. 
* You can have the option text as the answer instead of (a), (b) 
* It would be better if you could have questions that require numerical commonsense reasoning (not facts). 
* Improve explanations - 

```
{
            "input": "Some plant varieties can grow up to ____ feet tall.",
            "output": "nine",
            "explanation": "Any value ranging between five to ten is valid. So, nine feet is the correct answer"
},
```
You will give the options in the input and then you can write "A plant's height typically ranges between five and ten. So, ...."

**Comment by krishnasree11** [comment]
@nrjvarshney Appreciate your detailed review. 

I had one query wrt Task 277 based on your comment "It would be better if you could have questions that require numerical commonsense reasoning (not facts)." All the instances and examples have been picked up from numer-sense dataset. So, I'm not sure how I could modify the question.

**Comment by krishnasree11** [comment]
@swarooprm @nrjvarshney Due to laptop issue, I used my roommates laptop to complete assignment and accidentally pushed the code under her github account. As I cannot revert the push, I have addressed all the review comments and updated the code, pushed with my github account. Sorry for the inconvenience caused. Please let me know if I need to create new branch for pushing the code again or if any other additional modifications.

**Comment by nrjvarshney** [comment]
Just minor comments;
Task 274 -
* "The summary includes the main topic of the text." --> "The summary should include ..."

Task 276  and 277- 
* In the definition, specify what is blank, in brackets may be.
* None of my previous comments have been addressed for this task.

**Comment by krishnasree11** [comment]
@nrjvarshney 
with respect to these comments 
"Include the redundant phrase "Choose the right answer from options given" in the definition itself.
You can have the option text as the answer instead of (a), (b)"

I had a discussion with @swarooprm before starting the task and I was asked to refer to the following link which contains multiple choice QA task. 
https://github.com/allenai/natural-instructions-expansion/blob/master/tasks/task104_semeval_2019_task10_closed_vocabulary_mathematical_answer_generation.json
So, while creating my task I refer to the particular example in the above mentioned link and followed the same approach.

I have addressed remaining comments. Please let me know if any other additional modifications are required.

**Comment by nrjvarshney** [comment]
I don't think task 276 makes any sense.
Examples like this are facts:
```
  "input": "Illiteracy is ____ percent higher among women than men.",
            "output": [
                "seven"
            ]

{
            "input": "Babies usually wet the diaper at least ____ times each day.",
            "output": [
                "six"
            ]
        },
```

Even humans can't answer such questions.


Task 277 - 
* Definition: "In this task, you're given a sentence with a missing word which should be a no or number (between zero and ten) and four options to choose the correct answer. Your task is to select the right choice from the given options." does not follow the task definition.
* Similar to the task 276 --> these questions are subjective or fact based. 

@krishnasree11 , the above comments are not for you. 
cc @swarooprm

**Comment by swarooprm** [comment]
@krishnasree11, 
In Task 276: there are some obvious noise e.g.
{
            "input": "Maximum age is ____ years, but most live for four years.",
            "output": [
                "seven"
            ]
        },
Just have a look and remove instances that contain such ambiguous statements (I know you can't find everything manually, but do as far as you can)

Task 277: the problem is actually more than one option can be correct e.g. look at the positive example-1, here in explanation you say 5-10 feet, with that more than one option is correct. 
In Task 277 also, just have a quick look and delete such example which appear ambiguous
If you have some way to filter such instances automatically it would be great, but I understand there might not be. 
Spend a few minutes on this and let me know once you are done.

**Comment by swarooprm** [comment]
@krishnasree11, can you address my comment so that I can evaluate your HW?

**Comment by krishnasree11** [comment]
@swarooprm I have approx. 6000 instances in Task 276 & 277. I analyzed the datasets, to come up with a programmatic solution for eliminating the ambiguous sentences but didn't find any success there. 

I tried to remove a few instances manually but its getting infeasible to eliminate on a large scale. The main challenge lies in the process of identification of ambiguous sentences. Please let me know, if you came across a better approach or alternative solutions to fix this issue.

**Comment by swarooprm** [comment]
> @swarooprm I have approx. 6000 instances in Task 276 & 277. I analyzed the datasets, to come up with a programmatic solution for eliminating the ambiguous sentences but didn't find any success there.
> 
> I tried to remove a few instances manually but its getting infeasible to eliminate on a large scale. The main challenge lies in the process of identification of ambiguous sentences. Please let me know, if you came across a better approach or alternative solutions to fix this issue.

I understand your concern. Try if filtering and removing instances that contain the word "usually", "can", "higher" (find more such patterns) help.

The above filter might not fully remove annotation issue, in that case, maker sure to remove the visible issues i.e. the ones present in positive, negative examples and first few instances (some of which i pointed in my previous comment.) Delete positive example 1 and replace with an example where there is a definite numeric answer attached.

You are pretty close to completing HW and have done a great job so far. Once you do the things I have mentioned here, your HW will be complete.

**Comment by swarooprm** [comment]
> > @swarooprm I have approx. 6000 instances in Task 276 & 277. I analyzed the datasets, to come up with a programmatic solution for eliminating the ambiguous sentences but didn't find any success there.
> > I tried to remove a few instances manually but its getting infeasible to eliminate on a large scale. The main challenge lies in the process of identification of ambiguous sentences. Please let me know, if you came across a better approach or alternative solutions to fix this issue.
> 
> I understand your concern. Try if filtering and removing instances that contain the word "usually", "can", "higher" (find more such patterns) help.
> 
> The above filter might not fully remove annotation issue, in that case, maker sure to remove the visible issues i.e. the ones present in positive, negative examples and first few instances (some of which i pointed in my previous comment.) Delete positive example 1 and replace with an example where there is a definite numeric answer attached.
> 
> You are pretty close to completing HW and have done a great job so far. Once you do the things I have mentioned here, your HW will be complete.

A gentle reminder!

**Comment by krishnasree11** [comment]
@swarooprm I have changed the positive, negative examples and removed ambiguous sentences from first 1000 instances. Please check and let me know if any additional changes are required.

**Comment by swarooprm** [comment]
Your HW2 is complete now.

Would you like to submit the same tasks to our big project repo https://github.com/allenai/natural-instructions-expansion/pulls? You just need to fork that repo, rename tasks starting from the latest number in the repo and create PR there. This way, you can be part of our research on "learning from instructions instead of learning from examples (conventional machine learning)". This is purely optional and your HW2 grade does not depend on this @krishnasree11

**Comment by swarooprm** [comment]
@krishnasree11  Just a reminder that, if you plan to submit these tasks to the main Github repo and join our research project, Monday (27th Sept) is the deadline. Again, this is optional and independent of your HW2 grade.

**Pull request closed without merging**
