### PR TITLE
Kirby: Task 633-636

### PR DESCRIPTION
**Pull request by sudeepn96**

### CODE REVIEW

**Comment by swarooprm** [comment]
@shailaja183, wondering if you can help review this PR?

**Comment by swarooprm** [comment]
@kurbster, wondering if you can help review this PR?

**Comment by kurbster** [comment]
Could you shuffle your instances between tasks with similar datasets so they are not in the same order. `random.shuffle` will do the job.

For task 633, the instance on line 152 has some weird output. I know this dataset includes _#_ instead of the actual numbers, but this example seems off to me.

For task 634, change the category to incorrect summarization. Then update the definition to say `write a short incorrect summarization`. For the positive and negative examples, you should reverse what you said. For positive `The example is correct because the summary is incorrect as the location ... `. For negative `The example is incorrect because the summary is correct as it correctly ...`. Also, that same weird output is on line 94 can you remove that instance.

For task 635, make the definition more clear, saying generate for that statement could mean different things. Say something like `... generate a question that will be answered by the statement.`

For task 636, the definition could be more clear because it could generate an answer that was not mentioned in the statement. Say `... generate an answer to the question. The answer should be contained in the statement.` Also, you did not include instances for this task and just copied the instances from task 635.

**Comment by swarooprm** [comment]
@sudeepn96, can you address reviewer comments so that I can evaluate your HW?

**Comment by sudeepn96** [comment]
> @sudeepn96, can you address reviewer comments so that I can evaluate your HW?

I have made the fixes, could you review again?

**Comment by kurbster** [comment]
For task 634, update the definition to say `write a short incorrect summary based on the passage`.
Everything else looks good you just need to update that definition.

**Comment by sudeepn96** [comment]
> For task 634, update the definition to say `write a short incorrect summary based on the passage`.
> Everything else looks good you just need to update that definition.

I have updated the definition.

**Comment by swarooprm** [comment]
Your HW2 is complete now.

Would you like to submit the same tasks to our big project repo https://github.com/allenai/natural-instructions-expansion/pulls? You just need to fork that repo, rename tasks starting from the latest number in the repo and create PR there. This way, you can be part of our research on "learning from instructions instead of learning from examples (conventional machine learning)". This is purely optional and your HW2 grade does not depend on this @sudeepn96

**Comment by swarooprm** [comment]
@sudeepn96 Just a reminder that, if you plan to submit these tasks to the main Github repo and join our research project, Monday (27th Sept) is the deadline. Again, this is optional and independent of your HW2 grade.

**Pull request closed without merging**
