### PR TITLE
Swaroop Task 929-936: Math Dataset & Viquiquad

### PR DESCRIPTION
**Pull request by chiragvartak**
Name: Chirag Vartak
Datasets: BSC-TeMU/viquiquad and math_dataset
Tasks assigned: 929-936 (actual tasks done are 4)

### CODE REVIEW

**Comment by swarooprm** [comment]
Reviewed during call today

**Comment by chiragvartak** [comment]
Comments have been addressed. These include:
1) Made some positive/negative examples' explanations more verbose
2) Made the task definitions more clear, removed vague statements, removed redundancy
3) Added the input and output language fields for Catalan language tasks

**Review by swarooprm — COMMENTED** [review]
@chiragvartak your tasks looks good.
Just make sure that in the classification tasks, instances are label-balanced.
Once you confirm the numbers of each class, your HW2 will be complete.
Let me know once you are done.

**Comment by chiragvartak** [comment]
@swarooprm Yes the classes are balanced.  
There are 5 classes: algebra, arithmetic, measurement, numbers, probability
There are total 8000 instances, 1600 of each class.

**Comment by chiragvartak** [comment]
@swarooprm 
Oh yes, certainly. If all that's required to do is a few changes and another PR, I see no reason not to.
I'll do that by the end of this week.

**Comment by swarooprm** [comment]
@chiragvartak  Just a reminder that, if you plan to submit these tasks to the main Github repo and join our research project, Monday (27th Sept) is the deadline. Again, this is optional and independent of your HW2 grade.

**Comment by chiragvartak** [comment]
@swarooprm, Done: https://github.com/allenai/natural-instructions-expansion/pull/326

**Pull request closed without merging**
