### PR TITLE
Mihir: Task 825 - 826: NLU Evaluation Data

### PR DESCRIPTION
**Pull request by bedr2341**

### CODE REVIEW

**Comment by swarooprm** [comment]
Hi @bedr2341, your tests are failing. Can you fix your files so that tests pass and we can start evaluating your PR.

**Comment by bedr2341** [comment]
My tests are now passing

**Comment by swarooprm** [comment]
@kuntalkumarpal, wondering if you can help review this PR?

**Comment by swarooprm** [comment]
@Mihir3009, can you help review this PR?

**Comment by Mihir3009** [comment]
General Suggestions:

1. In the readme and task folder, add the squad tasks that Swaroop added already (don't remove those)
2. In the source, add a dataset link like this - [Datatset Name] (Link- )

Questions:

1. In task 825, classify the intent of the input into one of the following 18 categories, but I am seeing only 4 categories. (Same for Task 827).
2. Moreover, apart from different class names, what is the difference between the tasks that you created? Basically, you can merge all of them into one and say that classify instance into 16/18 categories. I think you can merge all of them or explain why they have to be different?

**Comment by bedr2341** [comment]
Thank you for the reminder, I will submit tonight

**Comment by bedr2341** [comment]
@Mihir3009 I did as you said. I merged all four tasks into one. I then created a second task that classifies labels instead of scenarios. I also updated the README and Source to follow your suggestions.

I had created a third and fourth task that's about text generation based on the label or scenario given only to realize that input can't be repeated. I had already finished the tasks at that time, but they don't pass the tests and so the tasks are likely not what you want. It's 3 AM, so I just pushed the acceptable work that I have, which are only task 825 and 826.

I apologize for my tardiness with the updates, the semester had been rough. Thank you for your patience and reminders.

**Comment by swarooprm** [comment]
Your HW2 is complete now @bedr2341.

**Pull request closed without merging**
