### PR TITLE
Task235_Task257

### PR DESCRIPTION
**Pull request by saurabh1mohite**
Upload the json file containing following information

task  - task name
definition - original definition
alternate_definition - alternate definition
technique - technique used to create the alternate definition from the original definition
bleu_score - the bleu_score computed for comparing the quality of the alternate_definition generated w.r.t. the original definition
need_manual_modification - tells whether the alternate_definition needs any update, either because it has a bleu_score less than 0.5 or the alternate_definition has some <unk> tags due to out of vocabulary words.

Tasks 
"task235_iirc_question_from_subtext_answer_generation.json
task236_iirc_question_from_passage_answer_generation.json
task237_iirc_answer_from_subtext_answer_generation.json
task238_iirc_answer_from_passage_answer_generation.json
task239_tweetqa_answer_generation.json
task240_tweetqa_question_generation.json
task241_tweetqa_classification.json
task242_tweetqa_classification.json
task243_count_elements_in_set_intersection.json
task244_count_elements_in_set_union.json
task245_check_presence_in_set_intersection.json
task246_dream_question_generation.json
task247_dream_answer_generation.json
task248_dream_classification.json
task249_enhanced_wsc_pronoun_disambiguation.json
task250_spl_translation_en_ar.json
task251_spl_translation_en_fi.json
task252_spl_translation_en_tr.json
task253_spl_translation_en_zh.json
task254_spl_translation_fi_en.json
task255_spl_translation_it_en.json
task256_spl_translation_de_en.json
task257_spl_translation_ar_en.json"

### CODE REVIEW

**Comment by saurabh1mohite** [comment]
Upload the json file containing following information

task - task name
definition - original definition
alternate_definition - alternate definition
technique - technique used to create the alternate definition from the original definition
bleu_score - the bleu_score computed for comparing the quality of the alternate_definition generated w.r.t. the original definition
need_manual_modification - tells whether the alternate_definition needs any update, either because it has a bleu_score less than 0.5 or the alternate_definition has some tags due to out of vocabulary words.

Tasks
"task235_iirc_question_from_subtext_answer_generation.json
task236_iirc_question_from_passage_answer_generation.json
task237_iirc_answer_from_subtext_answer_generation.json
task238_iirc_answer_from_passage_answer_generation.json
task239_tweetqa_answer_generation.json
task240_tweetqa_question_generation.json
task241_tweetqa_classification.json
task242_tweetqa_classification.json
task243_count_elements_in_set_intersection.json
task244_count_elements_in_set_union.json
task245_check_presence_in_set_intersection.json
task246_dream_question_generation.json
task247_dream_answer_generation.json
task248_dream_classification.json
task249_enhanced_wsc_pronoun_disambiguation.json
task250_spl_translation_en_ar.json
task251_spl_translation_en_fi.json
task252_spl_translation_en_tr.json
task253_spl_translation_en_zh.json
task254_spl_translation_fi_en.json
task255_spl_translation_it_en.json
task256_spl_translation_de_en.json
task257_spl_translation_ar_en.json"

**Comment by Ravsehajsinghpuri** [comment]
@saurabh1mohite can you fix the checks? they are failing

**Comment by saurabh1mohite** [comment]
My other pull request got approved with an option of merge request. Should I close this pull request? And is my submission successful?

**Comment by Ravsehajsinghpuri** [comment]
> My other pull request got approved with an option of merge request. Should I close this pull request? And is my submission successful?

which PR? I can't see your tasks in the main branch, can you tell me the PR number?

**Comment by Ravsehajsinghpuri** [comment]
> > My other pull request got approved with an option of merge request. Should I close this pull request? And is my submission successful?
> 
> which PR? I can't see your tasks in the main branch, can you tell me the PR number?

#164 I can see that you have raised this PR for the same tasks, Please close the redundant one and add 1) original tasks, task variants in the correct naming format mentioned above.

**Comment by saurabh1mohite** [comment]
Actually I did not rename the file as task235.1 and so on because each task
has a lot of multiple alternate definitions thus creating a separate file
for each new paraphrased definition is not feasible.
Thank you

With Regards,
Saurabh Balasaheb Mohite

**Comment by saurabh1mohite** [comment]
When I am trying to create a PR with lot of files git is throwing error
attached below.

**Pull request closed without merging**
