### PR TITLE
Mihir: Task: 713-716 Deceptive Opinion Spam dataset, hate_speech_offensive

### PR DESCRIPTION
**Pull request by meghpatel**

### CODE REVIEW

**Comment by swarooprm** [comment]
@Mihir3009, wondering if you can review this PR?

**Comment by swarooprm** [comment]
@Mihir3009, let @meghpatel know your feedback?

**Comment by Mihir3009** [comment]
Task 713:

1. Let's make the definition more comprehensive (Change it to this):

`In this task, you are given hotel review as input. Your task is to classify the given review based on its content and sentiment into two classes: negative and positive.`

2. Change labels 1 and 2 into positive and negative.

Task 714:

1. Let's make the definition more comprehensive (Change it to this):
`In this task, you are given hotel review and the corresponding polarity of review (i.e., Negative or Positive). Your task is to identify if the polarity is correct. Generate label 'true' if it's correct, 'false' otherwise.`

Task 715:

1. Let's make the definition more comprehensive (Change it to this):

`In this task, you are given a text of the tweet as input. Your task is to classify the given input into the three categories: (1) 'Hate Speech', (2) 'Offensive' and (3) 'Neither'.  [Explain each label here].`

2. Change 0,1, and 2 into label names

Task 716:

1. Let's make the definition more comprehensive (Change it to this):

`In this task, you are given a text of the tweet and a corresponding label whether this tweet is 'Offensive', 'Hate Speech' or 'Neither'. Your job is to identify if the label is correct. Generate label 'true' if it's correct, 'false' otherwise.`

General Comments:

1. Give me samples for each class for all the Tasks [Want to confirm that it is almost balanced]. Send numbers here, it's fine. Make classes almost balance (No need to be exactly the same)
2. Let's update the readme:

Task 713: Identity polarity of hotel reviews
Task 714: Given hotel reviews and it's polarity, determine whether it's true or false
Task 715: Classify tweets into hate speech, offensive or neither
Task 716: Given tweet and it's category, determine whether it's true or false

**Comment by Mihir3009** [comment]
@meghpatel Can you please address the comments?

**Comment by swarooprm** [comment]
> @meghpatel Can you please address the comments?

@meghpatel, can you address comments soon so that I can evaluate your HW?

**Comment by meghpatel** [comment]
> > @meghpatel Can you please address the comments?
> 
> 
> 
> @meghpatel, can you address comments soon so that I can evaluate your HW?

Yes @swarooprm

**Comment by meghpatel** [comment]
@Mihir3009 @swarooprm I've completed the suggested changes.

The dataset and the class distribution is as follows:

1) Deceptive Opinion Spam Dataset
800: Positive
800: Negative

2) Hate Speech Offensive
1430: Hate Speech
2535: Offensive
2535: Neither

**Comment by swarooprm** [comment]
> @Mihir3009 @swarooprm I've completed the suggested changes.
> 
> The dataset and the class distribution is as follows:
> 
> 1. Deceptive Opinion Spam Dataset
>    800: Positive
>    800: Negative
> 2. Hate Speech Offensive
>    1430: Hate Speech
>    2535: Offensive
>    2535: Neither

Ok, @Mihir3009 will check and let us know if he is happy or has any other feedback.

**Comment by Mihir3009** [comment]
@swarooprm I am happy with @meghpatel's work. I approve of this PR. Looks good to me.

**Comment by swarooprm** [comment]
Your HW2 is complete now.

Would you like to submit the same tasks to our big project repo https://github.com/allenai/natural-instructions-expansion/pulls? You just need to fork that repo, rename tasks starting from the latest number in the repo and create PR there. This way, you can be part of our research on "learning from instructions instead of learning from examples (conventional machine learning)". This is purely optional and your HW2 grade does not depend on this @meghpatel

**Comment by swarooprm** [comment]
@meghpatel Just a reminder that, if you plan to submit these tasks to the main Github repo and join our research project, Monday (27th Sept) is the deadline. Again, this is optional and independent of your HW2 grade

**Pull request closed without merging**
