### PR TITLE
Swaroop: Task 745-749: Opus Ted Talks & Health Fact

### PR DESCRIPTION
**Pull request by vansh-patel-asu**
@swarooprm Hi, I have created a pull request, request you to check and provide suggestions for the same.

Regards,
Vansh Patel 
vpatel44

### CODE REVIEW

**Comment by swarooprm** [comment]
@shailaja183, wondering if you can help in reviewing these tasks?

**Comment by shailaja183** [comment]
Looks good mostly, minor fixes;

task745/747:
1. No need of mentioning "can be used by you to translate the speech for a Croatian delegate." (745)
2. include hyphen inside special character list (745/747)
3. Remove "to their equivalent in your language." -- "to their equivalent in XYZ language" (745)
4. Instead of "Please do the same in your translations.", say "Input is case-sensitive .... and output is expected to case sensitive ..." (745/747)
5. In negative examples, you include 'punctuations' in your explanation but you have not mentioned any guideline related to punctuations in definition (745/747)

task746:
1. "we have a paragraph and a claim" -- change to "you will be given a paragraph and a claim"
2. no need of -- The claim starts with *Claim:* and paragraph starts with *Paragraph*.
3. "We have four categories of output," --  change to "the task is to classify the claim in x,y,z,w labels based on the given paragraph"
4. typos in definition - a multiple, evidences

task748:
1. "need to find a claim from within the given paragraph" -- change "we need to generate a claim that is supported by the given paragraph". 
2. Rewrite "Nothing will be outside the paragraph." -- "The claim must contain information ..."
3. Rewrite "A sentence within the paragraph can be a fact." -- "A sentence within the paragraph can be used as a claim"
4. Use "claim" consistently (do not use fact)
5. If you use sentences from the passage in explanation, include them in '' (do not copy too many sentences, just one or two which are most important)

task749:
1. "we have a paragraph and a claim" -- change to "you will be given a paragraph and a claim"
2. no need of -- The claim starts with *Claim:* and paragraph starts with *Paragraph*.
3. following points while providing an output -- following points while "generating" an output
4. "We need to generate" -- "generate" 
5. bring point 1) after "you will be given a paragraph and a claim" (that explains what task is to be done and then explain what things should be taken care of when generating explanation)
6. typo - "emphasised"

**Comment by vansh-patel-asu** [comment]
@shailaja183, @swarooprm  Hi, I have corrected all the issues. 

Regards,
Vansh Patel

**Comment by shailaja183** [comment]
@swarooprm check the categories of 748 and 749. 749 seems like Long text generation to me. 
Rest of the tasks look good to me!

@vansh-patel-asu based on swaroop's response, please commit changes one final time. Also couple more fixes;
745/747 - remove 'TED talks', 'hyphens or'
748/749 - add a line in the definition suggesting -- how long the claim/explanation should be

**Comment by Heave6899** [comment]
@shailaja183 yes I'll commit the changes after Swaroop mentioned the changes along with yours.

**Comment by shailaja183** [comment]
@swarooprm waiting for your opinion -- 
check the categories of 748 and 749. 749 seems like Long text generation to me.

**Comment by swarooprm** [comment]
@vansh-patel-asu, category of 748-sentence generation looks good. 749 should be long text generation.

**Comment by swarooprm** [comment]
> @vansh-patel-asu, category of 748-sentence generation looks good. 749 should be long text generation.

@vansh-patel-asu, can you address comments so that I can evaluate your tasks?

**Comment by vansh-patel-asu** [comment]
Hi @swarooprm, all corrections addressed

**Comment by swarooprm** [comment]
Your HW2 is complete now.

Would you like to submit the same tasks to our big project repo https://github.com/allenai/natural-instructions-expansion/pulls? You just need to fork that repo, rename tasks starting from the latest number in the repo and create PR there. This way, you can be part of our research on "learning from instructions instead of learning from examples (conventional machine learning)". This is purely optional and your HW2 grade does not depend on this @vansh-patel-asu

**Comment by swarooprm** [comment]
@vansh-patel-asu  Just a reminder that, if you plan to submit these tasks to the main Github repo and join our research project, Monday (27th Sept) is the deadline. Again, this is optional and independent of your HW2 grade.

**Pull request closed without merging**
