### PR TITLE
Mihir: Tasks 665-668 : Amazon/Yalp reviews and Google welformed query

### PR DESCRIPTION
**Pull request by paik1**

### CODE REVIEW

**Comment by swarooprm** [comment]
@Mihir3009, wondering if you can help review this PR?

**Comment by Mihir3009** [comment]
General Changes:

1. Add Contributors and Categories fields in JSON. 
2. Change JSON file names accordingly

Let's update the readme:

Task 666: Given a query, classify whether it's a good or bad query (Classification)
Task 667: Given a set of queries, find out the query which is not well-formed (Sentence Generation)
Task 668: Given a set of queries, find out the query which is well-formed (Sentence Generation)

(Change JSON names accordingly)


Task 665:

Make Category Summarization in JSON

1. Dataset name is too long (Change it to "Amazon and Yelp Summarization Dataset") - Change JSON file name accordingly.
2. Here is the deal, they are generating summaries from a set of reviews but not from one review, that should be reflected in definition and inputs. So Let's change the definition into this first:

`In this task, you are given a set of reviews from Amazon and Yelp. Your task is to generate a summary of a given set of reviews about the information present in reviews. This generated summary should reflect user common opinions expressed in the review, the common sentiment of the opinions and their details, and should be coherent with the given set of reviews in terms of sentence and information structure. Avoid creating summaries that (i) contains additional information which is not present in reviews, (ii) look exactly like the review, and (iii) uses 5 or more same consecutive words or phrases given in the review.`

Now let's deal with the inputs:
You can give input reviews like this -> "Review_1: ....., Review_2: ...., Review_3: ..... , "
Change this also.

Task 666:

Make this task "Binary Classification" task where you can say that if the score is >0.5 ("Good"), <0.5 (Bad) query. Don't make generation task


Task 667:

Add task category: "Sentence Generation"

Let's make the definition more comprehensive (Change to this):
`In this task, you are given a set of queries separated by '\n', and your job is to find out the query which is not a well-formed or well-structured query in terms of grammar, punctuations, or spelling errors from the list.`

Task 668:

Add task category: "Sentence Generation"

Let's make the definition more comprehensive (Change to this):
`In this task, you are given a set of queries separated by '\n', and your job is to find out the query which is a well-formed or well-structured query in terms of grammar, punctuations, or spelling errors from the list.`

**Comment by swarooprm** [comment]
Your HW2 is complete now.

Would you like to submit the same tasks to our big project repo https://github.com/allenai/natural-instructions-expansion/pulls? You just need to fork that repo, rename tasks starting from the latest number in the repo and create PR there. This way, you can be part of our research on "learning from instructions instead of learning from examples (conventional machine learning)". This is purely optional and your HW2 grade does not depend on this @paik1 ?

**Comment by swarooprm** [comment]
@paik1, can you address reviewer comments so that I can evaluate your HW?

**Comment by paik1** [comment]
Hi, I have made the requested changes. Will be pushing the modified files by tonight

**Comment by paik1** [comment]
@swarooprm @Mihir3009 . I have made all the suggested changes and committed them. Thank you for your suggestions @Mihir3009

**Comment by Mihir3009** [comment]
@swarooprm Looks good to me. I approve of this PR.

**Comment by swarooprm** [comment]
Your HW2 is complete now.

Would you like to submit the same tasks to our big project repo https://github.com/allenai/natural-instructions-expansion/pulls? You just need to fork that repo, rename tasks starting from the latest number in the repo and create PR there. This way, you can be part of our research on "learning from instructions instead of learning from examples (conventional machine learning)". This is purely optional and your HW2 grade does not depend on this @paik1

**Pull request closed without merging**
