### PR TITLE
Complete: Tasks 729-734: DSTC3 and Hatexplain

### PR DESCRIPTION
**Pull request by Pruthvi98**

### CODE REVIEW

**Comment by swarooprm** [comment]
@aarunku5, wondering if you can help in reviewing these tasks?

**Comment by aarunku5** [comment]
729- looks good
730- In the definition change "Note: ..." to "Note that if...."
731- In the definition change: "...user, followed by a question...". The category is "Answer Generation".
732- Remove "Note:...." in the definition.
733- Grammatical errors in definition, "is can be", "one or more community". Also change to "nine values: ", include "None" in quotes. Specify in the definition that "if multiple communities are targeted, the output must be separated by commas, in the following format: output: "community 1, community 2"
734- In the definition, specify that "the output must be separated by commas if there are multiple phrases, in the following format: output: "phrase 1, phrase 2". The category is "Answer Generation".

Also in tasks 732-734 replace examples that use more severe slurs (N/F/etc.). They can be included in the instances, but not in the positive/negative examples.

**Comment by Pruthvi98** [comment]
Hi @aarunku5, thanks for taking out time to review my submission. I have made the changes you suggested. 

I had an email correspondence with @swarooprm yesterday where he said that if the instances have multiple outputs, like tweet targeting more than one community, then the number of outputs for each input should remain same throughout. Similarly for the last task, 734 where the task is to output offensive and hate speech phrases, the number of phrases should be consistent. I have made those changes as well in both instances and definitions.

Let me know if there is something else to change.

**Comment by aarunku5** [comment]
Thanks!

729, 730, 731 look good.
732- Update the definition- '... one or more communities.'
733- Update the definition- 'A tweet targets only one community.'
734- Update the definition- typo 'is can be'

Update the readme- 731, 734 categories should be answer generation

**Comment by Pruthvi98** [comment]
hi @aarunku5, I have updated the files.

**Comment by aarunku5** [comment]
Thanks! @swarooprm all the tasks look good to me

**Comment by swarooprm** [comment]
Your HW2 is complete.

Would you like to submit the same tasks to our big project repo https://github.com/allenai/natural-instructions-expansion/pulls? You just need to fork that repo, rename tasks starting from the latest number in the repo (which at this point is 591) and create PR there. This way, you can be part of our research on "learning from instructions instead of learning from examples (conventional machine learning)". This is purely optional and your HW2 grade does not depend on this @Pruthvi98 ?

**Comment by swarooprm** [comment]
@Pruthvi98 Just a reminder that, if you plan to submit these tasks to the main Github repo and join our research project, Monday (27th Sept) is the deadline. Again, this is optional and independent of your HW2 grade.

**Pull request closed without merging**
