### PR TITLE
Complete: NLP Asignment2 - Task 585-590

### PR DESCRIPTION
**Pull request by Nikhitha0911**

### CODE REVIEW

**Comment by swarooprm** [comment]
@aarunku5, wondering if you can review this PR?

**Comment by aarunku5** [comment]
For all tasks, the source should be the web link to the dataset. Not the name of the dataset.

You need to update your task definitions, there are typos and grammatical errors. The definitions must be in full sentence format. Refer to the sample tasks you were given from SQUAD. You must specify exactly what the task is, define the terms in the task, specify what the output format is with an example if needed. Use Grammarly to bring the definitions to the standard required.

Please update the definitions, I'll review your examples after these definitions are clear.

**Comment by Nikhitha0911** [comment]
Added changes as per your suggestion and pushed it again

**Comment by aarunku5** [comment]
Update README to put the tasks in the correct order.

**585**
Update definition:
In this task, you are given a passage and a query about the interaction between two entities mentioned in the passage. The query provides information on one of the entities involved in the interaction. Your goal is to determine the other entity involved in the interaction. The correct answer has to be inferred by combining information from a chain of reactions mentioned in the passage.
Update Explanations:
P1: Based on the supporting passage it is clear that DB000773 is interacting with DB00072, hence this is a good example.
P2: Based on the supporting passage it is clear that DB09079 is interacting with DB06822, hence this is a good example.
N1: This is a bad example because the entity in the answer is the one that is also given in the question, and it will therefore not interact with itself.
N2: This is a bad example as the answer is not even present in the given context

**586**
Category: Classification (update in the readme as well, change the task name: task586_qangaroo_classification)
Change the summary in the readme to say that you are choosing from options and not generating
Update Definition:
In this task, you are given a passage, a query about the interaction between two entities mentioned in the passage, and a list of entities as answer options. The query provides information on one of the entities involved in the interaction. Your goal is to choose the other entity involved in the interaction from the options provided. The correct answer has to be inferred by combining information from a chain of reactions mentioned in the passage. Indicate your choice with the number of the option you choose. For instance, if the answer is '3. DB30411', the output should be '3'.
Update Explanations:
P1: The chosen answer is correct as it is the interacting entity for the given entity from the passage
P2: The chosen answer is correct as it is the interacting entity for the given entity from the passage
N1: The chosen answer is incorrect as it not is the interacting entity for the given entity from the passage
N2: The chosen answer is incorrect as it not is the interacting entity for the given entity from the passage

**587**
Update Definition:
Given a sentence in the English language, translate it into the Nepali language.
 _(The language here isn't neen. In the hugging face link, they have specified that samples with nepali-english, i.e., ne-en translations are marked as 'neen'.)_
Update Explanations:
P1, P2: The translation from English to Nepali is correct
N1, N2: The translation from English to Nepali is incorrect

**589**
Update Definition:
In this task, you will be given text in English. You need to translate the text into the Sinhali language.
Update Explanations:
P1, P2: The translation from English to Sinhala is correct.
N1, N2: The translation from English to Sinhala is incorrect.

**588**
Update Definition:
Given a text passage, you need to generate a suitable title as the output. The output title should be one of the words/phrases used in the passage and must be no longer than five words.
 Update Explanations:
Correct your explanations to include proper capitalization, punctuation, and grammar as specified for previous tasks.

**590**
Correct your task definition and explanations to include proper capitalization, punctuation, and grammar as specified for previous tasks.

**591**
Modify the definition and explanations similar to what was specified for task 589

**Comment by aarunku5** [comment]
Thanks, some minor edits left.

**585**
The explanation for N1 has a typo 'tThis'

**586**
Change N1, N2 explanations slightly- "...it is not the interacting..."
In the README, 'Choosing' should be capitalized, task 586 category is classification.

**588**
In P2's explanation, there is an extra period at the end.

**590**
Modify Definition: "Your answer should fit the blank appropriately."
Explanation P1: Make it use the same language as the explanation for P2.

**587, 589, 591 looks good**

**Comment by Nikhitha0911** [comment]
Thank you
Changed 585,586,588,590

**Comment by aarunku5** [comment]
Should have been more clear about 590- Revert back to the definition you had before. Change only the last sentence's beginning to be "Your answer should fit the blank appropriately..."
In P1- missing 'The' at the start of the second sentence

Rest look good

**Comment by Nikhitha0911** [comment]
Done

**Comment by Nikhitha0911** [comment]
let me know if anything else i need to modify

**Comment by aarunku5** [comment]
Thanks, all the tasks look good 👍 @swarooprm

**Comment by swarooprm** [comment]
Your HW2 is complete.

Would you like to submit the same tasks to our big project repo https://github.com/allenai/natural-instructions-expansion/pulls? You just need to fork that repo, rename tasks starting from the latest number in the repo (which at this point is 591) and create PR there. This way, you can be part of our research on "learning from instructions instead of learning from examples (conventional machine learning)". This is purely optional and your HW2 grade does not depend on this @Nikhitha0911 ?

**Comment by Nikhitha0911** [comment]
sure, i would like to submit this to your repo @swarooprm

**Comment by swarooprm** [comment]
> sure, i would like to submit this to your repo @swarooprm

Thanks :)

**Pull request closed without merging**
