### PR TITLE
Shailaja: Task 385-392: DART, ajgt_twitter_ar, youtube_caption_corrections

### PR DESCRIPTION
**Pull request by RushangKaria**
Task 385-392: Rushang Karia, ASU# 1206337661.

Tasks
=====
* DART
  - Question Generation
  - Sentence Similarity Classification
  - Text Generation
  - Relationship Extraction
  - Subject/Predicate/Object Identification
* ajgt_twitter_ar
  - Sentiment Classification
* youtube_captions_corrections
  - Grammar Correction
  - Incorrect Grammar Classification
  - Slot Filling
  - Slot Generation

Reproducibility/Additional Generation
=============================
For jupyter notebooks, please contact the author.

### CODE REVIEW

**Comment by swarooprm** [comment]
@shailaja183, wondering if you can help review this PR?

**Comment by shailaja183** [comment]
@RushangKaria
Since you created more than 4 tasks, ask @swaroop to give you unused task ids. You will have to rename them. 

385
===
a:
- update definition to incorporate following; 
1. if 2 or more triplets are given in input, fill-in-the-blank question should use at lease one triplet/all of them
2. ideally question should have maximum x number of blanks (because in negative example you say that question with too many blanks is bad) -- or say that from triplet, at least one/two entries from subject/object/verb should be included in the question
3. Specify when a question can have multiple fill-in-the-blanks (is one blank for one word/phrase/..?)

b:
- "how similar two sentences are based on the relationships in each sentence." is too vague. Just say whether or not two sentences are similar.
- from your positive example explanation, you should add relation of [subject, predicate, object] structure with the similarity in the description i.e. two sentences are similar/dissimilar if they have same/different triplet [subject, predicate, object] structure
 
c: (not sure if this can be considered a separate task from a) @swarooprm needs to decide this.
specify in definition: if 2 or more triplets are given in input, fill-in-the-blank question should use at lease one triplet/all of them

d/e/f/g: task categories would be 'token classification' @swarooprm verify

d:
specify in definition: if a given sentence can generate 2 or more triplets, the output must contain all of them (based on your instances). Not sure if the task should be to generate exactly one triplet @swarooprm tell him what format you would like in the final version

e/f/g:
add more details in the definition about: what a subject/predicate/object is, how to identify it, in case there are multiple tokens for a subject/predicate/object what should be done 

many instances dont look right to me ex. (from task e)
        {
            "input": "The record set by Elzbieta Urbanczik was 3:52.983s.",
            "output": [
                "3:52.983s"
            ]
        },
        {
            "input": "In 1951, The Married Couple was released.",
            "output": [
                "1951"
            ]
        },
clearly outputs do not represent subject it seems. Justify

f: 
typo in definition "the subject of" -> "the predicate of"

g:
typo in definition "the subject of" -> "the object of"

386a:
add more details in definition about when a sentiment is positive and negative. 

387a:
- Not sure what do you mean by "Grammar Correction" task (it does not seem to involve any spelling fixes, tense or sentence structure related fixes that user can do) Seems more like making the text case-sensitive. @swarooprm
 
[update: from 387b, I saw that your input sentences can have following errors and need to be fixed-
CASE_DIFF (case error), PUNCUATION_DIFF (punctuation error), CASE_AND_PUNCUATION_DIFF (both case and punctuation error), STEM_BASED_DIFF (stem word error), DIGIT_DIFF (digit error), INTRAWORD_PUNC_DIFF (intra-word punctuation error), UNKNOWN_TYPE_DIFF (unknown error), RESERVED_DIFF (special error)
rewrite your definition of this task based on above possible errors. 

- in definition, add that -- text should be uppercased/lowercased as per necessity (beginning of the sentence, proper nouns, ...), numbers should be normalized (6 as six and so on)
- explanations are not informative (too generic) for negative samples, rewrite where exactly the error is and why it is incorrect, what should be the correct output

387b:
- explanations are not informative (too generic) for negative samples, rewrite where exactly the error is and why it is incorrect, what should be the correct output

387d:
I dont see a need of this task as it is already done in 387a and 387b
(you can remove this task or modify to make it a novel task)

**Comment by RushangKaria** [comment]
Thanks for the detailed feedback @shailaja183. Is there any deadline as to when the new changes need to be pushed in?

**Comment by RushangKaria** [comment]
@shailaja183 I'll get the updates done by the weekend. If there is a hard deadline that falls earlier please do let me know :)

**Comment by shailaja183** [comment]
Try to do it by Saturday so I can do another round of review by weekend.

**Comment by RushangKaria** [comment]
Awesome. Thank you. It might be a bit difficult to get all changes made by Saturday evening, but I'll try my best.

**Comment by swarooprm** [comment]
I need to release grades by Tuesday. @shailaja183 can iterate and review multiple times before then.

**Comment by RushangKaria** [comment]
@shailaja183 i made the changes requested.

Removed task 387d.

Regarding, the incorrect instances from task385e

> many instances dont look right to me ex. (from task e)
{
"input": "The record set by Elzbieta Urbanczik was 3:52.983s.",
"output": [
"3:52.983s"

I am not sure since I double-checked in the data set and it does appear that the subject is indeed 3:52:983s. The whole triplet was
image

If the dataset itself is incorrect in such cases there is not much I can do in these cases. Although it does appear that the subject is the time in this case.

**Comment by shailaja183** [comment]
Final check- Looks good to me!

**Comment by RushangKaria** [comment]
Thank you @shailaja183 :)

Was a fun project!

**Comment by swarooprm** [comment]
Great, Your HW2 is complete now.

Would you like to submit the same tasks to our big project repo https://github.com/allenai/natural-instructions-expansion/pulls? You just need to fork that repo, rename tasks starting from the latest number in the repo and create PR there. This way, you can be part of our research on "learning from instructions instead of learning from examples (conventional machine learning)". This is purely optional and your HW2 grade does not depend on this @RushangKaria

**Comment by RushangKaria** [comment]
Hi @swarooprm, 

Yes, I'd be happy to contribute to the big repo. Since that would be more large scale here are a couple questions I had.

1. I used Google/Wikipedia/Merriam to fill in some definitions like (what constitutes a subject). They are general sources and Im not sure if a citation is required.
2. For the youtube task, the input in the dataset consists of the captions for the entire video. However, for generating instances I just stripped out the first 25-50 words. I have code to regenerate the instances as desired.
3. Finally, for DART, to simplify a few tasks, I considered simpler variants such as only 1 triplet present for slot generation etc. I can change these if needed as well.

If there is a document in the repo that details general guidelines, I can slowly refine these tasks and push them in a more polished fashion. Also, in the repo you linked, I don't see any place to park the source code that was used to create the tasks. The src/ directory might be a good fit but not sure if thats acceptable.

**Comment by swarooprm** [comment]
Good question! Please add all your references to the source fields of your json. Everything else is ok at this point to submit. I think you can submit your tasks at its current form to the repo and based on the feedback you receive there, you might need to change some of the things which you have mentioned.

Submitting code is optional. However, you can do that. Here's how a contributor has shared code for others to use https://github.com/allenai/natural-instructions-expansion/issues/154.

Please let me know if you have any other questions.

**Pull request closed without merging**
