### PR TITLE
Mehrad: Task 241- 245 Inquisitive, PROST

### PR DESCRIPTION
**Pull request by ashutosh1608**
Hi,
I am adding five tasks. @admin Can you approve it?

Thanking you.

### CODE REVIEW

**Comment by swarooprm** [comment]
@Mehrad0711, wondering if you can help review this PR?

**Comment by Mehrad0711** [comment]
1. Please add a link to the dataset/ repo in "Source" field of each task file.
2. Rename "task241_inquisitive_inquisitive_question_generation.json" file to "task241_inquisitive_question_generation.json"
3. In all tasks I think it would be better to replace "\n" with a non-escaping character to avoid unwanted line splits when reading the file. Perhaps a special token like `<sep>` which can be added to the tokenizer special vocab list.
4. I think we can improve task definitions. I suggest the following:
    - tasks/task241_inquisitive_inquisitive_question_generation.json: `The task is to generate an inquisitive question about a specific text span in a given sentence. A question is considered inquisitive when (1) it's about a specific text span in the sentence (2) the answer is not in the original sentence.`
    - tasks/task245_inquisitive_span_detection.json: `The task is to detect a text span in the passage about which an inquisitive question is asked. A question is considered inquisitive when (1) it's about a specific text span in the sentence (2) the answer is not in the original sentence.`
    - tasks/task242_prost_question_generation.json: `This task is to formulate questions about the information explicitly mentioned in a given passage.`
    - tasks/task243_prost_mcq_generation.json and tasks/task244_prost_mcq_answers_generation.json: Please explain what MCQs are in the task definition.
5. The explanations can be simplified by removing "The above example is a (good | bad) example because"
6. In "task241_inquisitive_inquisitive_question_generation.json:" file: `sentence itself sentence.` --> `sentence itself`

**Comment by swarooprm** [comment]
@ashutosh1608, can you address reviewer comments so that I can evaluate?

**Comment by ashutosh1608** [comment]
Hi Swaroop, I'm on it but can you explain me the last review?

Thanks.

**Comment by ashutosh1608** [comment]
> @ashutosh1608, can you address reviewer comments so that I can evaluate?

Hi Swaroop, I have addressed all the reviewer comments, you can go ahead and evaluate. Thanks.

**Comment by swarooprm** [comment]
@Mehrad0711, check if you are happy or have any other feedback?

**Comment by Mehrad0711** [comment]
Yeah, LGTM.

**Comment by swarooprm** [comment]
Your HW2 is complete now.

Would you like to submit the same tasks to our big project repo https://github.com/allenai/natural-instructions-expansion/pulls? You just need to fork that repo, rename tasks starting from the latest number in the repo and create PR there. This way, you can be part of our research on "learning from instructions instead of learning from examples (conventional machine learning)". This is purely optional and your HW2 grade does not depend on this @ashutosh1608

**Comment by ashutosh1608** [comment]
Sure thing, I'd like to be part of your research, I'll do as directed.

Thanks.

**Comment by swarooprm** [comment]
Great! Thanks.

**Comment by swarooprm** [comment]
@ashutosh1608 Just a reminder that, if you plan to submit these tasks to the main Github repo and join our research project, Monday (27th Sept) is the deadline. Again, this is optional and independent of your HW2 grade.

**Comment by ashutosh1608** [comment]
> @ashutosh1608 Just a reminder that, if you plan to submit these tasks to the main Github repo and join our research project, Monday (27th Sept) is the deadline. Again, this is optional and independent of your HW2 grade.

Hi Swaroop, I have raised the PR for the tasks. It is waiting for approval from a reviewer. Thanks.

**Pull request closed without merging**
