### PR TITLE
Mihir: Tasks 521-524 EURLEX,YELP and ARITHMETIC

### PR DESCRIPTION
**Pull request by RaghulRajM**
YELP Classification samples: ["Positive":544,"Negative":492]
EURLEX Classification samples: ["Regulation":370,"Directive":240,"Decision":370]

### CODE REVIEW

**Comment by swarooprm** [comment]
@Mihir3009, wondering if you can help review these tasks?

**Comment by Mihir3009** [comment]
Are you saying in the pull request that there are 521-528, but when I opened your branch, there are 521-524 only? Can you check, please?

Reviews for the tasks that are there in the branch:

Task 522:

1. Describe what each category means in the definition.

Task 523:

1. Update the definition and describe that what possible arithmetic operations you need to do to get answers. Describe all of them that are used in this dataset.

-> Save all JSON files using the below command:

`json.dumps(your_json_string, indent=4, ensure_ascii=False)`

**Update Readme**

Task 521: Generate headline (summary) for legal act article
Task 522: Identify the legal act article whether it is Regulation, Decision or Directive
Task 523: Given an arithmetic question, compute a solution
Task 524: Restaurant review classification based on its sentiment (i.e., positive or negative).

**Comment by swarooprm** [comment]
@RaghulRajM, can you address reviewer comments so that I can evaluate?

**Comment by RaghulRajM** [comment]
Hi @Mihir3009 @swarooprm ,
I've only 4 tasks. I named it that way because of the task slots allotted to me.
I'll make the suggested changes by today. Thanks for reviewing!

**Comment by Mihir3009** [comment]
Cool. Make changes and let me know. I will review again.

**Comment by RaghulRajM** [comment]
> Cool. Make changes and let me know. I will review again.

Hi @Mihir3009 I'm done with the changes. Please let me know if there's anything else I have to do. Thank you.

**Comment by Mihir3009** [comment]
@RaghulRajM Please delete ".DS_Store" file from your branch.

**Comment by RaghulRajM** [comment]
@Mihir3009 It's done.

**Comment by Mihir3009** [comment]
@swarooprm I am happy with @RaghulRajM's work. Looks good to me. I approve of this PR.

**Comment by swarooprm** [comment]
Your HW2 is complete now.

Would you like to submit the same tasks to our big project repo https://github.com/allenai/natural-instructions-expansion/pulls? You just need to fork that repo, rename tasks starting from the latest number in the repo and create PR there. This way, you can be part of our research on "learning from instructions instead of learning from examples (conventional machine learning)". This is purely optional and your HW2 grade does not depend on this @RaghulRajM

**Comment by RaghulRajM** [comment]
Sure! I can do that.

**Pull request closed without merging**
