### PR TITLE
Maitreya: task 817-820 Jfleg and Blimp Datasets

### PR DESCRIPTION
**Pull request by jreyes4**

### CODE REVIEW

**Comment by swarooprm** [comment]
@Maitreyapatel, wondering if you can help review these tasks?

**Review by Maitreyapatel — CHANGES_REQUESTED** [review]
1. Please add the source dataset name inside task file along with the link.
2. Task 817-818: Looks good.
3.  Task 819: Definition is good just modify slightly that it becomes clear. Like, classify good as \"good\" is redundant. For example, "If representation of the adjunct island is correct then denote it as \"good\". Otherwise give \"bad\" as output." And define what is good/bad representation.
4. Task 819: Positive Examples doesn't mean you need to give only good class examples. You need to give both class as examples and state why their classification is correct. For negative examples, you need to give few examples where answer is wrong. And explain why they are wrong and what is correct answer.
5. Task 820: I have same comments as tasl819. You need to write clear definition. Explain what is anaphor number agreement. No need to state the dataset name.

These are few minor and quick required changes. Rest of the things looks good.

**Comment by jreyes4** [comment]
Updates made

**Review by Maitreyapatel — COMMENTED** [review]
Just one question and one suggestion:
1. Task819-820: I think, your negative examples are wrongly written. The "bad" class is the correct answer based on the your explanations. But they are in the negative set of examples. Please recheck them.
2. For these classification task, what is data imbalance? If "good" and "bad" class instances are not balance then make them (like make them ~ 1:1). 

Everything else looks good to me. Make these changes and your homework is done.

**Comment by swarooprm** [comment]
@jreyes4, can you address reviewer comments so that I can evaluate your HW?

**Comment by jreyes4** [comment]
Apologies, I'm wrapping up another project. I'll have the updates finished and pushed to the PR later tonight.

**Comment by jreyes4** [comment]
1. For tasks 819 and 820 I've updated the negative set of examples to incorrectly identify the feature that's being tested. 

While doing so, I noticed that there was a bug in my code that combined the instances from 819 and 820. The bug put the combined instances into each of the instances of the 2 tasks. I've corrected this. Note, this bug only affected tasks 819 and 820.

2. After fixing my code so that each set of instances belonged to only one of the features for each task, the distribution is correctly 1:1 for both 819 and 820. For both tasks, there are 1000 instances and they are divided evenly with 500 good and 500 bad. The results are shuffled. 

Let me know if you have any further doubts or if I should clarify something. 

Thanks

**Comment by swarooprm** [comment]
Your HW2 is complete now.

Would you like to submit the same tasks to our big project repo https://github.com/allenai/natural-instructions-expansion/pulls? You just need to fork that repo, rename tasks starting from the latest number in the repo and create PR there. This way, you can be part of our research on "learning from instructions instead of learning from examples (conventional machine learning)". This is purely optional and your HW2 grade does not depend on this @jreyes4

**Comment by swarooprm** [comment]
@jreyes4 Just a reminder that, if you plan to submit these tasks to the main Github repo and join our research project, Monday (27th Sept) is the deadline. Again, this is optional and independent of your HW2 grade.

**Pull request closed without merging**
