### PR TITLE
Shailaja: Tasks 209-212: HIPPOCAMPUS and conv_ai_2

### PR DESCRIPTION
**Pull request by NeilFranks**
Name : Neil Franks
ASUID : 1209129086

datasets: https://msropendata.com/datasets/0a83fb6f-a759-4a17-aaa2-fbac84577318, https://huggingface.co/datasets/conv_ai_2

Add one Long-Text Generation task, and three unique Classification tasks.

### CODE REVIEW

**Comment by NeilFranks** [comment]
I believe I'm ready for review

**Comment by swarooprm** [comment]
@shailaja183, wondering if you can help in reviewing this task?

**Comment by shailaja183** [comment]
Good job! just few minor fixes is required;

General Comments:
1. Have a single entry in source if based on a single dataset (merge "HIPPOCORPUS" and "https://msropendata.com/datasets/0a83fb6f-a759-4a17-aaa2-fbac84577318")
2. Most definitions look good, I would however suggest to break down sentences, simplify and do not repeat any instructions. 
3. Do not simply copy paste instructions from the crowd-sourcing template. Write in your own words. 
4. remove 'a' in 'a correct classification', 'a misclassification' etc.

task209 
Typo "eaxmple" - positive example 2
positive example 2, negative example 2 - output missing some escape character

task210 
Definition, positive examples input, negative examples input - missing some escape character
"classifying it as one that was either" -- "classifying it as x, y or z"
avoid repetition -- last line "You should read each story and classify whether you think it is imagined, recalled, or retold."
rewrite -- "Some things that should have tipped you off that this is"
typo "mis-classification"
do not say "Researchers say ..", use "As per definition"

task212
positive example 2 typo "repitition"
negative example 1 typo "interpretted"

**Comment by NeilFranks** [comment]
> Good job! just few minor fixes is required;
> 
> General Comments:
> 
> 1. Have a single entry in source if based on a single dataset (merge "HIPPOCORPUS" and "https://msropendata.com/datasets/0a83fb6f-a759-4a17-aaa2-fbac84577318")
> 2. Most definitions look good, I would however suggest to break down sentences, simplify and do not repeat any instructions.
> 3. Do not simply copy paste instructions from the crowd-sourcing template. Write in your own words.
> 4. remove 'a' in 'a correct classification', 'a misclassification' etc.
> 
> task209
> Typo "eaxmple" - positive example 2
> positive example 2, negative example 2 - output missing some escape character
> 
> task210
> Definition, positive examples input, negative examples input - missing some escape character
> "classifying it as one that was either" -- "classifying it as x, y or z"
> avoid repetition -- last line "You should read each story and classify whether you think it is imagined, recalled, or retold."
> rewrite -- "Some things that should have tipped you off that this is"
> typo "mis-classification"
> do not say "Researchers say ..", use "As per definition"
> 
> task212
> positive example 2 typo "repitition"
> negative example 1 typo "interpretted"

Hi @shailaja183, I think I took care of everything, but I'm not sure about `3. Do not simply copy paste instructions from the crowd-sourcing template. Write in your own words.` and `missing some escape character` instructions. Can you help me understand what/where the escape character should be? I think it may have had something to do with errant whitespace in the text? Also, I'm not sure which instructions look to be copy/pasted from the crowd-sourcing template; I did write it in my own words but maybe I accidentally used the same wording? I'm not even sure which template you mean, I figured it was this one https://storage.googleapis.com/ai2-michalg/obqav2-one-brain-20190415-163709/index.html?fact1=Metal%20conducts%20electricity but I'm not sure what that template and mine have in common, please let me know if I'm just overlooking something!

**Comment by NeilFranks** [comment]
@shailaja183 @aarunku5 @kuntalkumarpal @nrjvarshney, any indication that my changes are acceptable?

**Comment by NeilFranks** [comment]
@swarooprm sorry to bother but any chance i can get confirmation on this before midnight?

**Comment by NeilFranks** [comment]
> @shailaja183 @aarunku5 @kuntalkumarpal @nrjvarshney, any indication that my changes are acceptable?

@shailaja183 @aarunku5 @kuntalkumarpal @nrjvarshney re-upping hoping for reply before midnight. Thanks in advance, i know youve been busy!

**Comment by shailaja183** [comment]
There were no significant issues with your submission, good to go for today's deadline. Will do another round of review later.

**Comment by NeilFranks** [comment]
@shailaja183 woo! Thank you so much! Have a good night!

**Comment by swarooprm** [comment]
@shailaja183, let me know if you are happy or have any other feedback?

**Comment by swarooprm** [comment]
Your HW2 is complete now.

Would you like to submit the same tasks to our big project repo https://github.com/allenai/natural-instructions-expansion/pulls? You just need to fork that repo, rename tasks starting from the latest number in the repo and create PR there. This way, you can be part of our research on "learning from instructions instead of learning from examples (conventional machine learning)". This is purely optional and your HW2 grade does not depend on this @NeilFranks

**Comment by swarooprm** [comment]
@NeilFranks  Just a reminder that, if you plan to submit these tasks to the main Github repo and join our research project, Monday (27th Sept) is the deadline. Again, this is optional and independent of your HW2 grade.

**Comment by NeilFranks** [comment]
> @NeilFranks Just a reminder that, if you plan to submit these tasks to the main Github repo and join our research project, Monday (27th Sept) is the deadline. Again, this is optional and independent of your HW2 grade.

Submitted https://github.com/allenai/natural-instructions-expansion/pull/330

**Pull request closed without merging**
