### PR TITLE
Complete Task 377-382: air_dialog and curiosity_dialog

### PR DESCRIPTION
**Pull request by jayavardhan3112**

### CODE REVIEW

**Comment by swarooprm** [comment]
@Palipoor, wondering if you can help review these tasks?

**Comment by Palipoor** [comment]
Hi, please remove the underline from task names. Like: `task_379_air_dialogue_classification` -> `task379_air_dialogue_classification`
In the definition of task 377, this sentence doesn't make sense: `Find if the expected status by the end of the conversation.`.
Also, it seems like the definition is talking about "positive" which is not a label, can you re-write the description to be more informative? Also describe labels change and cancel. 
In task 388:
There're some typos and grammatical errors in the description. Please re-read it or replace it with this:

`In this task, you're given a dialogue between a customer and a flight booking agent with a gap in the conversation. Your job is to find the answer of the previous dialogue. Avoid using irrelevant extra information while creating the answer. The answer should be relevant to the question before the blank. If you fill the blank with a question, it should have an answer from the agent in the given dialogue. Fill the gap marked with underline.`

**Comment by Palipoor** [comment]
Please re-write the definition of task `task_379_air_dialogue_classification`. It doesn't explain the task.

**Comment by Palipoor** [comment]
It would be better if you put tasks from each dataset in a different pull request.
The description of `task_380_curiosity_dialogs_answer_generation` is not clear, please rewrite it.
In task `task_381_curiosity_dialogs_classification`, please change the outputs to be "user" and "assistant" instead of numbers.

**Comment by jayavardhan3112** [comment]
@Palipoor I have resolved all the comments, could you please check , Thank you in advance.

**Comment by Palipoor** [comment]
Looks good to me! Thanks!

**Comment by swarooprm** [comment]
Your HW2 is complete now.
I see you have created PR in the Allen AI repo. Please rename your PRs based on my comment in that repo. Also, feel free to create more tasks in that repo if you want to be a co-author in our paper.

**Comment by jayavardhan3112** [comment]
> Your HW2 is complete now.
> I see you have created PR in the Allen AI repo. Please rename your PRs based on my comment in that repo. Also, feel free to create more tasks in that repo if you want to be a co-author in our paper.

Sure @swarooprm . I am creating  a few more tasks to push into the allenai repo, thanks 💯

**Pull request closed without merging**
