### PR TITLE
Task 287-309 Phase 1

### PR DESCRIPTION
**Pull request by abhinawale12**

### CODE REVIEW

**Comment by Ravsehajsinghpuri** [comment]
@abhinawale12  1) Can you add the original tasks in this PR. 2) Can you rename the task variants as taskxxx.1_yyyy, taskxxx.2_yyyy, taskxxx.3_yyyy and so on. For e.g. task547.1_spl_translation_entk_en.json, task547.2_spl_translation_entk_en.json, task547.3_spl_translation_entk_en.json and so on. Do this for all the tasks in this PR 3) Can you resolve the conflicts

**Comment by Ravsehajsinghpuri** [comment]
@abhinawale12 Can you resolve the conflicts?

**Comment by Ravsehajsinghpuri** [comment]
@abhinawale12 Quick question - Are the tasks added in this PR, already part of the phase 2 whose PR has been merged? Pls confirm because then you can close this PR as the tasks have already been merged

**Comment by abhinawale12** [comment]
> @abhinawale12 Quick question - Are the tasks added in this PR, already part of the phase 2 whose PR has been merged? Pls confirm because then you can close this PR as the tasks have already been merged

No. The tasks in this PR are different than the one in phase 2 PR

**Comment by Ravsehajsinghpuri** [comment]
> > @abhinawale12 Quick question - Are the tasks added in this PR, already part of the phase 2 whose PR has been merged? Pls confirm because then you can close this PR as the tasks have already been merged
> 
> No. The tasks in this PR are different than the one in phase 2 PR

Can you rename these tasks, as the tasks with the same name have been merged, so rename the tasks in this PR, thanks!

**Comment by abhinawale12** [comment]
> > > @abhinawale12 Quick question - Are the tasks added in this PR, already part of the phase 2 whose PR has been merged? Pls confirm because then you can close this PR as the tasks have already been merged
> > 
> > 
> > No. The tasks in this PR are different than the one in phase 2 PR
> 
> Can you rename these tasks, as the tasks with the same name have been merged, so rename the task variant number in this PR, thanks!

@Ravsehajsinghpuri I have renamed the tasks. Could you please take a look and let me know if anything needs to be updated. Thank you.

**Comment by Ravsehajsinghpuri** [comment]
> > > > @abhinawale12 Quick question - Are the tasks added in this PR, already part of the phase 2 whose PR has been merged? Pls confirm because then you can close this PR as the tasks have already been merged
> > > 
> > > 
> > > No. The tasks in this PR are different than the one in phase 2 PR
> > 
> > 
> > Can you rename these tasks, as the tasks with the same name have been merged, so rename the task variant number in this PR, thanks!
> 
> @Ravsehajsinghpuri I have renamed the tasks. Could you please take a look and let me know if anything needs to be updated. Thank you.

LGTM, thanks!

**Pull request merged**
