### PR TITLE
Complete: Swaroop: Tasks657-660-mkb-gooaq

### PR DESCRIPTION
**Pull request by Nikhil-Chandra-Nirukonda**

### CODE REVIEW

**Comment by swarooprm** [comment]
@shailaja183, wondering if you can help review this PR?

**Comment by swarooprm** [comment]
@kurbster, can you help review this PR?

**Comment by swarooprm** [comment]
@nrjvarshney, can you help review these tasks?

**Comment by swarooprm** [comment]
@nrjvarshney, can you help review these tasks?

**Comment by nrjvarshney** [comment]
* Input_language, output_language fields are missing
* output is not readable "\u092e\u0947\u0930\u0947 \u092a\u094d\u092f\u093e\u0930\u0947 \u0926\u0947\u0936\u0935\u093e\u093".
* Please confirm how the non-english characters need to be written.


Task 659 -
* "question: " prefix is not required
* Just keep the answer in the output without units. 
* In the explanation, explain using the conversion formula
* rectify the typos: "1 000" should be "1000"
* You have something else in the instances. Please check 
```
{
            "input": "0800 da natura do brasil?",
            "output": [
                "1 (720) 408-2293"
            ]
        },
        {
            "input": "0800 da unilever do brasil?",
            "output": [
                "1 (800) 298-5018"
            ]
        },
```
Task 660
* "id" is not required in the input
* Simplify the definition. "create a numerical reasoning question from the given passage". or whatever the description of the task is
* rectify the typos.
* Examples and instances should not have overlap.
*

**Comment by Nikhil-Chandra-Nirukonda** [comment]
Hi Neeraj,

For Task 657 & 658 
1) As I have already mentioned the input and output language in the definition itself, I did not include it again in the input or output fields.
2)If I am encoding the values to make it readable, it is failing the test program. So, I have not encoded the values and submitted as it is.
3)The non-english characters need to be encoded in UTF-8 to make them readable.

For Task 659
1)I have removed the question prefix as requested.
2)I have removed the units in output as requested.
3)I have changed the explanation as mentioned.
4)I have rectified the typo error as requested.
5)The instances have been changed as per your request.

For Task 660
1)I have made the requested changes like removing id and only giving the answer as input.
2)I have simplified the definition as requested.
3)I have rectified the typos as mentioned.
4)I have removed the instances overlapping with examples.

**Comment by swarooprm** [comment]
@Nikhil-Chandra-Nirukonda, once you add your file to the readme, the tests should pass

**Comment by Nikhil-Chandra-Nirukonda** [comment]
> @Nikhil-Chandra-Nirukonda, once you add your file to the readme, the tests should pass

Hi Swaroop, I have updated the Readme. Please let me know if it's working fine now

**Comment by swarooprm** [comment]
@nrjvarshney, check if you are happy or have any other feedback?

**Comment by nrjvarshney** [comment]
* Add the input_language and output_language as separate fields in the JSON
* remove the prefix from both input and output
* @swarooprm , see the output encoding. Do we want to keep it like that?

**Comment by Nikhil-Chandra-Nirukonda** [comment]
Hi, Swaroop and Neeraj, I was wondering If I can close the pull request now

**Comment by swarooprm** [comment]
@Nikhil-Chandra-Nirukonda :
Looks good. 2 minor changes.

- Your data does not contain 'id' and 'answer', but explanations contain reference to those- update explanations.
- Use utf-8 encoding while creating json so that they are readable.

Your HW will be complete once you do these.

**Comment by Nikhil-Chandra-Nirukonda** [comment]
Hi Swaroop, I have made the changes requested in explanation.
But, I am unable to make changes for the encoding issue, as I have done the encoding for json file and it is showing the translations perfectly, but the json file is not passing the test cases. I have uploaded images of what issue I am facing, Can I get any help.
Instances for task 657
Error for task 657

**Comment by Nikhil-Chandra-Nirukonda** [comment]
Hi Swaroop, can we talk over a zoom meeting if possible. As, I would like to clarify some doubts regarding these tasks, especially the encoding part and then we can close this pull request.

**Comment by Nikhil-Chandra-Nirukonda** [comment]
Hi Swaroop, I wonder if you are available for 10-15 mins. I would like to complete the changes and close the pull request after going through the encoding problem, if you are available right now

**Comment by Nikhil-Chandra-Nirukonda** [comment]
Hi Swaroop, Can I get a little help as I am unable to understand where the commit is going wrong

**Comment by swarooprm** [comment]
Your HW2 is complete now.

Would you like to submit the same tasks to our big project repo https://github.com/allenai/natural-instructions-expansion/pulls? You just need to fork that repo, rename tasks starting from the latest number in the repo and create PR there. This way, you can be part of our research on "learning from instructions instead of learning from examples (conventional machine learning)". This is purely optional and your HW2 grade does not depend on this @Nikhil-Chandra-Nirukonda

**Comment by Nikhil-Chandra-Nirukonda** [comment]
Ok Thanks for all the help you provided, Swaroop
With Regards
NIKHIL CHANDRA NIRUKONDA

**Pull request closed without merging**
