### PR TITLE
Mirali Task 289 - 296: Scitail and Daily Dailog Datasets

### PR DESCRIPTION
**Pull request by gksriharsha**

### CODE REVIEW

**Comment by swarooprm** [comment]
@Mirzyaaliii, wondering if you help review these tasks?

**Comment by Mirzyaaliii** [comment]
- General Comments -

1. Change the name of the files and keep the unique name for each. For example
task291_daily_dialog_conversation_type_classification
task292_daily_dialog_conversation_emotion_classification
For more, check tasks 137-140 [here](https://github.com/allenai/natural-instructions-expansion/tree/master/tasks).
2. Modify definitions of all the tasks, hence, it sounds concise, clear and do not have any repetitive part. (Also, provided few suggestions below)

- Task-289
1. Separate the different entities by \n. For example
`Premise: Lyme Disease is caused by a bacterium that's transmitted by tick bite, but many infected people don't remember a bite. \n Hypothesis: Lyme disease is caused by bacteria.`
2. Modify the definition, hence, it becomes concise and clear. Make some changes as follows:
i) You are given with two sentences. **->** You are given two sentences.
ii) You have to find if there is entailment/agreement of the Hypothesis by the Premise. **->** You have to find if there is entailment or agreement of the Hypothesis by the Premise.
iii) The Premise should not exactly be the same as Hypothesis. **->** The Premise may not exactly be the same as Hypothesis.
iv) The output of this task is either 'entails' for premise supporting the hypothesis or 'neutral' for non-supporting premise. -> Your task is to return 'entails' if the premise supports the hypothesis else return 'neutral'

- Task-290
1. In the README, change the category from text generation to Sentence Generation.
2. Remove the last line from the definition, it does not help to generate the output.
3. Instead of writing a former statement and another statement, write an **input** sentence and **output**. 

- Task-291
1. Keep only one category, and change accordingly in the name of the file.
2. In the output return name of the class only instead of 0-4 and change the definition and README accordingly. Check Task-212 [here](https://github.com/allenai/natural-instructions-expansion/tree/master/tasks).
3. There are 5 classes for the output and mentioned 6 in the README, correct it.

- Task-292
1. In the input instead of separate it by four spaces, make something like
`Person1 - Hey man , you wanna buy some weed ?  \n Person2 - Some what ? \n ......`
or write Speaker1 or anything and change accordingly in the definition.
(Apply this change to Task-293, 294, 296)
2. In the output also, write emotions directly (do change same as Task-291). 
3.  In the explanation, for few emotions explain why it represents that specific emotion and cover all 6 emotions across 3 positive examples.
4. Change the summary in the README, such as
`Classify the conversation sentences of input passage into the following emotions: anger, disgust, fear, happiness, sadness.`
(Apply this change to Task-291, 293)

- Task-295
1. In the definition, change something like this
`You are given a conversation and you have to classify if there exist more than 2 unique emotions in the entire conversation.`
2. In the explanation of the first 2 positive examples, elaborate more on why it is 0 or 1.

- Task-296
1. Modify the definition, it sounds confusing. If there is happened emotion exist then it should classify as 1 or for any other positive emotion. And if there is only 1 positive emotion across all the data mention that in the definition only.

**Comment by gksriharsha** [comment]
@Mirzyaaliii  Thank you very much for reviewing my submission. I have made all the required changes to the submission.

**Comment by Mirzyaaliii** [comment]
1. Complete each sentence by **.** in the explanation and definition. (Check this in all tasks)

- Task - 289
1. Keep space between these 3
_**... \n Hypothesis: ...**_

- Task - 290:
1. Change the category from Text Generation to Sentence Generation inside the file.

- Task - 291
1. In the README, one class is missing from the summary.
2. Keep only one category inside the file.

- Task - 292
1. In the instances, write all the emotions in the string only as below:
```
"output": [
            "sadness, surprise, No emotion, No emotion, No emotion, happiness, No emotion, happiness, No emotion"
]
```
2. Write person1 like this _Person1_ instead of _Person 1_. (Change this Task-293 also.)
3. Chnage this line
`You are required to label each of the sentence present in the conversation with the detected emotion.`
to
`Your task is to label each of the continuous conversations done by one speaker with the emotion detected in that particular part.` (Change this Task-293 also.)
The above one makes more sense because we are labeling each and every sentence. The task is to label one continuous conversation done by one speaker.

- Task - 293
1. Correct the definition according to change
`You are given a conversation between two people where the responses are seperated with four spaces.`
(Change this Task-294 also.)

- Task - 295
1. In the input instead of separate it by four spaces, make something like
`Person1 - Hey man , you wanna buy some weed ?  \n Person2 - Some what ? \n ......`
or write Speaker1 or anything and change accordingly in the definition.
(Change this Task-296 also.)

- Task - 296
1. Change the definition from
`You are given a conversation between two people. You are required to classify if the sentences in the conversation either convey 'No emotion' or 'happiness' as 1 else as '0' "`
to
`You are given a conversation between two people separated by \n. Your task is to classify the conversation either convey \*No emotion\* or \*Happiness\* by providing \*1\* and \*0\*, respectively.` (Change this to all the tasks which contain conversation)

**Comment by gksriharsha** [comment]
@Mirzyaaliii  I have tried to use \* \* instead of ' ' as mentioned in Task 296. While parsing the JSON it is throwing 

```
json.decoder.JSONDecodeError: Invalid \escape: line 11 column 357 (char 528)
```

Please advice what character to use.

**Comment by swarooprm** [comment]
@gksriharsha, 
Since you are getting Json decode error, you can use ' ' instead of **. However, let @Mirzyaaliii know once you address all reviewer comments so that she can take a look

**Comment by Mirzyaaliii** [comment]
- General comments

1. There are few grammatical errors in the explanations. So, please once pass this on the Grammarly (or a similar tool). Hence, there will be no grammatical, punctuation, spacing, etc errors.
- Task - 292
1. In the README, one class is missing from the summary.
- Task - 296
1. Correct this input (2nd positive example) according to task
`
{
     "input": "Person1:  Peter , listen to the lyrics of this song .      What's so special about this song ?      It's from the musical that is so popular in New York right now . Do you like it ?      Not very much . It sounds too emotional to me .      That's why it is so popular . It was recorded by Barbara Tutin . I've heard that when she sang this song on stage the opening night , she created quite a sensation .      I'm afraid my association with Broadway musicals is rather limited .      Well , then , you need an introduction . The school drama club is putting on a musical production . How about going together ?      I have a better idea . Let's go to a jazz concert and I'll give you an education in jazz . ",
    }`

**Comment by Mirzyaaliii** [comment]
All things look good to me, just a few minor comments -

- Keep the space before **\n**, because there is space somewhere and somewhere not. Keep space before and after **\n** in every task wherever it is.
- In Tasks 292-296, If possible extra tabs from the inputs
```
"input": " Person1:     Shall we buy ? \n Person2:     It really depends on you . \n Person1:      But if you were me ? \n Person2:    If I were you , I'd buy . "
```

**Comment by swarooprm** [comment]
Your HW2 is complete now.

Would you like to submit the same tasks to our big project repo https://github.com/allenai/natural-instructions-expansion/pulls? You just need to fork that repo, rename tasks starting from the latest number in the repo and create PR there. This way, you can be part of our research on "learning from instructions instead of learning from examples (conventional machine learning)". This is purely optional and your HW2 grade does not depend on this @gksriharsha

**Comment by swarooprm** [comment]
@gksriharsha, Just a reminder that, if you plan to submit these tasks to the main Github repo and join our research project, Monday (27th Sept) is the deadline. Again, this is optional and independent of your HW2 grade.

**Pull request closed without merging**
