### PR TITLE
Kirby: Task 137-141 : CoQA Dataset, code_x_glue Dataset

### PR DESCRIPTION
**Pull request by ShashankDavalgi**

### CODE REVIEW

**Comment by swarooprm** [comment]
@ kurbster, wondering if you can help review these tasks?

**Comment by kurbster** [comment]
I can take a look right now

**Comment by kurbster** [comment]
Move your tasks into the tasks directory. The PR is named task 137-144 but you have only provided task 137-141. Are the rest missing? Also, you need to make your negative example explanations better for every task. Don't just copy and paste the same thing. You need to explain why that output is bad.

For task137, there are some instances the have all caps output can you remove them or make them properly cased. You should add at least one more negative example and change one of the current ones. To provide more ways the model could fail, like 
1. Generating a question that can be answered correctly w/o actually reading the passage.
2. Uses the same words given in the passage.

Also, some generated questions are one word like `why?` How is this question unambiguous, what is `why` referring to? Also, you say in the definition the answer must be unique, but with such an open question that seems hard. Maybe remove these one-word questions.

For task 138, remove everything in the definition from `(iv)` on. It seems like that part was leftover from task 137. Change the definition to `The task is about reading the given story and question, then finding an answer to the given question ... `. Change one of the negative examples to another fail case, like what we're trying to do in task 137. Also, most of the answers are one word. The accompanying questions are very vague as well. @swarooprm I don't think this task should be included in the final dataset.

For task 139, the explanation for the second negative example is the same as the first and is incorrect. Remove the word `based` from the second positive explanation. I think the definition should be changed. ` ... return an incorrect answer to the given question.` Currently, some examples reference the passage but do not answer the question. Adding the phrase `which will not be present in the passage` is confusing.

For task 140, there is no explanation of what the output is. You only say `the classification is based on the value in the label key.` But what is the label key. You need to provide the different classes in the definition. If you don't want to include all 64 classes that's fine. Also, you should shuffle the instances. Make your negative example explanations better. You should explain why they are negative, e.x, `The given program solves problem 3 but the output is problem 11`.

For task 141, make your negative example explanation better, much like task 140. Also, remove the `?` symbols found throughout the code. Why is this there? If it is needed for whitespace then just put a space there.

**Comment by ShashankDavalgi** [comment]
Thanks for your comments @kurbster . No there are only tasks from 137-141, I will rename it. 
I am working on the changes you have commented on. 

In task 137, There was only one instance which was all in CAPS, I have updated it. I have added one more negative example so that te model could fail in a different way than other examples. And there was only one instance which had just `why?` question. I  deleted it.

In task 140, I changed the output explanation. I shuffled the instances. Made the negative example explanation better. Provided different instances.

In Task 141, the `?` symbols are there in the dataset itself, that is why I did not remove them. But it is all added as comments, so do I need to remove them? See the image below:
image


Thanks,
Shashank

**Comment by kurbster** [comment]
For task137, you should check all of the one words answers. Using grep I found 6 instances of _why?_ , 5 instances of _what?_, 1 instance of _how?_, and 3 instances of _when?_. Note some of them are capitalized.

For task141, that is weird. Leave them in for now because they don't affect the actual answer. Swaroop can decide what to do with them later.

**Comment by ShashankDavalgi** [comment]
For, task137, I have removed all the one word questions. And what do you mean when some of them are capitalized? Is the whole sentence capitalized or is it just the first character of the first word in the sentence is capitalized?

**Comment by kurbster** [comment]
For task137, there are instances of the question `Why?` I meant the first letter of the question. There are 18 one-word questions that are any of the following `and?, How?, when?, When?, where?, Where?, why?, Why?, who?`

**Comment by ShashankDavalgi** [comment]
@swarooprm @kurbster I have finished making the changes for all the above mentioned tasks. Below are the changes made:

I have made all the changes in task 137, task 140, and task 139.
For task 141, I have not removed the `?` as it was there in the dataset.
For task 138, Changed the negative example, Also removed all the one word answers and question. This may be handles the vague questions and answers.

I have committed the changes, which are in the latest commit named "string conversion tasks".

Thanks,
Shashank Davalgi

**Comment by swarooprm** [comment]
@kurbster, check and let me know if you are happy with the changes or have any other feedback?

**Comment by kurbster** [comment]
I think all of the changes are good. However, I am a little concerned with task140. 

From what I could find, there is no meaning behind the 64 different problems. For example, problem 1 solves finding the maximum number, problem 2 solves finding the minimum, etc... Without telling the model what each number means how would it know how to classify? 

This was not included in the original dataset so there's nothing more to be done on this PR. Just consider this when possibly adding it to the main dataset @swarooprm

**Comment by swarooprm** [comment]
Your HW2 is complete now.

Would you like to submit the same tasks to our big project repo https://github.com/allenai/natural-instructions-expansion/pulls? You just need to fork that repo, rename tasks starting from the latest number in the repo and create PR there. This way, you can be part of our research on "learning from instructions instead of learning from examples (conventional machine learning)". This is purely optional and your HW2 grade does not depend on this @ShashankDavalgi

**Comment by swarooprm** [comment]
@ShashankDavalgi, Just a reminder that, if you plan to submit these tasks to the main Github repo and join our research project, Monday (27th Sept) is the deadline. Again, this is optional and independent of your HW2 grade.

**Comment by ShashankDavalgi** [comment]
@swarooprm Sure, I will be submitting these tasks to the main Github repo by tomorrow.

Thanks,
Shashank

**Pull request closed without merging**
