### PR TITLE
Task 169-172: Amazon polarity and semeval

### PR DESCRIPTION
**Pull request by SavanDoshi**
`task169_review_polarity_classification` | Classify amazon review into positive or negative | Classification
`task170_review_polarity_answer_generation` | Given pair of amazon review and polarity, generate True or False when a review has particular polarity | Answer Generation

`task171_semeval_headline_funniness_answer_generation` | Generate rating for edited news headlines | Answer Generation
`task172_semeval_answer_generation` | Generate answer yes or no based on given edited sentence and rating | Answer Generation

### CODE REVIEW

**Comment by swarooprm** [comment]
@SavanDoshi, I will review once there is 4 or more tasks.

**Comment by SavanDoshi** [comment]
> @SavanDoshi, I will review once there is 4 or more tasks.

@swarooprm I have push another 2 tasks. Please Review it.

**Comment by swarooprm** [comment]
1. task169: looks good, 
2. task170: some grammatical error "Your task is generate answer \"True\" when the review has perticular polarity, otherwise generate answer \"False\"--> "Generate 'True' if the given sentence and its polarity match, else generate 'false'".
3. task171 and 172: rating from 0-3 has subjectivity associated, please convert it to a classification problem say funny or not funny and you can label based on rating value: >1.5--funny and <1.5--not funnny or you can have 3 class problem.  Also, make sure there is no ambiguity and grammatical issue in the definition.
make sure labels are balanced, since most are classification tasks.
I hope you can answer these minor comments quickly so that I can accept your taks @SavanDoshi.

**Comment by SavanDoshi** [comment]
@swarooprm I have made the changes which you asked for.

**Comment by swarooprm** [comment]
I assume labels are balanced. 
I see some grammatical errors e.g. task170: "Your task is generate"--> "Your task is to generate". Also in task171 and 172, "you're given a news headlines and an edited word", In positive examples, instances etc. Don't call the header "Original:", instead you should call "News:" or some thing like this. Make sure to run through grammarly for identifying grammatical issues in definition and explanation.

I will accept the tasks once you do the above minor changes and your HW2 will be complete.
Also, Would you like to submit the same tasks to our big project repo https://github.com/allenai/natural-instructions-expansion/pulls? You just need to fork that repo, rename tasks starting from the latest number in the repo (which at this point is 489) and create PR there. This way, you can be part of our research on "learning from instructions instead of learning from examples (conventional machine learning)". This is purely optional and your HW2 grade does not depend on this. @SavanDoshi

**Comment by SavanDoshi** [comment]
@swarooprm  I have updated files and solved the grammatical errors.  Yes, I have made the labels balanced. Also in task171 and 172, I have changed the header from "Original" to "News Headline". 

Yes, I will create PR in the main Allen AI GitHub repo.

**Comment by swarooprm** [comment]
Great! Your HW2 is complete now.

**Pull request closed without merging**
