### PR TITLE
Complete: Tasks 409-416 ALT & Discofuse Datasets

### PR DESCRIPTION
**Pull request by PhaniRohithaKaza**

### CODE REVIEW

**Comment by swarooprm** [comment]
@aarunku5, wondering if you can help review these tasks?

**Comment by aarunku5** [comment]
For all tasks include the web link to the dataset in the source, along with the dataset name.

For all your translation tasks, can you double-check if you're using the language name and not the country name? (i's needed for a couple of tasks like Laotian, Burmese, etc.)

**task_409_412_003** - definition typo, change to- "convert it into English Tokens"
**task_409_412_015**- definition typo, change to "given a sentence in English Tokens"
Also, what do you mean by English Tokens? The task examples aren't making the task definitions clear for these two?

**task_409_412_016 - 027**  - For all these tasks, in the definition, you've written: "given a sentence in the ___, convert it into the English language". Change it to "given a sentence in the ___ language, ...." 

**task_413** - Is the connecting word always the first word of the second sentence? Change the task category to Answer Generation. Also, update the readme. Change all explanations to "the word ___" instead of "the ___ word".

**task_414**- I am not clear on what the task is. Can you explain it here, as well as update the definition to make it clearer? Refer to the SQUAD example tasks given to update the definition and use Grammarly to verify. I haven't reviewed your examples yet, will do it once the task is clear.

**task_415**- Define what a discourse type is, and also list the possible choices that are discourse types in the definition. In the explanations for this task, elaborate further on why the answer is correct (e.g., why is positive example #1 of type PAIR_CONN_ANAPHORA)

**Comment by PhaniRohithaKaza** [comment]
Hello,

They haven't clearly mentioned about the English Tokens no where in the dataset. I tried some google resources but  I haven't found anything related to it. So, I assumed as model converts the given sentence into tokens right, I thought it may be related to that.

Coming to sentence generation task 414==> given a second sentence, generate a first sentence which is on the same topic but incoherent.

**Comment by PhaniRohithaKaza** [comment]
Hello,

Lao itself a language. Should I change it to Laotian or just keep it as Lao.

**Comment by PhaniRohithaKaza** [comment]
Task 413==> it need not necessarily be the first word of second sentence sometimes it can even be in first sentence

**Comment by PhaniRohithaKaza** [comment]
@aarunku5 Hello, I have addressed all the comments, could you please follow up with it. Thank you :)

**Comment by aarunku5** [comment]
Thanks!

**001**
Update Definition: "In this task, an input sentence is given which can be in the English, Bengali, Filipino, Hindi, Bahasa Indonesia, Japanese, Khmer, Lao, Malay, Myanmar, Thai, Vietnamese or Chinese languages. There are a total of 13 languages. Your task is to identify the language of the input sentence. The input sentence can only be in any of the 13 languages provided."
Change the explanations to "in **the** ___ language" wherever it occurs."

**002**
Remove 'and' from the definition.

**413**
Get rid of the commas in the output, make sure just the word appears.

**414**
In the explanations, it should be '...an incoherent...'

**415**
Update Definition- "There are 13 discourse types in total..."

I'm not sure if we can use 003, 015 as they stand @swarooprm can you take a look?

The rest of the tasks look good, i.e., 003-014, 016-027.

**Comment by PhaniRohithaKaza** [comment]
Hello,

I have addressed the changes and pushed the files again. Please review the changes. Thank you in advance :)

**Comment by aarunku5** [comment]
Thanks, everything looks good here (barring 003,015) @swarooprm

**Comment by PhaniRohithaKaza** [comment]
Hello,

Can I proceed to fork the Allen AI's repo?

**Comment by swarooprm** [comment]
@PhaniRohithaKaza, Your HW2 is complete!
I see you have already created a PR in the Allen AI repo. I have renamed your PR.
Please rename your files to 535-542 since task numbers till 534 are already taken.
Also, feel free to create new tasks in the Allen AI repo if you want to be a co-author in our future paper.

**Comment by PhaniRohithaKaza** [comment]
@swarooprm Thanks :). I would love to contribute more tasks. I will do some more by this weekend. As I have created 30 tasks already, I just want to know will I eligible to be a co-author for the paper?

**Comment by swarooprm** [comment]
Oh sorry I did not notice that you have already created 30 tasks. I have edited the PR name in Allen AI Repo. 
Re: co-author, yes you will be a co-author if your tasks get approved in the Allen AI Repo.

**Comment by PhaniRohithaKaza** [comment]
@swarooprm Thank you:)

**Comment by swarooprm** [comment]
Also, @PhaniRohithaKaza, as per https://github.com/allenai/natural-instructions-expansion#my-commits-are-not-tied-to-my-github-profie-github-does-not-show-all-my-contributions, you also need to do some light reviewing of tasks if you want to be coauthor in our paper. All the contributors are performing task reviews after creating 25 tasks. Reviewing should not take more than a couple of hrs per week. Let me know if you are interested and I can assign a couple of tasks to you.

**Comment by PhaniRohithaKaza** [comment]
@swarooprm Sure. I will review the tasks too.

**Pull request closed without merging**
