### PR TITLE
Tasks 47-71 Phase 1

### PR DESCRIPTION
**Pull request by BhavyaSri1001**

### CODE REVIEW

**Comment by Ravsehajsinghpuri** [comment]
@BhavyaSri1001 1) Can you add the original tasks in this PR. 2) Can you rename the task variants as taskxxx.1_yyyy, taskxxx.2_yyyy, taskxxx.3_yyyy and so on. For e.g. task547.1_spl_translation_entk_en.json, task547.2_spl_translation_entk_en.json, task547.3_spl_translation_entk_en.json and so on. Do this for all the tasks in this PR 3) Can you resolve the conflicts

**Comment by BhavyaSri1001** [comment]
Hi @Ravsehajsinghpuri . I have made all the changes but not sure how to resolve the conflicts as i didnt find any issues in files. can you help me with that?

**Comment by BhavyaSri1001** [comment]
Hi,
I have uploaded the phase 1 and phase 2 project reports as well.
I have resolved the conflicts too.

[Dataset_47_71_Bhavya_Sri_Aravapalli-1.pdf](https://github.com/swarooprm/CSE576HW/files/7481062/Dataset_47_71_Bhavya_Sri_Aravapalli-1.pdf
[Dataset_47_71_Bhavya_Sri_Aravapalli-2.pdf](https://github.com/swarooprm/CSE576HW/files/7481064/Dataset_47_71_Bhavya_Sri_Aravapalli-2.pdf)
)

**Comment by Ravsehajsinghpuri** [comment]
@BhavyaSri1001 did you raise the PR for phase 2 variants? I can see only 2-3 variants of each task. Can you do 5-6 variants of each tasks? Do you have a separate PR for the phase 2?

**Comment by BhavyaSri1001** [comment]
Hi @Ravsehajsinghpuri , I have done nearly 60 variants and some of the tasks do not have more than 6000 instances whereas many of them have paragraph questioning and answering kind of tasks and longer definitions which require reading through the whole passage and writing examples, definitions. So that took up more time and we are told by swaroop that the number doesn't matter but the quality is required.

**Comment by Ravsehajsinghpuri** [comment]
@BhavyaSri1001 can you resolve the conflicts

**Pull request merged**
