### PR TITLE
task428-task474 phase 2

### PR DESCRIPTION
**Pull request by hanut1909**

### CODE REVIEW

**Comment by Ravsehajsinghpuri** [comment]
> i am not able ot create a pull request again. please consider this for the second phase submission.

@hanut1909 does this PR include phase 1 or phase 2 tasks? I saw you're other PR as well, not sure what is this about, can you clarify

**Comment by Ravsehajsinghpuri** [comment]
@hanut1909 while resolving conflicts, I have mistakenly deleted one of the names of the files in the README. Can you check and add accordingly?

**Comment by hanut1909** [comment]
yes it contains the 1st phase of the task. I accidentally added the phase 2 tasks as well for this one. Should I remove them from here?

**Comment by Ravsehajsinghpuri** [comment]
@hanut1909 No you're good, this is merged

**Pull request merged**
