### PR TITLE
Task 129 - 135 : DNC Paper Dataset

### PR DESCRIPTION
**Pull request by aritC**

### CODE REVIEW

**Comment by swarooprm** [comment]
1. task129: "Your job is to determine if the second sentence clearly agrees with the first sentence. Indicate your answer with 1 for Entailment and 0 for No Entailment"--->"Your job is to determine if the second sentence clearly agrees/entails with the first sentence. Indicate your answer with 1 if the second sentence entails the first sentence, else 0"
2. task130: there's an extra 'the', remove. Also remove the word 'also';its redundant.
3. task131: "position."--->"positions."
4. task135: make it a classification problem where given premise, hyp., you need to identify the class (i) entialment,(ii) contradiction etc.. text generation does not make sense.
@aritC, overall it looks good. I suggested some minor changes. One thing: in classification tasks, make sure that classes are balanced across instances.

**Comment by aritC** [comment]
1 : Fixed the line
2 : removed the extra 'the' and 'also'
3 : changed position to positions
4 : Since I already have submitted a task of classification with the same dataset I've removed this task
5 : Checked and verified all the classification task's classes are balanced

@swarooprm For your review

**Comment by swarooprm** [comment]
Great, your HW2 is complete now.
Would you like to submit the same tasks to our big project repo https://github.com/allenai/natural-instructions-expansion/pulls? You just need to fork that repo, rename tasks starting from the latest number in the repo (which at this point is 517) and create PR there. This way, you can be part of our research on "learning from instructions instead of learning from examples (conventional machine learning)". This is purely optional and your HW2 grade does not depend on this

**Comment by swarooprm** [comment]
Closing this, reminder that you have an option to submit to the main repo https://github.com/allenai/natural-instructions-expansion/pulls

**Comment by swarooprm** [comment]
@aritC, just wanted to check if you are planning to submit these tasks to our main repo (it should not take more than a couple minutes).
Alternatively, let us know if you are not planning and one of our contributors will create tasks from this.

**Comment by swarooprm** [comment]
@aritC Just a reminder that, if you plan to submit these tasks to the main Github repo and join our research project, Monday (27th Sept) is the deadline. Again, this is optional and independent of your HW2 grade.

**Pull request closed without merging**
