### PR TITLE
Tasks 310-332 Variant tasks Phase 1

### PR DESCRIPTION
**Pull request by saianirud**

### CODE REVIEW

**Comment by Ravsehajsinghpuri** [comment]
@saianirud 1) Can you add the original tasks in this PR. 2) Can you rename the task variants as taskxxx.1_yyyy, taskxxx.2_yyyy, taskxxx.3_yyyy and so on. For e.g. task547.1_spl_translation_entk_en.json, task547.2_spl_translation_entk_en.json, task547.3_spl_translation_entk_en.json and so on. Do this for all the tasks in this PR 3) Can you resolve the conflicts

**Comment by saianirud** [comment]
@swarooprm @Ravsehajsinghpuri modified the task names. I am also attaching the report for Phase - 1
[Dataset3_SaianirudReddyNellore.pdf](https://github.com/swarooprm/CSE576HW/files/7489826/Dataset3_SaianirudReddyNellore.pdf)

**Comment by Ravsehajsinghpuri** [comment]
> @swarooprm @Ravsehajsinghpuri modified the task names. I am also attaching the report for Phase - 1
> [Dataset3_SaianirudReddyNellore.pdf](https://github.com/swarooprm/CSE576HW/files/7489826/Dataset3_SaianirudReddyNellore.pdf)

Can you resolve the conflicts?

**Comment by Ravsehajsinghpuri** [comment]
@saianirud  Quick question - Are the tasks added in this PR, already part of the phase 2 whose PR has been merged? Pls confirm because then you can close this PR as the tasks have already been merged

**Comment by saianirud** [comment]
@Ravsehajsinghpuri no these are different tasks

**Comment by Ravsehajsinghpuri** [comment]
> @Ravsehajsinghpuri no these are different tasks

But the names are same, these tasks have already been merged as part of phase 2

**Comment by saianirud** [comment]
> > @Ravsehajsinghpuri no these are different tasks
> 
> But the names are the same, these tasks have already been merged as part of phase 2

Names might be the same but the content is different. I didn't know that the naming convention should be different for phase 1 and phase 2.  I will change the names right away

**Comment by saianirud** [comment]
@Ravsehajsinghpuri changed the file names. Thank you

**Comment by Ravsehajsinghpuri** [comment]
> @Ravsehajsinghpuri changed the file names. Thank you

perfect! thanks

**Pull request merged**
