### PR TITLE
Complete: Tasks 145-152 for com_qa and paracrawl datasets

### PR DESCRIPTION
**Pull request by Arutselvan**

### CODE REVIEW

**Review by swarooprm — COMMENTED** [review]
Review:
1. task145: Ask to generate to single paraphrase rather than a list of paraphrases. So change definition. Positive examples's outputs should have single paraphrase, however keep all possible paraphrases in the output of instances which is a list. This way output of positive examples will be a string where as instances will contain list as output. I dont understand what you want to say in this line "Additional contextual information if available can be used to frame the questions". Either make it more clear or delete it.
2. Task146: same- make output of positive examples a string, instances a list. Ask to generate single question. This line "Don't create questions on topics indirectly related to the given answer" is ambiguous in the definition. Rephrase the line.
3. Task147: looks good, make the definition more professional by rephrasing terms like "that mean the same thing". You can drop "related answer" and just talk about "partial answer"
4.  Task 148: a tricky one, but keep it. You can make "Given a set of questions" to "Give a question and its paraphrases"
5. Task 149: category should be 'translation'. Also, please create a task to convert somali to english, you can name the task as task1003
6. Task 150: "Identify the language" should be "generate the language". Category: Classification
7. Task 151 Category: Translation, also create a reverse translation task and name it 1004
8. Task 152 Category: Translation, also create a reverse translation task and name it 1005

Rename files so that their names are not same. E.g. task147 and task148 has almost same name. Also add dataset url in the source field.

Overall you did a good job. These are minor fixes in language which you should be able to fix quickly. Let me know once you are done and I can review it again. @Arutselvan

**Comment by Arutselvan** [comment]
Thanks a lot for the feedback. I have made the above mentioned changes:
- Changed the task definitions and examples of 145 and 146 to generate question string as output.
- Rephrased the definitions of tasks 147 and 148
- Change the categories of the translation tasks (149,151,152) and the classification task (150)
- Added 3 new reverse translation tasks 1003,1004 and 1005
- Added URL of the dataset as source in the tasks
- Renamed the files to be more distinguishable 
@swarooprm

**Comment by swarooprm** [comment]
Thanks! two feedbacks remained:
1. task 145: in instances, put all possible answers in a list, e.g. if for a given question, you have 3 paraphrases, put them in a list. 
2. task 146: same as above, make instance output a list. I would change negative example 1 explanation from "The question and the answer is a part of a broader topic but they're not directly related" to "The answer to the generated question is not the answer mentioned in the input, so this is a bad output."

You have done a good job. Once you address these 2 comments, I can accept your tasks.

**Comment by Arutselvan** [comment]
Thank you for your time to give feedback. I've made the explanation change but I don't quite understand the other change. The output value is already a list containing all the possible paraphrases - in both tasks 145 and 146. I have attached some instances from task 145 below. If you can just use one of these and explain, that will be great. @swarooprm 

Task 145 sample instances:

`{
            "input": "Question: what was rick riordan's first book he wrote?",
            "output": [
                "what was rick riordan's first book written?",
                "what was the first book rick riordan wrote?",
                "what is rick riordans first kids book?"
            ]
        },
        {
            "input": "Question: when was remember the titans filmed?",
            "output": [
                "when was the movie remember the titans filmed?"
            ]
        },
        {
            "input": "Question: largest city located along the nile river?",
            "output": [
                "what largest city in africa is on the banks of the nile river?",
                "largest city on the nile river?",
                "largest city by the nile river?",
                "largest city in africa built on the nile river?",
                "what is the largest city in africa that is on the banks of the nile river?"
            ]
},`

**Comment by swarooprm** [comment]
> Thank you for your time to give feedback. I've made the explanation change but I don't quite understand the other change. The output value is already a list containing all the possible paraphrases - in both tasks 145 and 146. I have attached some instances from task 145 below. If you can just use one of these and explain, that will be great. @swarooprm
> 
> Task 145 sample instances:
> 
> ```
>         {
>             "input": "Question: what was rick riordan's first book he wrote?",
>             "output": [
>                 "what was rick riordan's first book written?",
>                 "what was the first book rick riordan wrote?",
>                 "what is rick riordans first kids book?"
>             ]
>         },
>         {
>             "input": "Question: when was remember the titans filmed?",
>             "output": [
>                 "when was the movie remember the titans filmed?"
>             ]
>         },
>         {
>             "input": "Question: largest city located along the nile river?",
>             "output": [
>                 "what largest city in africa is on the banks of the nile river?",
>                 "largest city on the nile river?",
>                 "largest city by the nile river?",
>                 "largest city in africa built on the nile river?",
>                 "what is the largest city in africa that is on the banks of the nile river?"
>             ]
>         }
> ```

my bad! you are right. I am going to accept your tasks, you have done a great job. Your HW2 is complete now.
Would you like to submit the same tasks to our big project repo https://github.com/allenai/natural-instructions-expansion/pulls? You just need to fork that repo, rename tasks starting from the latest number in the repo (which at this point is 442) and create PR there. This way, you can be part of our research on "learning from instructions instead of learning from examples (conventional machine learning)". This is purely optional and your HW2 grade does not depend on this.

**Comment by Arutselvan** [comment]
Sure I would be happy to do it. Thank you  @swarooprm

**Comment by swarooprm** [comment]
> Sure I would be happy to do it. Thank you @swarooprm

Great!

**Pull request closed without merging**
