### PR TITLE
Complete: Mirali: Task_(17-22)_cedr_winobias_triangleCOPA

### PR DESCRIPTION
**Pull request by samarthi894**
Please review my task files

### CODE REVIEW

**Comment by samarthi894** [comment]
@swarooprm My tests are not running. I am getting "First-time contributors need a maintainer to approve running workflows."

**Comment by swarooprm** [comment]
@samarthi894, your tests are failing. Please fix your files so that we can start reviewing your HW.

**Comment by samarthi894** [comment]
@swarooprm I have formatted the tasks and committed them again. Please approve so that my test cases will run.

**Comment by swarooprm** [comment]
your tests are still failing. Please run tests locally using src/test_all.py before pushing here.

**Comment by samarthi894** [comment]
> your tests are still failing. Please run tests locally using src/test_all.py before pushing here.

@swarooprm I am sorry for the multiple commits which I am doing but the reason for that is I am facing an issue testing in the local. I am getting this error .."FileNotFoundError: [Errno 2] No such file or directory: 'tasks/README.md'. I tried all possible ways but still getting the same FileNotFoundError.

**Comment by swarooprm** [comment]
I guess you have already tried with ASCII=False option.
Also, make sure to try removing utf-8 encoding option while creating the json file

**Comment by swarooprm** [comment]
@Mirzyaaliii, can you help review these tasks?

**Comment by Mirzyaaliii** [comment]
- General comments - 
1. Check other tasks and modify your all tasks according to them. (For your reference, check few tasks from [here](https://github.com/krishna-8/CSE576HW/tree/main/tasks). And that might be the reason your checks are failing.) 
2. Remove **.json** from _Name_ in README.
3. Add dataset name in the filename of all tasks.
Format for filename is **tasknumber_datasetname_language_category**
Mention 2 letters short of the language you are using in your task, if language is other than English. (You can check short form [here](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes))
4. Elaborate the summary in the README. For your reference check few summaries [here](https://github.com/allenai/natural-instructions-expansion/tree/master/tasks).
5. Remove extra empty lines. For example, in Task - 19, remove lines 81 and 82.

- Task - 17
1. As you are using a different language, check task 424 from [here](https://github.com/krishna-8/CSE576HW/tree/main/tasks) and add Input_language, Output_language and Instruction_language in your JSON file. (Apply this change to Task-18)
2. Change the category to _Classificcation_. (Apply this change to Task-18)
3. Change filename from (Apply this change to Task-18)
`task_17_Answer_generation
`
to
`task17_cedr_ru_emotion_classification`
4. For the dataset link, provide this [link](https://huggingface.co/datasets/viewer/?dataset=cedr), instead of whatever you wrote now. And provide dataset link as shown in task 424 [here](https://github.com/krishna-8/CSE576HW/tree/main/tasks) (Apply this change to Task-18)
5. In the output, write emotion directly instead of assigning it to a number.

- Task - 18
1. This task is very similar to Task-17, first, change the above 3 points and then change this task to incorrect emotion classification.

- Task - 19
1. For the dataset link, provide this [link](https://huggingface.co/datasets/viewer/?dataset=wino_bias), instead of whatever you wrote now. And provide dataset link as shown in task 424 [here](https://github.com/krishna-8/CSE576HW/tree/main/tasks) (Apply this change to Task-18)
2. In input instead of writing words separately into the list, write it as a sentence.
3. In the output, return the exact coreference words and separate them by comma (,) in one string only and change the definition accordingly. For example for the first positive example,
`["the clerk, she"]`
4. Why there is **\n** in all the inputs, is it on purpose or by mistake?
5. Change the category to _Text Generation_.

- Task - 20
Change the definition from
```
A premise is a short summary of a situation or a story. Here you will be given a premise and you need to generate a question based on the given premise. The generated question (i) must be unambiguous, (ii) must be relevant to the premise and should be present within the context of the premise, (iii) should be answerable with the given premise. You should not use any outside knowledge to generate the question.
```

to

```
In this task, you are given a short story or summary of a situation (premise). Your task is to generate a question based on the given premise. The generated question (i) must be unambiguous, (ii) must be relevant to the premise and should be present within the context of the premise, (iii) should be answerable with the given premise. You should not use any outside knowledge to generate the question.
```

- Once you complete **all the changes**, drop a comment here and if you have any suggestions or doubts on any comment mention here.

**Comment by samarthi894** [comment]
> * General comments -
> 
> 1. Check other tasks and modify your all tasks according to them. (For your reference, check few tasks from [here](https://github.com/krishna-8/CSE576HW/tree/main/tasks). And that might be the reason your checks are failing.)
> 2. Remove **.json** from _Name_ in README.
> 3. Add dataset name in the filename of all tasks.
>    Format for filename is **tasknumber_datasetname_language_category**
>    Mention 2 letters short of the language you are using in your task, if language is other than English. (You can check short form [here](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes))
> 4. Elaborate the summary in the README. For your reference check few summaries [here](https://github.com/allenai/natural-instructions-expansion/tree/master/tasks).
> 5. Remove extra empty lines. For example, in Task - 19, remove lines 81 and 82.
> 
> * Task - 17
> 
> 1. As you are using a different language, check task 424 from [here](https://github.com/krishna-8/CSE576HW/tree/main/tasks) and add Input_language, Output_language and Instruction_language in your JSON file. (Apply this change to Task-18)
> 2. Change the category to _Classificcation_. (Apply this change to Task-18)
> 3. Change filename from (Apply this change to Task-18)
>    `task_17_Answer_generation `
>    to
>    `task17_cedr_ru_emotion_classification`
> 4. For the dataset link, provide this [link](https://huggingface.co/datasets/viewer/?dataset=cedr), instead of whatever you wrote now. And provide dataset link as shown in task 424 [here](https://github.com/krishna-8/CSE576HW/tree/main/tasks) (Apply this change to Task-18)
> 5. In the output, write emotion directly instead of assigning it to a number.
> 
> * Task - 18
> 
> 1. This task is very similar to Task-17, first, change the above 3 points and then change this task to incorrect emotion classification.
> 
> * Task - 19
> 
> 1. For the dataset link, provide this [link](https://huggingface.co/datasets/viewer/?dataset=wino_bias), instead of whatever you wrote now. And provide dataset link as shown in task 424 [here](https://github.com/krishna-8/CSE576HW/tree/main/tasks) (Apply this change to Task-18)
> 2. In input instead of writing words separately into the list, write it as a sentence.
> 3. In the output, return the exact coreference words and separate them by comma (,) in one string only and change the definition accordingly. For example for the first positive example,
>    `["the clerk, she"]`
> 4. Why there is **\n** in all the inputs, is it on purpose or by mistake?
> 5. Change the category to _Text Generation_.
> 
> * Task - 20
>   Change the definition from
> 
> ```
> A premise is a short summary of a situation or a story. Here you will be given a premise and you need to generate a question based on the given premise. The generated question (i) must be unambiguous, (ii) must be relevant to the premise and should be present within the context of the premise, (iii) should be answerable with the given premise. You should not use any outside knowledge to generate the question.
> ```
> 
> to
> 
> ```
> In this task, you are given a short story or summary of a situation (premise). Your task is to generate a question based on the given premise. The generated question (i) must be unambiguous, (ii) must be relevant to the premise and should be present within the context of the premise, (iii) should be answerable with the given premise. You should not use any outside knowledge to generate the question.
> ```
> 
> * Once you complete **all the changes**, drop a comment here and if you have any suggestions or doubts on any comment mention here.



> * General comments -
> 
> 1. Check other tasks and modify your all tasks according to them. (For your reference, check few tasks from [here](https://github.com/krishna-8/CSE576HW/tree/main/tasks). And that might be the reason your checks are failing.)
> 2. Remove **.json** from _Name_ in README.
> 3. Add dataset name in the filename of all tasks.
>    Format for filename is **tasknumber_datasetname_language_category**
>    Mention 2 letters short of the language you are using in your task, if language is other than English. (You can check short form [here](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes))
> 4. Elaborate the summary in the README. For your reference check few summaries [here](https://github.com/allenai/natural-instructions-expansion/tree/master/tasks).
> 5. Remove extra empty lines. For example, in Task - 19, remove lines 81 and 82.
> 
> * Task - 17
> 
> 1. As you are using a different language, check task 424 from [here](https://github.com/krishna-8/CSE576HW/tree/main/tasks) and add Input_language, Output_language and Instruction_language in your JSON file. (Apply this change to Task-18)
> 2. Change the category to _Classificcation_. (Apply this change to Task-18)
> 3. Change filename from (Apply this change to Task-18)
>    `task_17_Answer_generation `
>    to
>    `task17_cedr_ru_emotion_classification`
> 4. For the dataset link, provide this [link](https://huggingface.co/datasets/viewer/?dataset=cedr), instead of whatever you wrote now. And provide dataset link as shown in task 424 [here](https://github.com/krishna-8/CSE576HW/tree/main/tasks) (Apply this change to Task-18)
> 5. In the output, write emotion directly instead of assigning it to a number.
> 
> * Task - 18
> 
> 1. This task is very similar to Task-17, first, change the above 3 points and then change this task to incorrect emotion classification.
> 
> * Task - 19
> 
> 1. For the dataset link, provide this [link](https://huggingface.co/datasets/viewer/?dataset=wino_bias), instead of whatever you wrote now. And provide dataset link as shown in task 424 [here](https://github.com/krishna-8/CSE576HW/tree/main/tasks) (Apply this change to Task-18)
> 2. In input instead of writing words separately into the list, write it as a sentence.
> 3. In the output, return the exact coreference words and separate them by comma (,) in one string only and change the definition accordingly. For example for the first positive example,
>    `["the clerk, she"]`
> 4. Why there is **\n** in all the inputs, is it on purpose or by mistake?
> 5. Change the category to _Text Generation_.
> 
> * Task - 20
>   Change the definition from
> 
> ```
> A premise is a short summary of a situation or a story. Here you will be given a premise and you need to generate a question based on the given premise. The generated question (i) must be unambiguous, (ii) must be relevant to the premise and should be present within the context of the premise, (iii) should be answerable with the given premise. You should not use any outside knowledge to generate the question.
> ```
> 
> to
> 
> ```
> In this task, you are given a short story or summary of a situation (premise). Your task is to generate a question based on the given premise. The generated question (i) must be unambiguous, (ii) must be relevant to the premise and should be present within the context of the premise, (iii) should be answerable with the given premise. You should not use any outside knowledge to generate the question.
> ```
> 
> * Once you complete **all the changes**, drop a comment here and if you have any suggestions or doubts on any comment mention here.

Hi Sir/Madam,
I have done the mentioned changes and committed my files. Kindly, review and let me know if I missed anything.

**Comment by Mirzyaaliii** [comment]
- General comments -
1. Delete old files.
2. _Contributors_ and _Categories_ should be list.
3. Remove extra space before and after string from all the output lists of instances, examples and source field.
```
"output": [ "anger" ]
```
4. Filename should be in lowercase, change this in the README also.

- Task - 17
1. Change the definition according to the task.
2. In the README, change the category to _Classification_.

- Task - 18
1. In this task also return the incorrect emotion directly instead of returning the number and according to that change the definition and other things.
2. In the README, change the category to _Incorrect Classification_.

- Task - 19
1. Don't need to mention _eng_ in the filename, remove it. (Apply this to Task-20 also.)

**Comment by samarthi894** [comment]
> * General comments -
> 
> 1. Delete old files.
> 2. _Contributors_ and _Categories_ should be list.
> 3. Remove extra space before and after string from all the output lists of instances, examples and source field.
> 
> ```
> "output": [ "anger" ]
> ```
> 
> 1. Filename should be in lowercase, change this in the README also.
> 
> * Task - 17
> 
> 1. Change the definition according to the task.
> 2. In the README, change the category to _Classification_.
> 
> * Task - 18
> 
> 1. In this task also return the incorrect emotion directly instead of returning the number and according to that change the definition and other things.
> 2. In the README, change the category to _Incorrect Classification_.
> 
> * Task - 19
> 
> 1. Don't need to mention _eng_ in the filename, remove it. (Apply this to Task-20 also.)

Hi Sir/Madam,
For task 18, I am giving MCQ's as input so I made output as the option name A or B or C.....etc. Here I am returning the option which has an incorrect emotion label name. Do I need to change this MCQ task to a normal text generation one?

**Comment by Mirzyaaliii** [comment]
> > * General comments -
> > 
> > 
> > 1. Delete old files.
> > 2. _Contributors_ and _Categories_ should be list.
> > 3. Remove extra space before and after string from all the output lists of instances, examples and source field.
> > 
> > ```
> > "output": [ "anger" ]
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > 1. Filename should be in lowercase, change this in the README also.
> > 
> > 
> > * Task - 17
> > 
> > 
> > 1. Change the definition according to the task.
> > 2. In the README, change the category to _Classification_.
> > 
> > 
> > * Task - 18
> > 
> > 
> > 1. In this task also return the incorrect emotion directly instead of returning the number and according to that change the definition and other things.
> > 2. In the README, change the category to _Incorrect Classification_.
> > 
> > 
> > * Task - 19
> > 
> > 
> > 1. Don't need to mention _eng_ in the filename, remove it. (Apply this to Task-20 also.)
> 
> Hi Sir/Madam, For task 18, I am giving MCQ's as input so I made output as the option name A or B or C.....etc. Here I am returning the option which has an incorrect emotion label name. Do I need to change this MCQ task to a normal text generation one?

@samarthi894 Yes, it is better if you convert the task like that. So, it will same as Task-17, just generate the incorrect answer. Also, do _all other changes_ and once done please comment here.

**Comment by samarthi894** [comment]
> > > * General comments -
> > > 
> > > 
> > > 1. Delete old files.
> > > 2. _Contributors_ and _Categories_ should be list.
> > > 3. Remove extra space before and after string from all the output lists of instances, examples and source field.
> > > 
> > > ```
> > > "output": [ "anger" ]
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 
> > > 1. Filename should be in lowercase, change this in the README also.
> > > 
> > > 
> > > * Task - 17
> > > 
> > > 
> > > 1. Change the definition according to the task.
> > > 2. In the README, change the category to _Classification_.
> > > 
> > > 
> > > * Task - 18
> > > 
> > > 
> > > 1. In this task also return the incorrect emotion directly instead of returning the number and according to that change the definition and other things.
> > > 2. In the README, change the category to _Incorrect Classification_.
> > > 
> > > 
> > > * Task - 19
> > > 
> > > 
> > > 1. Don't need to mention _eng_ in the filename, remove it. (Apply this to Task-20 also.)
> > 
> > 
> > Hi Sir/Madam, For task 18, I am giving MCQ's as input so I made output as the option name A or B or C.....etc. Here I am returning the option which has an incorrect emotion label name. Do I need to change this MCQ task to a normal text generation one?
> 
> @samarthi894 Yes, it is better if you convert the task like that. So, it will same as Task-17, just generate the incorrect answer. Also, do _all other changes_ and once done please comment here.

Hi Mirali,
I have done the above changes and committed my files. All files passed successfully. Kindly, review and let me know if any  other changes required

**Comment by Mirzyaaliii** [comment]
All things look good to me, just a few minor comments.

- General comments -
1. Instances are not human-readable.
2. Inside the JSON file, write the category same as README.
3. There are few grammatical errors in the explanation and definition. So, please once pass it on the Grammarly (or a similar tool). Hence, there will be no grammatical, punctuation, spacing, etc errors.
 
- Task - 18
Make input language as a string as shown below:
```
"Input_language": "Russian",
```

After these changes, your tasks are _done_.

**Comment by samarthi894** [comment]
> All things look good to me, just a few minor comments.
> 
> * General comments -
> 
> 1. Instances are not human-readable.
> 2. Inside the JSON file, write the category same as README.
> 3. There are few grammatical errors in the explanation and definition. So, please once pass it on the Grammarly (or a similar tool). Hence, there will be no grammatical, punctuation, spacing, etc errors.
> 
> * Task - 18
>   Make input language as a string as shown below:
> 
> ```
> "Input_language": "Russian",
> ```
> 
> After these changes, your tasks are _done_.

Have done the above changes and committed my files.

**Comment by Mirzyaaliii** [comment]
@swarooprm All things look good to me.

**Pull request closed without merging**
