### PR TITLE
Maitreya: Tasks 121-125:Event2Mind and Coached_Conv_Pref dataset

### PR DESCRIPTION
**Pull request by yashbhokare**

### CODE REVIEW

**Comment by swarooprm** [comment]
@Maitreyapatel, wondering if you can help review these tasks?

**Comment by swarooprm** [comment]
@Maitreyapatel, wondering if you can help review these tasks?

**Review by Maitreyapatel — CHANGES_REQUESTED** [review]
Summary: You need to give proper and clean definitions. Make your friend or roommate read them. And check whether they are able to understand it clearly or not on the first attempt. When we humans start learning something new we need proper instructions, same goes for computers too. Also, you should not use any programming related or data storage related syntax. It should feel like you are reading a book instead of reading the database.


Please refer below comments:
1. Remove any capital characters from the task file name and update the same in readme as well.
2. Remove “.json” from task name names given in readme.
3. Task121: 
a. This is the classification task. So, explain each and every class in Definition. If there are too many classes then change the task category to generation and update the definition accordingly such that it explains what to generate.  
b. In addition to that, there are many instances referring to PersonY. So, update definition as => ‘.... (i.e., PersonX and PersonY)’ instead of ‘... say ‘PersonX’.
c. It seems that all the instances have blanks. Therefore, create the positive and negative examples having these blanks such that there is no such mismatch with Instances.
System does not understand the concept of lists easily. Therefore, convert “Intent:[to relax at home,to have some alone time,to relax,to end the day]” to “Intent: 1) to relax at home 2) to have some alone time 3) to relax 4) to end the day”.
d. Change the definition from “You are provided with an event,intent and reaction related to PersonX.” to “You are provided with an \”Event\”, \”Intent\” and reaction related to PersonX.”
4. Task122: 
a. Again same as task121, this is the classification task. So, explain each and every class in Definition. For example, here, you need to explain when to classify “Positive”, “Negative”, and “Unknown”.
b. Again, refer to the point (3.d) above. If intent is None then keep it an empty string like: “Intent: ”, instead of stating None.
c. Refer to the same suggestion as (3.b).
5. Task123: 
a. Please follow all the above comments for this task file as well. In addition, refer below extra comments:
b. In definition, mention what XEmotion refers to. There is no mention of emotion. What is the reaction ? Please list them and justify how to identify them. 

6. Task124: 
a. Give proper and clear definition. Change “You are provided with a list of converations between a USER and ASSISTANT.” to “You are provided with the conversations between a \“USER\” and \“ASSISTANT\”.” 
b. Input should be in textual format. You can’t use any programming language related syntax. For example, write as “USER: How are you doing ? ASSISTANT: I’m doing good. ASSISTANT: What about you? ….. ”
7. Task125: 
a. This is not a classification task. It's a word/phrase generation task. Please, modify the task category and update the definition. 
b. And refer to the same comments as Task124.

**Review by Maitreyapatel — COMMENTED** [review]
These task files are improved for sure.
Just last few minor and quick suggestions:

* Task122: What is the count of each class instance ?
* Task123: Can you remove the instances having output “none” ?
* Task124: Please change the following sentence in definition “There should a a maximum of 7 conversations between \"USER\" and \"ASSISTANT\"” to “There are maximum of 7 conversations between \"USER\" and \"ASSISTANT\" in each input.”
* Task124: Please change the first negative example. Choose another example where there is a proper answer. This applies to the Instances as well.
* Task125: There is no need to mention anything point by point (i.e., (i), (ii), ...).  I’m not finding any use of “(iii) There should be a minimum of 4 utterances between the \"USER\" and \"ASSISTANT\".” If that’s the case then please remove it.

**Comment by yashbhokare** [comment]
Task122: What is the count of each class instance ?
-> It ranges from 0 -3
Task123: Can you remove the instances having output “none” ?
-> Done
Task124: Please change the following sentence in definition “There should a a maximum of 7 conversations between "USER" and "ASSISTANT"” to “There are maximum of 7 conversations between "USER" and "ASSISTANT" in each input.”
-> Done
Task124: Please change the first negative example. Choose another example where there is a proper answer. This applies to the Instances as well.
-> Updated it.
Task125: There is no need to mention anything point by point (i.e., (i), (ii), ...). I’m not finding any use of “(iii) There should be a minimum of 4 utterances between the "USER" and "ASSISTANT".” If that’s the case then please remove it.
-> Made changes and uploaded the new one.

**Review by Maitreyapatel — COMMENTED** [review]
Just few another minor suggestions:
* Task122: I wanted to check the total number of examples for each class. I check by myself and I think there are about 550 negative examples. And positive/unknowns are high in numbers. Therefore, I would suggest to keep the data balance (i.e., ~600 examples from each class). 
* Task123: There are two "none" examples in positive/negative instances. Please update them as well.

Please do these last minor changes and your homework is done.

**Comment by swarooprm** [comment]
@yashbhokare, can you address reviewer comments so that I can evaluate your HW?

**Comment by yashbhokare** [comment]
Task122: I wanted to check the total number of examples for each class. I check by myself and I think there are about 550 negative examples. And positive/unknowns are high in numbers. Therefore, I would suggest to keep the data balance (i.e., ~600 examples from each class).
-> I've updated the Instances to have Positive - 1500 examples, Negative - 1500 examples, and Unknown - 1500 examples.
Task123: There are two "none" examples in positive/negative instances. Please update them as well.
-> I've removed the none values.

**Comment by swarooprm** [comment]
Your HW2 is complete now.

Would you like to submit the same tasks to our big project repo https://github.com/allenai/natural-instructions-expansion/pulls? You just need to fork that repo, rename tasks starting from the latest number in the repo and create PR there. This way, you can be part of our research on "learning from instructions instead of learning from examples (conventional machine learning)". This is purely optional and your HW2 grade does not depend on this @yashbhokare

**Comment by swarooprm** [comment]
@yashbhokare, Just a reminder that, if you plan to submit these tasks to the main Github repo and join our research project, Monday (27th Sept) is the deadline. Again, this is optional and independent of your HW2 grade.

**Pull request closed without merging**
