### PR TITLE
Swaroop: task697_700:Hans_MovieRationales

### PR DESCRIPTION
**Pull request by devshree07**

### CODE REVIEW

**Comment by swarooprm** [comment]
@aarunku5, wondering if you can review these tasks?

**Comment by aarunku5** [comment]
1) The names for the files are incorrect. It should be:
"task_705_hans_classification.json"
"task_706_hans_answer_generation.json"
2) 705 category should be just "Classification", 706 should just be "Answer Generation"
3) The "Source" in both files should be the web link to the dataset paper HANS that you were provided. Not the name of the dataset.
4) Change the definitions as follows:
**705**
In this task, you must classify if there is lexical overlap present between the given premise and hypothesis statements, indicating your answer as "Yes" or "No". If the hypothesis is a sub-string of the premise, the answer must be "No". 
**706**
In this task, given a premise statement, generate a hypothesis that does not agree, i.e., is not entailed, with respect to the premise. The hypothesis must be unambiguous and should have the same subjects/objects as are in the premise.
5) Changes in positive/negative examples:
**705**
Positive Example 1: typo- sentor should be "senator"
Negative Examples: In the explanations for both, change sub-sequence to "sub-string"
**706**
Positive Example 1: The hypothesis is a substring, you can't use this as an example.
Negative Example 1: Change the output "**the** judge"
Both negative examples' explanations: Typo "hypotesis", and correct the grammar to "and the hypothesis"

**Comment by devshree07** [comment]
> * The names for the files are incorrect. It should be:
>   "task_705_hans_classification.json"
>   "task_706_hans_answer_generation.json"
> * 705 category should be just "Classification", 706 should just be "Answer Generation"
> * The "Source" in both files should be the web link to the dataset paper HANS that you were provided. Not the name of the dataset.
> * Change the definitions as follows:
>   **705**
>   In this task, you must classify if there is lexical overlap present between the given premise and hypothesis statements, indicating your answer as "Yes" or "No". If the hypothesis is a sub-string of the premise, the answer must be "No".
>   **706**
>   In this task, given a premise statement, generate a hypothesis that does not agree, i.e., is not entailed, with respect to the premise. The hypothesis must be unambiguous and should have the same subjects/objects as are in the premise.
> * Changes in positive/negative examples:
>   **705**
>   Positive Example 1: typo- sentor should be "senator"
>   Negative Examples: In the explanations for both, change sub-sequence to "sub-string"
>   **706**
>   Positive Example 1: The hypothesis is a substring, you can't use this as an example.
>   Negative Example 1: Change the output "**the** judge"
>   Both negative examples' explanations: Typo "hypotesis", and correct the grammar to "and the hypothesis"

I have completed the changes and also added the remaining two tasks. Thank you.

**Comment by aarunku5** [comment]
Update the README to put the tasks in order. If the category has changed, update the category too here.

For all the tasks, I think you've confused what a negative example means. 

Positive Examples:
Model answers true and correct answer is true
Model answers false and correct answer is false

Negative Examples:
Model answers true, but the correct answer is false
Model  answers false but the correct answer is true

Update your positive and negative examples accordingly for all the tasks. Negative examples are when the answer is completely incorrect. Not false or no or etc. options.

**697**
Is the task a sentiment analysis classification task? Your explanations in the examples: "The evidence generated is a positive example as it contains words/phrases from review and is unambiguous." this isn't making it clear what your task is doing? Also, in the positive examples, your explanation says it's positive, but your output says "N"?
Update the examples as mentioned above.

**698**
Same confusion as 697. What exactly is this task considering positive/negative?
Definition changes- "Construct evidence"
Category- Answer Generation
Update the examples as mentioned above.

**699, 700**
Update the examples as mentioned above.

**Comment by devshree07** [comment]
> Update the README to put the tasks in order. If the category has changed, update the category too here.
> 
> For all the tasks, I think you've confused what a negative example means.
> 
> Positive Examples:
> Model answers true and correct answer is true
> Model answers false and correct answer is false
> 
> Negative Examples:
> Model answers true, but the correct answer is false
> Model answers false but the correct answer is true
> 
> Update your positive and negative examples accordingly for all the tasks. Negative examples are when the answer is completely incorrect. Not false or no or etc. options.
> 
> **697**
> Is the task a sentiment analysis classification task? Your explanations in the examples: "The evidence generated is a positive example as it contains words/phrases from review and is unambiguous." this isn't making it clear what your task is doing? Also, in the positive examples, your explanation says it's positive, but your output says "N"?
> Update the examples as mentioned above.
> 
> **698**
> Same confusion as 697. What exactly is this task considering positive/negative?
> Definition changes- "Construct evidence"
> Category- Answer Generation
> Update the examples as mentioned above.
> 
> **699, 700**
> Update the examples as mentioned above.

Thank you for the review. I have understood the meaning of positive and negative examples but in case of task 697 and 698, the issue is that the dataset "Movie Rationales" only consists of negative reviews labelled as 0. Thus, I will change the output to labels accordingly. 

Also, for the task 699-700, I have taken classification task, wherein if lexical overlap happens and output itself has the lexical overlap, I classify it as 'Yes'. And in task 700, it goes same for entailment.

**Comment by aarunku5** [comment]
For **697**, download the dataset from this link: http://www.eraserbenchmark.com/zipped/movies.tar.gz
Go to the train.jsonl file, you will have both positive and negative reviews annotated. In the jsonl file, you have the "text" field which will be the substring used to classify the review, "classification" as POS/NEG, and from he docs folder, you can retrieve the full reviews corresponding to the "doc_id" field in the jsonl.

You need to update the definition for 697 as:
"In this task, you must classify if a given review is positive/negative, indicating your answer as \"P\" or \"N\"."

Also, your outputs in the instances and examples must be 'P' or 'N'. Not 0s.

The positive and negative example explanations must be: "The phrases used in  the review convey a positive (or negative) sentiment." 

**698** looks good

*699**
Please correct your negative examples. Currently, you have:

{
"input": "Premise: The tourists advised the managers and the senator ., Hypothesis: The tourists advised the managers .",
"output": "No",
"explanation": "The hypothesis is a sub-string of premise."
}

This is not a negative example. The hypothesis is a substring of the premise, so the answer provided, "No" is a correct answer. Therefore the example is positive. It shows how a correct answer should be arrived at. You need to update as:

{
"input": "Premise: The tourists advised the managers and the senator ., Hypothesis: The tourists advised the managers .",
"output": "Yes",
"explanation": "The hypothesis is a sub-string of the premise, so there is no lexical overlap. Therefore the answer should be 'No'."
}

Update the other negative example in the same manner.

**700**

In your first negative example:

{
            "input": "The judge encouraged the athlete .",
            "output": "The athlete encouraged the judge .",
            "explanation": "The premise and the hypothesis have entailment and thus hypothesis generated is not correct."
}

The two statements here are not entailed. Change the hypothesis to make them agree so it is a negative example.

**Comment by swarooprm** [comment]
@devshree07, I see several problems with your tasks and the reviewer comments are also not addressed (e.g. look at negative examples, they are not changed as per the reviewer comments).
- Task697 is incorrect because instances only contain negative labels.
- Explanations are generic and are not specific to the specific examples.
- I am not sure if labels are balanced across the output field of instances in other classification tasks (699)

I understand that you had other deadlines, so I am ready to give you extra time. 
Please let me know if you plan to fix those or not and I will grade accordingly.
In order to do a fair evaluation to other students who have created valid tasks, I might have to deduct points if you don't plan to fix your tasks.  

Let me know if you have any question.

**Comment by devshree07** [comment]
Hi Swaroop,
As mentioned by me earlier, the dataset for tasks - 697 and 698 did not have the positives (1)s originally. I was informed to work on a new dataset by the reviewer after the deadline. I hope you understand that it is a cumbersome task for me to start it all over again. Again, I hope that you can consider task 697 as submitted by me on the day before the deadline.

For, task 699, the labels are balanced and I can show my script to you for the same. Regarding, the explanations, I have changed according to the reviewer. 

Lastly, you can deduct my marks for the negative examples which were not changed by me as I am not certain how to make my hypothesis more meaningful.

I hope you will understand the scenario from my side and grade my assignment accordingly. Thank you.

**Pull request closed without merging**
