### PR TITLE
Mirali: Task 49-56: LAMBADA chr_en newspop

### PR DESCRIPTION
**Pull request by drocobeth**

### CODE REVIEW

**Comment by swarooprm** [comment]
@Mirzyaaliii, wondering if you can help review this PR?

**Comment by Mirzyaaliii** [comment]
- General comments -
1. Filename should be in lowercase.
2. In the source field, keep only 1 element in the list.  For example, check Task-300 [here](https://github.com/allenai/natural-instructions-expansion/tree/master/tasks).
3. Category should be list.
4. In the README, write the tasks in order.
5. In the definition where _Things TO Avoid_ and _Emphasis & Caution_ are empty, remove it.
6. Change the following categories (in the README and inside the JSON file)
 Task049: Next Sentence Generation -> Sentence Generation
 Task050: Final Word Generation -> Text Generation (change filename to task050_lambada_last_word_text_generation)
 Task051: Topic Classification -> Classification
 Task054: Title Generation -> Text Generation (change filename to task054_newspop_title_text_generation)
 Task055: Language Translation -> Translation
7. Elaborate summary for all the tasks in the README. (For your reference check the summary of few tasks [here](https://github.com/allenai/natural-instructions-expansion/tree/master/tasks).)
8. Correct grammar and typos in the definition and explanation from all the tasks. For example,

> The title and headline **tals abotu** economy. Therefore, this **shpuld** be labelled in \"economy\" category. 

> The title and headline talks about Obama and **H=hence** it should be classified into 'obama' category. 

9. make sure your definition is concise, clear and do not have repetition. (For your reference check the definition of few tasks [here](https://github.com/allenai/natural-instructions-expansion/tree/master/tasks).)
Also, for example, check this definition for Task-051
`You are given a title and a headline from multiple news sources. Your task is to classify this headline into the following 4 categories: Obama, Economy, Microsoft, and Palestine.`
10. From the explanation, remove extra space
`"explanation": "... about i.e. signs. "`
11. Remove special character wherever it is. For example,

> "input": "Headline: The US economy added 160,000 **\u00a0** jobs in April, fewer **\u00a0** than expected, as the unemployment rate held steady at 5%. Economists had forecast that nonfarm payrolls grew by 200,000, and that the unemployment rate fell to 4.9%. **\u00a0** Construction companies and retailers cut back on hiring as the mining sector continued to bleed jobs. **\u00a0** **&quot**; The data suggests that US investment in labor has not completely decoupled ",

- Task - 049
1. In the input of the first example _Passage:_ is missing. I think it is fine if you don't write _Passage:_ in every input, just remove it because there is only a single entity in the input.

- Task - 055
1. Why there are special characters in place of the Cherokee language in the whole file? Files are not properly saved.
Write this while saving your JSON
`json.dumps(your_dict, ensure_ascii=False, indent=4)`
2. Write 2 letter short-form of the languages in the filename which are included in your tasks. For example,
`task055_chren_ck_en_translation`
where _ck_en_ indicates Cherokee to English.
3. Check tasks 312 [here](https://github.com/allenai/natural-instructions-expansion/tree/master/tasks) and change all things (filename, definition, summary in the README) and add Input_language, Output_language, Instruction_language.
4. Also, you can create (if you want) other 3 tasks same as tasks 313-315 on the above link.

**Comment by swarooprm** [comment]
@drocobeth, can you address reviewer comments so that I can evaluate your HW?

**Comment by swarooprm** [comment]
> @drocobeth, can you address reviewer comments so that I can evaluate your HW?

A Gentle Reminder @drocobeth

**Comment by Mirzyaaliii** [comment]
@drocobeth Once you complete **all the changes**, drop a comment here and if you have any suggestions or doubts on any comment mention here.

**Comment by drocobeth** [comment]
Hello @Mirzyaaliii @swarooprm   , I did not receive any updates on my email and hence I wasn't able to know that the review has been done. However, I have now seen it. Please give me a little time to correct all the things that have been mentioned. I am extremely sorry for the inconvenience caused.

**Comment by drocobeth** [comment]
Hello @Mirzyaaliii @swarooprm , I modified the JSON files as per the suggestions and addressed all the issues. However regarding task 55 when **I am encoding the JSON file with esnure_ascii=False since Cherokee characters does not have any ascii values**, the testing script throws an **UnicodeDecodeError**. Now, I don't understand how can I pass the test script if I save my json file with ensure_ascii=False. Please, kindly look into this. 

Regarding the other issues, I have addressed all of them.

**Comment by drocobeth** [comment]
Hello @Mirzyaaliii @swarooprm,
I changed the JSON files as per the suggested review

1. Filename was converted in lowercase.
2. In the source field, only 1 element was kept as in Task300.
3. Tasks were written in order.
4. Things To Avoid and Cautions were removed where they were empty.
5. Categories were changed in both JSON and README as suggested.
6. Summary was elaborated fir each task in Readme File.
7. Grammar and typos were corrected in definition and explanation.
8. Definitions were made concise, non-repetitive.
9. Special characters were removed from all the JSON files except the Cherokee to English one as the Cherokee language has only special characters.
10. Trailing, leading and multiple spaces were removed.
11. "Passage:" was removed before every sentence in task 049 and task 055 was saved with ensure_ascii=False and input, output, and instruction language field was added for task 055.

**Comment by swarooprm** [comment]
> Hello @Mirzyaaliii @swarooprm, I changed the JSON files as per the suggested review
> 
> 1. Filename was converted in lowercase.
> 2. In the source field, only 1 element was kept as in Task300.
> 3. Tasks were written in order.
> 4. Things To Avoid and Cautions were removed where they were empty.
> 5. Categories were changed in both JSON and README as suggested.
> 6. Summary was elaborated fir each task in Readme File.
> 7. Grammar and typos were corrected in definition and explanation.
> 8. Definitions were made concise, non-repetitive.
> 9. Special characters were removed from all the JSON files except the Cherokee to English one as the Cherokee language has only special characters.
> 10. Trailing, leading and multiple spaces were removed.
> 11. "Passage:" was removed before every sentence in task 049 and task 055 was saved with ensure_ascii=False and input, output, and instruction language field was added for task 055.

@Mirzyaaliii, let me know if you are happy or have any other feedback for @drocobeth ?

**Comment by Mirzyaaliii** [comment]
All things look good to me, just a few minor comments.

- General comments -
1. Keep the space before **\n**, because there is space somewhere and somewhere not. Keep space before and after \n in every task wherever it is.
2. There are few grammatical errors in the explanation and definition. So, please once pass it on the Grammarly (or a similar tool). Hence, there will be no grammatical, punctuation, spacing, etc errors.

- Task - 055
1. Do not mention Cherokee and English in input and output, respectively. Directly write the sentence as shown below:
```
"input": "ᎠᎴ ᎾᏍᎩ ᏅᏗᎦᎵᏍᏙᏗᎭ ᏂᎦᏛ ᎠᏃᎯᏳᎲᏍᎩ ᎠᎾᏚᏓᎴᎭ ᏂᎦᎥ ᏧᏓᎴᏅᏛ, ᎾᏍᎩ ᎨᏣᏚᏓᎳᎡᏗ ᏂᎨᏒᎾ ᏥᎨᏒ ᎼᏏ ᎤᏤᎵ ᏗᎧᎿᏩᏛᏍᏗ ᏕᏥᎧᎿᏩᏗᏒ ᎢᏳᏍᏗ.",
"output": "and by him every one that believeth is justified from all things, from which ye could not be justified by the law of Moses.",
```

@swarooprm Once check the task 052, 052 and 056 as these tasks are regression, if these are valid or not.

**Comment by swarooprm** [comment]
grading complete.

**Pull request closed without merging**
