### PR TITLE
Swaroop: Tasks 601-605: GCWD and gap

### PR DESCRIPTION
**Pull request by selvagmj**
Please review these tasks.

### CODE REVIEW

**Comment by nrjvarshney** [comment]
I'll review this one. 
@swarooprm

**Comment by nrjvarshney** [comment]
Task 601 - 
* Try to make the definition slightly more simple/readable. 
* Give an example of neutral also.

Task 602 - 
* Remove this from the definition "A passage strongly agrees with target when the probability of agreement is than 0.7."
* Do all the sentences support (strongly or weakly) the target sentiment? Is there no neutral class like Task 601?

Task 603- 
* You can shorten the task definition (The task can be explained with fewer sentences). Specify what is pronoun offset.
* In the input, after the pronoun use a comma as the separator 
* Have only the name in the output (without the prefix "Name"), as it would be difficult to evaluate (if only the offset matches but not the same or vice versa). Actually, even with that it would slightly tricky to evaluate when the model output only the first name. One option to eliminate such cases is to convert this task to a multiple-choice QA type. 
* Verify your negative examples. Seems incorrect

Task 604 - 
* Same comments as above
* Specify the pronoun possibilities 
* Is case important here?
* Improve the explanation - "The 'also' mentioned next to 'he' shows" --> "The word 'also' mentioned next to the word 'he' ...."
* Improve the explanation in terms of content also. Write the primary reason.

Task 605 - 
* Improve the task definition. You don't need to write short sentences. Mention the actual task first and then provide the details. 
* For blank, use only one character instead of '_____ '.
* Look at the comments from previous tasks.

**Comment by selvagmj** [comment]
Task 601 - Changed the definition. Added a neutral positive example.
Task 602 - Deleted this task since it just used a part of dataset
Task 603 - Changed the definition. 
		    Used comma as pronoun separator
		    I have not deleted the name offset since if delete the offset it would be difficult to identify for which name the pronoun corresponds to. The same name could be repeated in several places in the passage.
		    Corrected the negative example
Task 604 - Added pronoun possibilities. Added case criteria in definition. Improved the explanations.
Task 605 - Improved the task definition. Changed blank usage to 1 character.

**Comment by nrjvarshney** [comment]
Task 603-
* I was referring to the answer offset not the pronoun offset

Task 604 -
* Why is pronoun offset is required in the answer
* Also define the offset --> is it word offset or character offset 

Task 605 -
* All the examples are of "her" class. Give other class examples also
* The task definition is verbose, grammatically incorrect, and difficult to follow. It can be simplified

**Comment by swarooprm** [comment]
@selvagmj, can you address reviewer comments so that I can evaluate your HW?

**Comment by selvagmj** [comment]
@swarooprm I will update the tasks and push the changes by today evening.

**Comment by selvagmj** [comment]
I have updated the tasks.

**Comment by nrjvarshney** [comment]
* "Categories" should be a list. please refer to the JSON format
* prefix "Name : " is not needed in the output. Think what a human would output for such as task.
* Similarly "pronoun: "  is not needed
* " The output should include the pronoun only" seems redundant

**Comment by swarooprm** [comment]
@selvagmj can you address reviewer comments?

**Comment by selvagmj** [comment]
Removed "name" and "pronoun" from output. Removed redundant definition. For the "Categories" the example is like this,
image
It is given as "Categories": "Question Generation" . Did you mean something else?

**Comment by swarooprm** [comment]
Your tasks look good. Categorie should be a list e.g. https://github.com/allenai/natural-instructions-expansion/blob/master/tasks/task003_mctaco_question_generation_event_duration.json
One comment:
- make sure classes are balanced in the classification task. Also, shuffle the instances.

Once you do the above change, your HW2 will be complete.

**Comment by selvagmj** [comment]
@swarooprm Made the changes.

**Comment by swarooprm** [comment]
Your HW2 is complete now.

Would you like to submit the same tasks to our big project repo https://github.com/allenai/natural-instructions-expansion/pulls? You just need to fork that repo, rename tasks starting from the latest number in the repo and create PR there. This way, you can be part of our research on "learning from instructions instead of learning from examples (conventional machine learning)". This is purely optional and your HW2 grade does not depend on this @selvagmj

**Comment by swarooprm** [comment]
@selvagmj Just a reminder that, if you plan to submit these tasks to the main Github repo and join our research project, Monday (27th Sept) is the deadline. Again, this is optional and independent of your HW2 grade.

**Comment by selvagmj** [comment]
Yes, I like to submit these tasks to main repo. I have created a fork. Will raise the PR soon.

**Pull request closed without merging**
