### PR TITLE
Tasks 57-64 Done-Please review

### PR DESCRIPTION
**Pull request by BhavyaSri1001**

### CODE REVIEW

**Comment by swarooprm** [comment]
@yeganehkordi, wondering if you can help review these tasks?

**Review by yeganehkordi — COMMENTED** [review]
Thanks for your work!
Some general comments about the tasks:
1. Please provide the link to the dataset and paper in the source field.
2. Elaborate the tasks clearly in the definition. Anyone should be able the complete the task correctly by just reading the definition and instructions.
3. Make sure that the distribution is not skewed toward a class.
4. Mention the explanation of X and Y in the definition.

Task 57:
- I think the better category for this task is answer generation.
- Based on the definition, this task seems to be a classification task into relevant and irrelevant. But I guess it is about writing a plausible answer for the question. Please explain that there are many correct answers, but we only need one.
- Correct the verb tenses in the second example.
- Change `related to question` to `related to the question`.

Task 58:
- Actually, this task is a classification task.
I think you can simplify this task by saying: `given two sentences, check if they have the same meaning.`
- Maybe format the input as: sentence1 <sep> sentence2
- Having five outputs doesn't make sense to me. Maybe you can consider the output with the most occurrence as the final output.
- `As Y did not reach till the 12th chapter`: your explanation should be based on the input. We know nothing about chapter 12 here.
Try to have at least one example with a "no" label in the positive examples and one with the wrong "no" label in the negative ones.

Task 59:
- I think the better category for this task is text generation.
- Please elaborate more on the definition of the context. Here is an example that came to my mind. You can make it much better: "In this task, you are given a question, and you have to predict the context of the question. The context of the question refers to the previous talks and situation that lead us to this question."
- Make the explanation of the first example grammatically correct.

Task 60:
- Change `The question asked was if he like` to `The question asked was if he liked` i the second example.
- Maybe replace `while the answer was regarding a villa` to `while the answer is regarding a villa` in the third example.
- Change `some place` to `someplace` in the fourth example.

Task 61, 64:
- I think anyone should be able to solve the tasks. And I'm not sure about these tasks!
    @swarooprm I'd like to know your point of view about these tasks.
- I think "Text generation" is a better category.
- Your explanations in task 64 seem to be mistaken.
- We should have at least one output for each instance. Please remove the instances without the output.

Task 62, 63:
- Please explain about the Ner generation in the definition.
- I think you can make the explanation more concise.
- "Ner generation" is enough for the category field. We add the extra information in the definition.

Please update the README based on the above comments.

**Comment by BhavyaSri1001** [comment]
I have made the changes now. Please check.

Thanks and Regards,
Bhavya Sri Aravapalli.

**Comment by swarooprm** [comment]
@yeganehkordi, thanks for your review. I think task 61 and 64 are ok at this point, we might need to keep it in training split while bulding the final dataset. Please check and let me know if you are happy with the revisions or if you have any other suggestion

**Comment by yeganehkordi** [comment]
Thanks! I'll review these tasks again in the allenai repo.

**Comment by swarooprm** [comment]
Closing this as this is getting reviewed in the Allen Ai repo

**Pull request closed without merging**
