### PR TITLE
Swaroop: Task 769-776: OPP-115, HopeEDI, Ollie Datasets

### PR DESCRIPTION
**Pull request by sskp-kaushik**

### CODE REVIEW

**Comment by swarooprm** [comment]
Hi @sskp-kaushik, your tests are failing. Can you fix your files so that tests pass and we can start evaluating your HW.

**Comment by sskp-kaushik** [comment]
> Hi @sskp-kaushik, your tests are failing. Can you fix your files so that tests pass and we can start evaluating your HW.

Hi Swaroop, I'm so sorry fixing it now will make a pull request

**Comment by sskp-kaushik** [comment]
@swarooprm Hi Swaroop. I fixed the issues and tested on my side. Seems good. Sorry for the mess.

Thanks,
Kaushik

**Comment by swarooprm** [comment]
Your tasks look really good, some minor feedback:
task769-shuffle your instances.
task770-explanations are too generic and look same, paraphrase some of those.
In classification tasks, make sure that labels are balanced.

Let me know once you fix these @sskp-kaushik

**Comment by sskp-kaushik** [comment]
Hi @swarooprm,

1. I have shuffled the instances in task769
2. I have changed the explanations for tasks - 769, 770, 771 paraphrased the explanation
    Eg : Positive Example Explanation - "The generated sentence contains the two given subjects - you and me, and have the 
    given relationship - talk, between them"
    Negative Example Explanation - "The generated sentence contains the two given subjects - I and name, but they are not 
    related to each other on the basis of the given relationship - enter"
3. I have balanced the classification tasks datasets (Hope EDI) as much as possible for tasks - 772, 773, 774. There are very few data records for some of the classes like 22 records, had to balance on the other classes and have all the 22 data records of the third class. Is that ok? If not could you suggest a way to balance those records?

Please review the changes and let me know if any other corrections are to be made.

**Comment by swarooprm** [comment]
Everything looks good except the data balance thing.
3. We can't do anything here as at least 100 instances are required. 

Your HW2 is complete now.

Would you like to submit the same tasks to our big project repo https://github.com/allenai/natural-instructions-expansion/pulls? You just need to fork that repo, rename tasks starting from the latest number in the repo and create PR there. This way, you can be part of our research on "learning from instructions instead of learning from examples (conventional machine learning)". This is purely optional and your HW2 grade does not depend on this @sskp-kaushik

**Comment by sskp-kaushik** [comment]
Hi @swarooprm I see there is gap in the task numbering (582 and then 607) in the allenai repository. With which number do I start for naming the tasks?

**Comment by swarooprm** [comment]
The latest pull request has number has 675 (https://github.com/allenai/natural-instructions-expansion/pull/296), please name your task from 676.

**Comment by sskp-kaushik** [comment]
@swarooprm, created a pull request in allenai repository : [https://github.com/allenai/natural-instructions-expansion/pull/315](url). Thanks.

**Pull request closed without merging**
