### PR TITLE
Anjana: Task 329 - 332: acronym_identification, doc2dial

### PR DESCRIPTION
**Pull request by akshatj427**
Hi @swarooprm,
I have added four task. Can you please review it when possible.
Thanks.

### CODE REVIEW

**Comment by swarooprm** [comment]
@SavanDoshi, wondering if you can help review this PR?

**Comment by swarooprm** [comment]
@yeganehkordi, wondering if you can help review this PR?

**Comment by aarunku5** [comment]
Thanks!

Rename the PR as 329-332.

Include the web link for the dataset as part of the source for all tasks.

329- Change to "predicting" and "in which case you must output". This text: "Please note that the output should be the acronym not the long form of the acronym." should be in the definition and not the explanations.

330- Looks good

331- Change to "You are given the...", "the user and second dialogue is by the agent", "two consecutive dialogues may be said by the user". Typo "dispursement" in the example output. 

332- Include "the" in front of user as mentioned for 331.

**Comment by akshatj427** [comment]
Hi,
I have made changes to the tasks as suggested, Please check if they are ok now.

Thanks
Akshat

**Comment by swarooprm** [comment]
> Hi,
> I have made changes to the tasks as suggested, Please check if they are ok now.
> 
> Thanks
> Akshat

@aarunku5, check if you are happy or have any other comment?

**Comment by aarunku5** [comment]
Looks good to me @swarooprm

**Comment by swarooprm** [comment]
Your HW2 is complete now.

Would you like to submit the same tasks to our big project repo https://github.com/allenai/natural-instructions-expansion/pulls? You just need to fork that repo, rename tasks starting from the latest number in the repo and create PR there. This way, you can be part of our research on "learning from instructions instead of learning from examples (conventional machine learning)". This is purely optional and your HW2 grade does not depend on this @akshatj427

**Comment by swarooprm** [comment]
@akshatj427 Just a reminder that, if you plan to submit these tasks to the main Github repo and join our research project, Monday (27th Sept) is the deadline. Again, this is optional and independent of your HW2 grade.

**Pull request closed without merging**
