### PR TITLE
Tasks 457-460 emo and aquamuse dataset.

### PR DESCRIPTION
**Pull request by kurbster**

### CODE REVIEW

**Comment by kurbster** [comment]
The aquamuse tasks do have some unicode characters. I didn't know if that was ok or not.

**Comment by swarooprm** [comment]
1. task459: you can delete "that was asked"
2. make sure that labels are balanced in the classification tasks.

Once you fix these, I am going to accept your tasks and your HW2 will be complete.

Also, Would you like to submit the same tasks to our big project repo https://github.com/allenai/natural-instructions-expansion/pulls? You just need to fork that repo, rename tasks starting from the latest number in the repo (which at this point is 489) and create PR there. This way, you can be part of our research on "learning from instructions instead of learning from examples (conventional machine learning)". This is purely optional and your HW2 grade does not depend on this @kurbster

**Comment by kurbster** [comment]
Task457 all classes have 1625 instances.
Task458 has 3338 'yes' answers and 3162 'no'.
Task460 has 526 'True' answers and 474 'False'.

**Comment by swarooprm** [comment]
Your hw2 is complete now, just note that you have the option to create a PR in big project repo https://github.com/allenai/natural-instructions-expansion/pulls with these tasks.

**Pull request closed without merging**
