### PR TITLE
Anjana: Tasks 001-007: Sick and cc-aligned datasets

### PR DESCRIPTION
**Pull request by vidyaakkiraju**

### CODE REVIEW

**Comment by swarooprm** [comment]
@ kurbster, wondering if you can help review these tasks?

**Comment by swarooprm** [comment]
@aarunku5, wondering if you can help review these tasks?

**Comment by kurbster** [comment]
I can take a look at this.

**Comment by aarunku5** [comment]
Include the dataset web link in the source field for all tasks.

Also, update the readme where applicable, and put all your definitions/explanations for all tasks through Grammarly before resubmitting. Ensure everything has proper capitalization and punctuation as well.

**001**

Definition: "entailed or contradict each other, otherwise labeled neutral"
This isn't very clear, rephrase it a bit.
Also, rephrase the second line to be along the lines of "Your output format should be..."

There are some typos and grammatical errors in your explanations, please correct those.

**002**

Expand your definition to specify what entailment and contradiction mean.
Fix grammatical errors and typos in your explanations.

**003*

Elaborate on what you mean by "a sentence similar to that in the input" in the definition, and rephrase to make it clearer.
Avoid using phrases like 'kind of' in the explanation. Some typos and grammatical errors to fix here.

**004**

Typos in the definition. Reword the second line to make it more concise.
Some typos and grammatical errors in the explanations.

**005, 006, 007**

Don't have the character codes, the text needs to be in Telugu characters.
Also, make sure you have at least 2 positive and 2 negative examples.

**Comment by swarooprm** [comment]
> I can take a look at this.

You can ingore this.

**Comment by swarooprm** [comment]
@vidyaakkiraju, can you address reviewer comments so that I can evaluate the HW?

**Comment by vidyaakkiraju** [comment]
Hi Swaroop,

I didn't see these comments before. Will address them today.

Thanks,
Vidya

**Comment by vidyaakkiraju** [comment]
@aarunku5, @swarooprm  I have updated the tasks as per the comments, please review

**Comment by swarooprm** [comment]
> @aarunku5, @swarooprm I have updated the tasks as per the comments, please review

@aarunku5, check if you are happy with the changes or have any other feedback?

**Comment by aarunku5** [comment]
**001**
Change definition to this:
In this task, you're given a pair of sentences, sentence 1 and sentence 2. Your job is to choose whether the two sentences clearly agree (entailment)/disagree (contradiction) with each other, or if this cannot be determined (neutral). Your answer must be in the form of the letters 0 (entailment), 1 (neutral), or 2(contradiction).

**002**
Change defintion to this:
In this task, you are given a sentence and a category word that defines the relation between the input sentence and the output to be generated. Your job is to generate another sentence that satisfies the relation specified by the category. If the category is specified as entailment, then the output sentence must clearly agree with the input sentence. If the category specified is contradiction , then the output sentence must clearly disagree with the input sentence.

**003**
Change defintion to:
In this task, you must modify the text given in the input to generate a paraphrased sentence. Your output sentence must retain the same meaning, but does not necessarily have to include all the details  as the input text. 

**004**
Change defintion to:
In this task, given 2 input sentences, you must classify the relation  between them. If the second sentence has a similar meaning to that of the first sentence then the output is ' B_entails_A', if the second sentence has the opposite meaning to the first sentence then it is classified as ' B_contradicts_A'. If you cannot clearly ascertain agreement/disagreement between the two sentences, the label is ' B_neutral_A'.

**005-007** Looks good

**Comment by swarooprm** [comment]
> **001**
> Change definition to this:
> In this task, you're given a pair of sentences, sentence 1 and sentence 2. Your job is to choose whether the two sentences clearly agree (entailment)/disagree (contradiction) with each other, or if this cannot be determined (neutral). Your answer must be in the form of the letters 0 (entailment), 1 (neutral), or 2(contradiction).
> 
> **002**
> Change defintion to this:
> In this task, you are given a sentence and a category word that defines the relation between the input sentence and the output to be generated. Your job is to generate another sentence that satisfies the relation specified by the category. If the category is specified as entailment, then the output sentence must clearly agree with the input sentence. If the category specified is contradiction , then the output sentence must clearly disagree with the input sentence.
> 
> **003**
> Change defintion to:
> In this task, you must modify the text given in the input to generate a paraphrased sentence. Your output sentence must retain the same meaning, but does not necessarily have to include all the details as the input text.
> 
> **004**
> Change defintion to:
> In this task, given 2 input sentences, you must classify the relation between them. If the second sentence has a similar meaning to that of the first sentence then the output is ' B_entails_A', if the second sentence has the opposite meaning to the first sentence then it is classified as ' B_contradicts_A'. If you cannot clearly ascertain agreement/disagreement between the two sentences, the label is ' B_neutral_A'.
> 
> **005-007** Looks good

@vidyaakkiraju, can you address reviewer comments so that I can evaluate your HW?

**Comment by vidyaakkiraju** [comment]
@aarunku5 , @swarooprm Made the necessary changes, Please review task 001 to 004

**Comment by aarunku5** [comment]
@swarooprm Looks good to me

**Comment by swarooprm** [comment]
Your HW2 is complete now.

Would you like to submit the same tasks to our big project repo https://github.com/allenai/natural-instructions-expansion/pulls? You just need to fork that repo, rename tasks starting from the latest number in the repo and create PR there. This way, you can be part of our research on "learning from instructions instead of learning from examples (conventional machine learning)". This is purely optional and your HW2 grade does not depend on this @vidyaakkiraju

**Comment by swarooprm** [comment]
@vidyaakkiraju Just a reminder that, if you plan to submit these tasks to the main Github repo and join our research project, Monday (27th Sept) is the deadline. Again, this is optional and independent of your HW2 grade.

**Pull request closed without merging**
