### PR TITLE
Complete:Tasks 281-285: MOCHA and CUAD datasets

### PR DESCRIPTION
**Pull request by akhilkumargudipoodi**

### CODE REVIEW

**Comment by swarooprm** [comment]
@aarunku5, wondering if you can help in reviewing these tasks?

**Comment by akhilkumargudipoodi** [comment]
@swarooprm , @aarunku5  Can you please review my tasks and let me know if any changes are required?

**Comment by aarunku5** [comment]
**281**
Change Definition:
 'In this task, you're given a context passage, followed by a question that needs to be answered.  You must write unambiguous answers to the questions based on the paragraph that correspond to a phrase from the paragraph. If multiple answers seem to exist, write the answer that is the most plausible.'

**282**
Change Definition:
'In this task, you're given a context passage. Your job is to generate relevant questions that can be answered by directly referring to the passage.'

**283**
Change Definition:
'In this task, you're given a passage that represents a legal contract or clause between multiple parties, followed by a question that needs to be answered. You must write unambiguous answers to the questions based on the paragraph that correspond to a phrase from the paragraph. If multiple answers seem to exist, write the answer that is the most plausible.'
Negative Example #1:
"Don't write unnecessary information as a part of the answer."--> change this to: "There is unnecessary information in the answer"

**284**
Change Definition:
"In this task, you're given a passage that represents a legal contract or clause between multiple parties, followed by a question that needs to be answered. You must write the index where the answer starts based on the paragraph. If multiple answers seem to exist, write the index of the answer that is the most plausible."

**285**
Change Definition:
"In this task, you're given a passage that represents a legal contract or clause between multiple parties. Your job is to write questions that ask the basic details corresponding to the legal contracts or clauses. Avoid questions that can be answered correctly without actually understanding the paragraph, and which might have multiple answers. The answer to each question should be unambiguous."
Also in this task, can you clarify why you're structuring the output as a "Highlight... Details: ..."?

**Comment by akhilkumargudipoodi** [comment]
@aarunku5 Appreciate your detailed review of my tasks!!

With respect to **Task-285**, my output is structed as "Highlight... Details: ...". This is because all the instances from the dataset are in the same manner. So, while writing the examples, I adopted the same style / approach.

**Comment by aarunku5** [comment]
Akhil can you confirm that the repo is updated? I'm not seeing the changes.

Also for task 284, change the category to just "Answer Generation"

**Comment by akhilkumargudipoodi** [comment]
@aarunku5 The repo has been updated. Please let me know in case any additional modifications are required.

**Comment by aarunku5** [comment]
The tasks look good 👍
Just update the readme-- change 284 to Answer Generation, and list the tasks in order.

**Comment by akhilkumargudipoodi** [comment]
Updated the README and listed the files in order. Changed Task-284 to Answer Generation.

**Comment by aarunku5** [comment]
Thanks, @swarooprm it looks good to me

**Comment by swarooprm** [comment]
Your HW2 is complete.

Would you like to submit the same tasks to our big project repo https://github.com/allenai/natural-instructions-expansion/pulls? You just need to fork that repo, rename tasks starting from the latest number in the repo (which at this point is 591) and create PR there. This way, you can be part of our research on "learning from instructions instead of learning from examples (conventional machine learning)". This is purely optional and your HW2 grade does not depend on this @akhilkumargudipoodi ?

**Comment by akhilkumargudipoodi** [comment]
@swarooprm I would like to submit the tasks to the big project repo. I have created a pull request to that repo. Let me know in case of any further queries or concerns.

**Comment by swarooprm** [comment]
> @swarooprm I would like to submit the tasks to the big project repo. I have created a pull request to that repo. Let me know in case of any further queries or concerns.

Thanks :)

**Pull request closed without merging**
