### PR TITLE
Swaroop: Task 577-583: financial_phrasebook, pubmed_QA Dataset

### PR DESCRIPTION
**Pull request by JalanshMunshi**
`task577_financial_phrasebank_classification` | Classifying news into positive, neutral, and negative (based on financial_phrasebank) | Classification
`task578_financial_phrasebank_classification` | Classifying if (news, polarity) is valid or not (based on financial_phrasebank) | Classification
`task579_pubmedQA_question_generation` | Generating question from context and answer (based on pubmed_QA) | Question Generation
`task580_pubmedQA_classification` | Classifying if the given answer pertains to the question or not (based on pubmed_QA)| Classification
`task581_pubmedQA_question_generation` | Generating question from context (based on pubmed_QA) | Question Generation
`task582_pubmedQA_classification` | Classifying if the objective is present or not (based on pubmed_QA) | Classification

### CODE REVIEW

**Comment by JalanshMunshi** [comment]
I understand that "output" inside instances should be a list. I have done that change in 2 of the files on my local machine. Will push the remaining changes soon.

**Comment by swarooprm** [comment]
Update: Reviews performed during the office hour today.

**Comment by JalanshMunshi** [comment]
@swarooprm Please review the tasks. I have modified the tasks after our discussion in the morning and added two new tasks.

**Comment by Mihir3009** [comment]
@swarooprm I am reviewing this task.

**Comment by swarooprm** [comment]
@JalanshMunshi,
- What is the difference between task 579-581 and 580-582?
- In case of question generation, if you have multiple questions per passage, make sure to append them all and make it a list in case of instances, positive examples still need to contain only one question.
- You can create an answer generation task where given a question, model needs to generate answer
Other things look good.

**Comment by JalanshMunshi** [comment]
@swarooprm 
The pubmed_QA dataset has the fields 'Question', 'Context', 'Answer', and 'Labels'.

### Answer to Point 1

Task 579 generates a question from the Context and the Answer. 
Task 581 generates a question just from the context.

We discussed this during your office hours and you raised the same questions about task 579. I went through a few instances in the dataset and felt that few answers cannot be answered only from the context or answer. In particular, I feel that it is very difficult to form a question from the answer itself. We definitely need the context and the answer would help the model more. 

That is why I formulated both tasks. 

Task 580 classifies if the given answer actually answers the question or not. 
Task 581 basically uses the fields 'Context' and 'Labels' from the dataset. If there is an objective in the context, then the 'Labels' array will have a tag named 'Objective' in it. I am classifying if the given context has a definite objective in it or not.

### Answer to Point 2

My question generation tasks only generate one question. 

### Answer to Point 3

This is a good suggestion and I will try to push it soon. I am currently working on the homework and I will push this new task as soon as I can. Is there a deadline that you have to maintain? If yes, please let me know so that I can keep that in mind.

**Comment by swarooprm** [comment]
Fine. I plan to finish grading HW2 of all students this week, so sooner is better.

**Comment by JalanshMunshi** [comment]
Got it. I will try to push it by Tuesday. Thank you for your suggestions!

**Comment by JalanshMunshi** [comment]
Hi @swarooprm ,

I have added a new task. Please note that I have considered the context and question for the input here. 

If you have a look at the dataset, I feel that it is not possible to generate the answer from the question alone. We need the context and the question in order to generate an answer.

However, if you have a different opinion, then please let me know. I can push another task that will the question as input and answer as the output.

**Comment by swarooprm** [comment]
Everything looks good except my second comment:

> In case of question generation, if you have multiple questions per passage, make sure to append them all and make it a list in case of instances, positive examples still need to contain only one question.


Look at task001 here https://github.com/allenai/natural-instructions-expansion/blob/master/tasks/task001_quoref_question_generation.json

See that multiple questions are added as list in instance outputs, this is also needed for your question generation task(s).

Note that, instances are for evaluation. Output in instances should cover all questions generated from a passage for a reliable evaluation. 
Your task can ask  model to generate one question, positive examples also should have 1 question as output, just the instances would change (similar to task001 above)

This is my last comment. Once you fix this, your HW will be complete. @JalanshMunshi

**Comment by swarooprm** [comment]
@JalanshMunshi, can you address the comments so that I can grade your HW?

**Comment by JalanshMunshi** [comment]
@swarooprm 

My dataset only has one question per passage/instance.

This is how the dataset looks. 

```
"25429730": {
        "QUESTION": "Are group 2 innate lymphoid cells ( ILC2s ) increased in chronic rhinosinusitis with nasal polyps or eosinophilia?",
        "CONTEXTS": [
            "Chronic rhinosinusitis (CRS) is a heterogeneous disease with an uncertain pathogenesis. Group 2 innate lymphoid cells (ILC2s) represent a recently discovered cell population which has been implicated in driving Th2 inflammation in CRS; however, their relationship with clinical disease characteristics has yet to be investigated.",
            "The aim of this study was to identify ILC2s in sinus mucosa in patients with CRS and controls and compare ILC2s across characteristics of disease.",
            "A cross-sectional study of patients with CRS undergoing endoscopic sinus surgery was conducted. Sinus mucosal biopsies were obtained during surgery and control tissue from patients undergoing pituitary tumour resection through transphenoidal approach. ILC2s were identified as CD45(+) Lin(-) CD127(+) CD4(-) CD8(-) CRTH2(CD294)(+) CD161(+) cells in single cell suspensions through flow cytometry. ILC2 frequencies, measured as a percentage of CD45(+) cells, were compared across CRS phenotype, endotype, inflammatory CRS subtype and other disease characteristics including blood eosinophils, serum IgE, asthma status and nasal symptom score.",
            "35 patients (40% female, age 48 \u00b1 17 years) including 13 with eosinophilic CRS (eCRS), 13 with non-eCRS and 9 controls were recruited. ILC2 frequencies were associated with the presence of nasal polyps (P = 0.002) as well as high tissue eosinophilia (P = 0.004) and eosinophil-dominant CRS (P = 0.001) (Mann-Whitney U). They were also associated with increased blood eosinophilia (P = 0.005). There were no significant associations found between ILC2s and serum total IgE and allergic disease. In the CRS with nasal polyps (CRSwNP) population, ILC2s were increased in patients with co-existing asthma (P = 0.03). ILC2s were also correlated with worsening nasal symptom score in CRS (P = 0.04)."
        ],
        "LABELS": [
            "BACKGROUND",
            "OBJECTIVE",
            "METHODS",
            "RESULTS"
        ],
        "LONG_ANSWER": "As ILC2s are elevated in patients with CRSwNP, they may drive nasal polyp formation in CRS. ILC2s are also linked with high tissue and blood eosinophilia and have a potential role in the activation and survival of eosinophils during the Th2 immune response. The association of innate lymphoid cells in CRS provides insights into its pathogenesis.",
        "MESHES": [
            "Adult",
            "Aged",
            "Antigens, Surface",
            "Case-Control Studies",
            "Chronic Disease",
            "Eosinophilia",
            "Female",
            "Humans",
            "Hypersensitivity",
            "Immunity, Innate",
            "Immunoglobulin E",
            "Immunophenotyping",
            "Leukocyte Count",
            "Lymphocyte Subsets",
            "Male",
            "Middle Aged",
            "Nasal Mucosa",
            "Nasal Polyps",
            "Neutrophil Infiltration",
            "Patient Outcome Assessment",
            "Rhinitis",
            "Sinusitis",
            "Young Adult"
        ],
        "final_decision": "yes"
    },
```
So for every passage, there will only be one question. There are no multiple questions anywhere.

I verified this by searching the phrase '"QUESTION": [' in VSCode. There were 0 results and it implies that there no instance where there are multiple questions. 

The question is related to the context and answer and hence, I formulated the tasks accordingly.

**Comment by swarooprm** [comment]
Your HW2 is complete now.

Would you like to submit the same tasks to our big project repo https://github.com/allenai/natural-instructions-expansion/pulls? You just need to fork that repo, rename tasks starting from the latest number in the repo and create PR there. This way, you can be part of our research on "learning from instructions instead of learning from examples (conventional machine learning)". This is purely optional and your HW2 grade does not depend on this @JalanshMunshi

**Comment by JalanshMunshi** [comment]
@swarooprm 
Sure. I will create a PR during the weekend or next week. Have got a lot of stuff on my plate at the moment.

Will that be okay?

**Comment by swarooprm** [comment]
> @swarooprm
> Sure. I will create a PR during the weekend or next week. Have got a lot of stuff on my plate at the moment.
> 
> Will that be okay?

Sure. That will be okay.

**Comment by swarooprm** [comment]
@JalanshMunshi  Just a reminder that, if you plan to submit these tasks to the main Github repo and join our research project, Monday (27th Sept) is the deadline. Again, this is optional and independent of your HW2 grade.

**Comment by JalanshMunshi** [comment]
@swarooprm 
Raised a PR on the repo you mentioned.
https://github.com/allenai/natural-instructions-expansion/pull/328

**Pull request closed without merging**
