### PR TITLE
Mihir: Task 777 780 hyperpartisan data & hotpot qa

### PR DESCRIPTION
**Pull request by sadneyap**

### CODE REVIEW

**Comment by swarooprm** [comment]
@Mihir3009, Wondering if you can review these tasks?

**Comment by Mihir3009** [comment]
General:
1. Give a link to each dataset in the source. Something like this: Source: [ Dataset Name (Link - )]
2. Update Readme:
-> Change categories
-> Change summary like this:
Task 778: Determine whether a given set of news articles are hyperpartisan 
Task 779: Generate answer to a given question based on multiple context passages
Task 780: Generate titles of passages that contains supporting facts to answer a question


Task 777:

1. Change category to "Answer Generation" (change file name accordingly).
2. Change definition to this:

`In this task, you need to count the number of vowels that appears in the given passage.`

Task 778:

1. Let's make the definition more comprehensive:

-> In the input, it is not clear about what you classifying. Basically, you wrote that the passage contains news articles. So there is a label for each article or for all articles you generate the same label. In that case, write like this, "In this task, you are given a passage (i.e., set of news articles) as input. ....."

Task 779:

1. You said in the definition that you are given multiple passages, however, there are sentences in the input. Please change those to passages, and indicate each passage by passage_1:, passage_2:, etc.
2. Remove unnecessary brackets like {} from the input

Task 780:

My suggestion is basically to change the Task if possible,  just do this (or add one more task):
-> Given a title, passage, question, answer as input, generate 'yes' if this contains supporting fact to the answer, or generate 'no' otherwise.

If you want to keep this task:

1. Change category to 'Answer Generation'
2. Change the definition to this:

`In this task, you are given multiple passages, their titles, question and given answer to a question. Your task is to find the titles of the passages which contain supporting facts. There may be multiple supporting facts.`

3. Change input format to this:

"Input": "Passage_1: Title- Text-, Passage_2: Title- Text-, ...., Question:, Answer:"
"Output": [Titles]

**Comment by Mihir3009** [comment]
You haven't addressed all the comments. Moreover keep .json files from only in tasks and delete from other places.

**Comment by swarooprm** [comment]
Can you address reivewer comments @sadneyap  so that I can grade your HW?

**Comment by sadneyap** [comment]
The reviewer's comments have been addressed.

**Comment by swarooprm** [comment]
@Mihir3009, check and let me know if you are happy or have any other feedback?

**Comment by Mihir3009** [comment]
@swarooprm I am happy with this HW. Everything looks good to me.

**Comment by swarooprm** [comment]
Your HW2 is complete now.

Would you like to submit the same tasks to our big project repo https://github.com/allenai/natural-instructions-expansion/pulls? You just need to fork that repo, rename tasks starting from the latest number in the repo and create PR there. This way, you can be part of our research on "learning from instructions instead of learning from examples (conventional machine learning)". This is purely optional and your HW2 grade does not depend on this @sadneyap

**Comment by swarooprm** [comment]
@sadneyap  Just a reminder that, if you plan to submit these tasks to the main Github repo and join our research project, Monday (27th Sept) is the deadline. Again, this is optional and independent of your HW2 grade.

**Pull request closed without merging**
