### PR TITLE
Anjana: Task 857-860: msr_sqa dataset

### PR DESCRIPTION
**Pull request by sarnshreya**
Task 857-860: msr_sqa dataset

1. Question generation
2. Given a passage and a question, Answer generation
3. Incorrect answer generation
4. Given a passage, Arithmetic question and answer generation

### CODE REVIEW

**Comment by swarooprm** [comment]
Hi @sarnshreya, your tests are failing, Could you fix your files so that tests pass and we can consider your PR for evaluation.

**Comment by sarnshreya** [comment]
Hi Swaroop,

Sorry I missed to check that.
Yes, I will fix it by today, update the PR,  and send you an email.
Thank you

**Comment by sarnshreya** [comment]
@swarooprm, 
fixed the issues with failing tests (which was due to duplicate data in the datasource itself).
please review the updated PR.

**Comment by swarooprm** [comment]
@aarunku5, wondering if you can help review this PR?

**Comment by aarunku5** [comment]
Thanks, a couple of edits:

1) Include the web link for the datasets in the source for all tasks.

2) For all the tasks, rephrase the beginning of the definition to be along the lines of "In this task, you are given ___, and must ___." (split it into 2 sentences if it gets too long)

**Comment by sarnshreya** [comment]
@aarunku5 , I updated as per the reviews.  can you please check again?

**Comment by swarooprm** [comment]
> @aarunku5 , I updated as per the reviews. can you please check again?

@aarunku5, check if you are happy or have any other feedback?

**Comment by aarunku5** [comment]
Thanks. Modify all the definitions to include that the passage is a csv file or data in a tabular format and you should be good to go.

**Comment by swarooprm** [comment]
> Thanks. Modify all the definitions to include that the passage is a csv file or data in a tabular format and you should be good to go.

@sarnshreya, can you do the changes soon so that I can evaluate your HW?

**Comment by sarnshreya** [comment]
> @sarnshreya, can you do the changes soon so that I can evaluate your HW?

 Yeah, will do it soon today

**Comment by sarnshreya** [comment]
@aarunku5  @swarooprm Please review the changes.

**Comment by swarooprm** [comment]
> @aarunku5 @swarooprm Please review the changes.

Does not look correct when the first sentence of definition is "The passage is a CSV file".  I would say replace this line to "Note that the passage is given in tabular format" and move it after the first sentence where you say "In this task, you are give.. and you need to.."

Your HW will be complete as soon you do this change @sarnshreya

**Comment by swarooprm** [comment]
I still see "The passage is a CSV file". In the comment above, I mentioned to replace this by "Note that the passage is given in tabular format"

**Comment by sarnshreya** [comment]
> I still see "The passage is a CSV file". In the comment above, I mentioned to replace this by "Note that the passage is given in tabular format"

Oh, I misunderstood your comment to be about the placing the text at the right place in the `Definition`.

It is fixed now. can you please verify?

**Comment by swarooprm** [comment]
Your HW2 is complete now.

Would you like to submit the same tasks to our big project repo https://github.com/allenai/natural-instructions-expansion/pulls? You just need to fork that repo, rename tasks starting from the latest number in the repo and create PR there. This way, you can be part of our research on "learning from instructions instead of learning from examples (conventional machine learning)". This is purely optional and your HW2 grade does not depend on this @sarnshreya

**Comment by sarnshreya** [comment]
> Your HW2 is complete now.
> 
> Would you like to submit the same tasks to our big project repo https://github.com/allenai/natural-instructions-expansion/pulls? You just need to fork that repo, rename tasks starting from the latest number in the repo and create PR there. This way, you can be part of our research on "learning from instructions instead of learning from examples (conventional machine learning)". This is purely optional and your HW2 grade does not depend on this @sarnshreya

Yes, sure. I will do that. I am willing to submit a separate PR for some more tasks based on other datasets. Is it okay?

**Comment by swarooprm** [comment]
> > Your HW2 is complete now.
> > Would you like to submit the same tasks to our big project repo https://github.com/allenai/natural-instructions-expansion/pulls? You just need to fork that repo, rename tasks starting from the latest number in the repo and create PR there. This way, you can be part of our research on "learning from instructions instead of learning from examples (conventional machine learning)". This is purely optional and your HW2 grade does not depend on this @sarnshreya
> 
> Yes, sure. I will do that. I am willing to submit a separate PR for some more tasks based on other datasets. Is it okay?

Yes, please go ahead. Make sure to keep your new tasks in a different PR.

**Pull request closed without merging**
