### PR TITLE
Anjana: NLP Assignment2- Task393-399

### PR DESCRIPTION
**Pull request by divya0627**

### CODE REVIEW

**Comment by swarooprm** [comment]
@aarunku5, wondering if you can help review this PR?

**Comment by aarunku5** [comment]
393- Have spaces for options with two words in them.  Change the output to be 1/2/3 etc. instead of the word. Specify in the definition that they must indicate their choice with the choice number as output, for example, 1. athlete means the output should be 1.

394- Remove "Things to avoid:", you can just have the sentence starting at "Don't ....".

395-  Don't capitalize "question" in the definition. Give spaces for two-word options. Modify to "The incorrect answer should be among one of the following categories: "

396- Minor grammatical errors in the definition.   Remove "Things to avoid:" like 394.

397- Task category is classification. Change in the readme as well. Remove "Things to avoid:" like 394.

398-  Minor grammatical errors in the definition.

399- Remove "Things to avoid:" like 394.

Run your definitions and explanations for all tasks through Grammarly to verify before submitting.

**Comment by divya0627** [comment]
@aarunku5  For task 397, the options generated are randomly chosen from 14 categories and are different for each instance. In this case, will it come under classification or answer generation?

**Comment by aarunku5** [comment]
You can have 397 as answer generation in that case.

**Comment by divya0627** [comment]
@aarunku5 Made changes as per the review and pushed it.

**Comment by aarunku5** [comment]
Thanks, all the tasks look good to me @swarooprm

**Comment by swarooprm** [comment]
Your HW2 is complete now.

Would you like to submit the same tasks to our big project repo https://github.com/allenai/natural-instructions-expansion/pulls? You just need to fork that repo, rename tasks starting from the latest number in the repo and create PR there. This way, you can be part of our research on "learning from instructions instead of learning from examples (conventional machine learning)". This is purely optional and your HW2 grade does not depend on this @divya0627 ?

**Comment by divya0627** [comment]
@swarooprm Yes, I want to submit the tasks to the big project repo.

**Pull request closed without merging**
