### PR TITLE
Complete: CSE 576 NLP Assignement - TASKS 544 - 548

### PR DESCRIPTION
**Pull request by PraveenMathew92**

### CODE REVIEW

**Comment by swarooprm** [comment]
@Mihir3009, Wondering if you can help review these tasks?

**Comment by Mihir3009** [comment]
General:
1. In the source key, just put the link of the dataset in the bracket, i.e., Dataset Name (Link - [dataset link]). Something like this for better representation.
2.  More importantly, we need to define the syntax of the regex operation in the input definition. Basically, let's briefly define what all the recurring keywords/operations (concat, repeat, repeatrange, etc.) mean in the regex structure. [Do for all tasks]

Task 544:

Let's make the definition more comprehensive. Change it to this definition:

`In this task, structured regex expression is given as an input and your task is to generate a string as output  which is accepted by the structured regex expression.`
[Add details related to 2nd point at the end of this definition]

Task 546:

1. [Add details related to 2nd point at the end of this definition]

Task 545:

1. Change category to "Sentence Generation".
2. Let's make the definition more comprehensive. Change it to this definition:

`In this task, structured regex expression is given as an input and your task is to generate a description in natural language for the given structured regex expression. The description should eliminate ambiguity and clearly explain the constraints a string (i.e., generated from regex expression) should follow to match the pattern.` 
[Add details related to 2nd point at the end of this definition]

Task 547:

1. Change category to "Structured Text Generation"
2. Let's make the definition more comprehensive. Change it to this definition:

`In this task, you are given a natural language description of structured regex expression. Your task is to generate the structured regular expression corresponding to the given description.`
[Add details related to 2nd point at the end of this definition]

Task 548:

1. Change category to "Answer Generation"
2.  Let's make the definition more comprehensive. Change it to this definition:

`This task is to choose the correct match from a list of options given for a structured regex. There would be four options given and one of the options is the right match for the given regex. The other three will fail to match the given regex.`
[Add details related to 2nd point at the end of this definition]

**Comment by PraveenMathew92** [comment]
Thanks for the feedback @Mihir3009 . I have updated the Definitions and have included the other required changes in the pull request.

Please let me know if anything else is needed.

**Comment by Mihir3009** [comment]
@swarooprm Looks good to me. Approved from my side.

**Comment by swarooprm** [comment]
Your HW2 is complete.

Would you like to submit the same tasks to our big project repo https://github.com/allenai/natural-instructions-expansion/pulls? You just need to fork that repo, rename tasks starting from the latest number in the repo (which at this point is 591) and create PR there. This way, you can be part of our research on "learning from instructions instead of learning from examples (conventional machine learning)". This is purely optional and your HW2 grade does not depend on this @PraveenMathew92 ?

**Comment by swarooprm** [comment]
@PraveenMathew92  Just a reminder that, if you plan to submit these tasks to the main Github repo and join our research project, Monday (27th Sept) is the deadline. Again, this is optional and independent of your HW2 grade.

**Pull request closed without merging**
